DROP TRIGGER APP_RIM.XBC_TRIG_ELEMENT_UPDATE;

CREATE OR REPLACE TRIGGER APP_RIM.XBC_TRIG_ELEMENT_UPDATE
AFTER UPDATE OF ne_end_date
ON APP_RIM.NM_ELEMENTS_ALL 
DECLARE
/*

*/

BEGIN

    APP_RIM.XBC_CREATE_SECURING_INV.process_globals_enddate;
    APP_RIM.XBC_CREATE_SECURING_INV.clear_globals_enddate;

EXCEPTION WHEN OTHERS THEN
    NULL;
END;
/


