DROP TRIGGER APP_RIM.XBC_TRIG_ELEMENT_UPDATE_ROW;

CREATE OR REPLACE TRIGGER APP_RIM.XBC_TRIG_ELEMENT_UPDATE_ROW
AFTER UPDATE OF ne_end_date
ON APP_RIM.NM_ELEMENTS_ALL FOR EACH ROW
DECLARE
/*

*/

BEGIN

    IF :NEW.NE_END_DATE IS NOT NULL AND :NEW.NE_TYPE = 'S' AND :NEW.NE_NT_TYPE = 'ROAD' THEN
        APP_RIM.XBC_CREATE_SECURING_INV.append_to_globals_enddate(:NEW.NE_ID, :NEW.NE_NT_TYPE);
    END IF;

EXCEPTION WHEN OTHERS THEN
    NULL;
END;
/


