Insert into EXOR.NM_INV_TYPE_ATTRIBS_ALL (
 ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_DEC_PLACES, ITA_SCRN_TEXT, ITA_ID_DOMAIN,
 ITA_VALIDATE_YN, ITA_DTP_CODE, ITA_MAX, ITA_MIN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_END_DATE, ITA_QUERYABLE, ITA_UKPMS_PARAM_NO,
 ITA_UNITS, ITA_FORMAT_MASK, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_QUERY, ITA_DISPLAYED,
 ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
Values (
 'OP', 'IIT_CHR_ATTRIB26', 'Y', 1, 'N', 'VARCHAR2', 1, null, 'Type of Operation', null,
 'Y', null, null, null, 'TYPE_OP', 'TYPE_OP', trunc(sysdate), null, 'Y', null,
 null, null, 'N', 'N', trunc(sysdate), trunc(sysdate), 'EXOR', 'EXOR', null, 'Y',
 1, 'Y', 'UPPER');

Insert into EXOR.NM_INV_TYPE_ATTRIBS_ALL (
 ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_DEC_PLACES, ITA_SCRN_TEXT, ITA_ID_DOMAIN,
 ITA_VALIDATE_YN, ITA_DTP_CODE, ITA_MAX, ITA_MIN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_END_DATE, ITA_QUERYABLE, ITA_UKPMS_PARAM_NO,
 ITA_UNITS, ITA_FORMAT_MASK, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_QUERY, ITA_DISPLAYED,
 ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
Values (
 'OP', 'IIT_NUM_ATTRIB16', 'Y', 2, 'N', 'NUMBER', 8, null, 'Route NE ID', null,
 'Y', null, null, null, 'RT_NE_ID', 'RT_NE_ID', trunc(sysdate), null, 'Y', null,
 null, null, 'N', 'N', trunc(sysdate), trunc(sysdate), 'EXOR', 'EXOR', null, 'Y',
 1, 'Y', 'UPPER');

 Insert into NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('OP', 'IIT_CHR_ATTRIB27', 'Y', 3, 'N', 
    'VARCHAR2', 50, 'Route NE UNQUE', 'Y', 'RT_NE_UNIQUE', 
    'RT_NE_UNIQUE', to_date(sysdate), 'Y', 'N', 'N', 
    to_date(sysdate), to_date(sysdate), 'EXOR', 'EXOR', 'Y', 
    1, 'Y', 'UPPER');
 
Insert into EXOR.NM_INV_TYPE_ATTRIBS_ALL (
 ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_DEC_PLACES, ITA_SCRN_TEXT, ITA_ID_DOMAIN,
 ITA_VALIDATE_YN, ITA_DTP_CODE, ITA_MAX, ITA_MIN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_END_DATE, ITA_QUERYABLE, ITA_UKPMS_PARAM_NO,
 ITA_UNITS, ITA_FORMAT_MASK, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_QUERY, ITA_DISPLAYED,
 ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
Values (
 'OP', 'IIT_NUM_ATTRIB17', 'Y', 4, 'N', 'NUMBER', 8, 3, 'BEGIN Mile Point', null,
 'Y', null, null, null, 'BEGIN_MP', 'BEGIN_MP', trunc(sysdate), null, 'Y', null,
 null, null, 'N', 'N', trunc(sysdate), trunc(sysdate), 'EXOR', 'EXOR', null, 'Y',
 1, 'Y', 'UPPER');

Insert into EXOR.NM_INV_TYPE_ATTRIBS_ALL (
 ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_DEC_PLACES, ITA_SCRN_TEXT, ITA_ID_DOMAIN,
 ITA_VALIDATE_YN, ITA_DTP_CODE, ITA_MAX, ITA_MIN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_END_DATE, ITA_QUERYABLE, ITA_UKPMS_PARAM_NO,
 ITA_UNITS, ITA_FORMAT_MASK, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_QUERY, ITA_DISPLAYED,
 ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
Values (
 'OP', 'IIT_NUM_ATTRIB18', 'Y', 5, 'N', 'NUMBER', 8, 3, 'END Mile Point', null,
 'Y', null, null, null, 'END_MP', 'END_MP', trunc(sysdate), null, 'Y', null,
 null, null, 'N', 'N', trunc(sysdate), trunc(sysdate), 'EXOR', 'EXOR', null, 'Y',
 1, 'Y', 'UPPER');

  
Insert into EXOR.NM_INV_TYPE_ATTRIBS_ALL (
 ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_DEC_PLACES, ITA_SCRN_TEXT, ITA_ID_DOMAIN,
 ITA_VALIDATE_YN, ITA_DTP_CODE, ITA_MAX, ITA_MIN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_END_DATE, ITA_QUERYABLE, ITA_UKPMS_PARAM_NO,
 ITA_UNITS, ITA_FORMAT_MASK, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_QUERY, ITA_DISPLAYED,
 ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
Values (
 'OP', 'IIT_CHR_ATTRIB28', 'Y', 6, 'N', 'VARCHAR2', 50, null, 'District', null,
 'Y', null, null, null, 'DISTRICT', 'DISTRICT', trunc(sysdate), null, 'Y', null,
 null, null, 'N', 'N', trunc(sysdate), trunc(sysdate), 'EXOR', 'EXOR', null, 'Y',
 1, 'Y', 'UPPER');

Insert into EXOR.NM_INV_TYPE_ATTRIBS_ALL (
 ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_DEC_PLACES, ITA_SCRN_TEXT, ITA_ID_DOMAIN,
 ITA_VALIDATE_YN, ITA_DTP_CODE, ITA_MAX, ITA_MIN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_END_DATE, ITA_QUERYABLE, ITA_UKPMS_PARAM_NO,
 ITA_UNITS, ITA_FORMAT_MASK, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_QUERY, ITA_DISPLAYED,
 ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
Values (
 'OP', 'IIT_CHR_ATTRIB29', 'Y', 7, 'N', 'VARCHAR2', 50, null, 'COUNTY NAME', null,
 'Y', null, null, null, 'COUNTY_NAME', 'COUNTY_NAME', trunc(sysdate), null, 'Y', null,
 null, null, 'N', 'N', trunc(sysdate), trunc(sysdate), 'EXOR', 'EXOR', null, 'Y',
 1, 'Y', 'UPPER');
 
Insert into EXOR.NM_INV_TYPE_ATTRIBS_ALL (
 ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_DEC_PLACES, ITA_SCRN_TEXT, ITA_ID_DOMAIN,
 ITA_VALIDATE_YN, ITA_DTP_CODE, ITA_MAX, ITA_MIN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_END_DATE, ITA_QUERYABLE, ITA_UKPMS_PARAM_NO,
 ITA_UNITS, ITA_FORMAT_MASK, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_QUERY, ITA_DISPLAYED,
 ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
Values (
 'OP', 'IIT_NUM_ATTRIB21', 'Y', 8, 'N', 'NUMBER', 8, null, 'County Code', null,
 'Y', null, null, null, 'COUNTY', 'COUNTY',trunc(sysdate), null, 'Y', null,
 null, null, 'N', 'N',trunc(sysdate), trunc(sysdate), 'EXOR', 'EXOR', null, 'Y',
 1, 'Y', 'UPPER');

Insert into EXOR.NM_INV_TYPE_ATTRIBS_ALL (
 ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_DEC_PLACES, ITA_SCRN_TEXT, ITA_ID_DOMAIN,
 ITA_VALIDATE_YN, ITA_DTP_CODE, ITA_MAX, ITA_MIN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_END_DATE, ITA_QUERYABLE, ITA_UKPMS_PARAM_NO,
 ITA_UNITS, ITA_FORMAT_MASK, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_QUERY, ITA_DISPLAYED,
 ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
Values (
 'OP', 'IIT_CHR_ATTRIB30', 'Y', 9, 'N', 'VARCHAR2', 8, null, 'Route Prefix', null,
 'Y', null, null, null, 'RT_PREFIX', 'RT_PREFIX', trunc(sysdate), null, 'Y', null,
 null, null, 'N', 'N', trunc(sysdate), trunc(sysdate), 'EXOR', 'EXOR', null, 'Y',
 1, 'Y', 'UPPER');

Insert into EXOR.NM_INV_TYPE_ATTRIBS_ALL (
 ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_DEC_PLACES, ITA_SCRN_TEXT, ITA_ID_DOMAIN,
 ITA_VALIDATE_YN, ITA_DTP_CODE, ITA_MAX, ITA_MIN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_END_DATE, ITA_QUERYABLE, ITA_UKPMS_PARAM_NO,
 ITA_UNITS, ITA_FORMAT_MASK, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_QUERY, ITA_DISPLAYED,
 ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
Values (
 'OP', 'IIT_NUM_ATTRIB19', 'Y', 10, 'N', 'NUMBER', 8, null, 'Route Number', null,
 'Y', null, null, null, 'RT_NUMBER', 'RT_NUMBER',trunc(sysdate), null, 'Y', null,
 null, null, 'N', 'N',trunc(sysdate), trunc(sysdate), 'EXOR', 'EXOR', null, 'Y',
 1, 'Y', 'UPPER');

Insert into EXOR.NM_INV_TYPE_ATTRIBS_ALL (
 ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_DEC_PLACES, ITA_SCRN_TEXT, ITA_ID_DOMAIN,
 ITA_VALIDATE_YN, ITA_DTP_CODE, ITA_MAX, ITA_MIN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_END_DATE, ITA_QUERYABLE, ITA_UKPMS_PARAM_NO,
 ITA_UNITS, ITA_FORMAT_MASK, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_QUERY, ITA_DISPLAYED,
 ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
Values (
 'OP', 'IIT_CHR_ATTRIB31', 'Y', 11, 'N', 'VARCHAR2', 8, null, 'Route Suffix', null,
 'Y', null, null, null, 'RT_SUFFIX', 'RT_SUFFIX', trunc(sysdate), null, 'Y', null,
 null, null, 'N', 'N', trunc(sysdate), trunc(sysdate), 'EXOR', 'EXOR', null, 'Y',
 1, 'Y', 'UPPER');

Insert into EXOR.NM_INV_TYPE_ATTRIBS_ALL (
 ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_DEC_PLACES, ITA_SCRN_TEXT, ITA_ID_DOMAIN,
 ITA_VALIDATE_YN, ITA_DTP_CODE, ITA_MAX, ITA_MIN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_END_DATE, ITA_QUERYABLE, ITA_UKPMS_PARAM_NO,
 ITA_UNITS, ITA_FORMAT_MASK, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_QUERY, ITA_DISPLAYED,
 ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
Values (
 'OP', 'IIT_NUM_ATTRIB20', 'Y', 12, 'N', 'NUMBER', 8, null, 'Route Section', null,
 'Y', null, null, null, 'RT_SECTION', 'RT_SECTION', trunc(sysdate), null, 'Y', null,
 null, null, 'N', 'N', trunc(sysdate), trunc(sysdate), 'EXOR', 'EXOR', null, 'Y',
 1, 'Y', 'UPPER');

Insert into EXOR.NM_INV_TYPE_ATTRIBS_ALL (
 ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_DEC_PLACES, ITA_SCRN_TEXT, ITA_ID_DOMAIN,
 ITA_VALIDATE_YN, ITA_DTP_CODE, ITA_MAX, ITA_MIN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_END_DATE, ITA_QUERYABLE, ITA_UKPMS_PARAM_NO,
 ITA_UNITS, ITA_FORMAT_MASK, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_QUERY, ITA_DISPLAYED,
 ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
Values (
 'OP', 'IIT_CHR_ATTRIB66', 'Y', 13, 'N', 'VARCHAR2', 240, null, 'Route Description', null,
 'Y', null, null, null, 'RT_DESCR', 'RT_DESCR', trunc(sysdate), null, 'Y', null,
 null, null, 'N', 'N', trunc(sysdate), trunc(sysdate), 'EXOR', 'EXOR', null, 'Y',
 1, 'Y', 'UPPER');

Insert into EXOR.NM_INV_TYPE_ATTRIBS_ALL (
 ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_DEC_PLACES, ITA_SCRN_TEXT, ITA_ID_DOMAIN,
 ITA_VALIDATE_YN, ITA_DTP_CODE, ITA_MAX, ITA_MIN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_END_DATE, ITA_QUERYABLE, ITA_UKPMS_PARAM_NO,
 ITA_UNITS, ITA_FORMAT_MASK, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_QUERY, ITA_DISPLAYED,
 ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
Values (
 'OP', 'IIT_CHR_ATTRIB33', 'Y', 14, 'N', 'VARCHAR2', 8, null, 'Gov Level', null,
 'Y', null, null, null, 'GOV_LEVEL', 'GOV_LEVEL', trunc(sysdate), null, 'Y', null,
 null, null, 'N', 'N', trunc(sysdate), trunc(sysdate), 'EXOR', 'EXOR', null, 'Y',
 1, 'Y', 'UPPER');

