--
SET TERM ON
PROMPT *** RUNNING: XBCC_EQUIPMENTVIEW.SQL ***
SET TERM OFF
--
SET FEEDBACK ON
START XBCC_EQUIPMENTVIEW.SQL
SET FEEDBACK OFF
--
--
SET TERM ON
PROMPT *** RUNNING: XBCC_SUBURBVIEW.sql ***
SET TERM OFF
--
SET FEEDBACK ON
START XBCC_SUBURBVIEW.sql
SET FEEDBACK OFF
--
--
SET TERM ON
PROMPT *** RUNNING: xBCC_EAV_input.sql ***
SET TERM OFF
--
SET FEEDBACK ON
START xBCC_EAV_input.sql
SET FEEDBACK OFF
--
--
SET TERM ON
PROMPT *** RUNNING: MV_XBCC_EQUIP_ATTR_VIEWS_ESUR.sql ***
SET TERM OFF
--
SET FEEDBACK ON
START MV_XBCC_EQUIP_ATTR_VIEWS_ESUR.sql
SET FEEDBACK OFF
--
--
SET TERM ON
PROMPT *** RUNNING: xBCC_EquipAttrVeiws.sql ***
SET TERM OFF
--
SET FEEDBACK ON
START xBCC_EquipAttrVeiws.sql
SET FEEDBACK OFF
--
--
