SET DEFINE OFF;
Insert into BRAMS_OWNER.XBCC_EAV_INPUT
   (PRIMARY_VIEW, BRAMS_ASSET, NETWORK, XSP, LAST_COMPLETE)
 Values
   ('XBEX_KERB_VERGE', 'KERB', 'KCOR', 'XKE,XKO', TO_DATE('04/26/2014 00:26:26', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BRAMS_OWNER.XBCC_EAV_INPUT
   (PRIMARY_VIEW, BRAMS_ASSET, NETWORK, XSP, LAST_COMPLETE)
 Values
   ('XBEX_ASOW_MEDIAN', 'ASOW', 'MED', 'XRM, XCM, XMKE, XMKO, XRKE, XRKO', TO_DATE('04/26/2014 00:55:20', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BRAMS_OWNER.XBCC_EAV_INPUT
   (PRIMARY_VIEW, BRAMS_ASSET, NETWORK, XSP, LAST_COMPLETE)
 Values
   ('XBEX_PLAY_ROAD', 'PLAY', 'RDCO', 'XCS,XCE1,XCO1', TO_DATE('04/25/2014 08:19:53', 'MM/DD/YYYY HH24:MI:SS'));
Insert into BRAMS_OWNER.XBCC_EAV_INPUT
   (PRIMARY_VIEW, BRAMS_ASSET, NETWORK, XSP, LAST_COMPLETE)
 Values
   ('XBEX_OPDN_VERGE', 'OPDN', 'VECO', 'XVE1,XVO1', TO_DATE('04/26/2014 00:31:07', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
