SET DEFINE OFF;
MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_1_1_DD1_1A' as HMO_MODULE,
  'Community Area: &P6_PARAM2. for &P6_PARAM3.' as HMO_TITLE,
  'WPR_4_1_1_DD1_1A' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_1_1_DD1_1B' as HMO_MODULE,
  'Community Area: &P6_PARAM2. for &P6_PARAM3.' as HMO_TITLE,
  'WPR_4_1_1_DD1_1B' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_1_1_TOP_1A' as HMO_MODULE,
  'Report Set 1' as HMO_TITLE,
  'WPR_4_1_1_TOP_1A' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_1_1_TOP_1B' as HMO_MODULE,
  'Report Set 1' as HMO_TITLE,
  'WPR_4_1_1_TOP_1B' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_1_2_DD1_2A' as HMO_MODULE,
  'Community Area: &P6_PARAM2. for &P6_PARAM3.' as HMO_TITLE,
  'WPR_4_1_2_DD1_2A' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_1_2_DD1_2B' as HMO_MODULE,
  'Community Area: &P6_PARAM2. for &P6_PARAM3.' as HMO_TITLE,
  'WPR_4_1_2_DD1_2B' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_1_2_TOP_2A' as HMO_MODULE,
  'Report Set 1' as HMO_TITLE,
  'WPR_4_1_2_TOP_2A' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_1_2_TOP_2B' as HMO_MODULE,
  'Report Set 1' as HMO_TITLE,
  'WPR_4_1_2_TOP_2B' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_1_3_DD1_3A' as HMO_MODULE,
  'Community Area: &P6_PARAM2. for &P6_PARAM3.' as HMO_TITLE,
  'WPR_4_1_3_DD1_3A' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_1_3_DD1_3B' as HMO_MODULE,
  'Community Area: &P6_PARAM2. for &P6_PARAM3.' as HMO_TITLE,
  'WPR_4_1_3_DD1_3B' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_1_3_TOP_3A' as HMO_MODULE,
  'Report Set 1' as HMO_TITLE,
  'WPR_4_1_3_TOP_3A' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_1_3_TOP_3B' as HMO_MODULE,
  'Report Set 1' as HMO_TITLE,
  'WPR_4_1_3_TOP_3B' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_1_4_DD1_4A' as HMO_MODULE,
  'Community Area: &P6_PARAM2. for &P6_PARAM3.' as HMO_TITLE,
  'WPR_4_1_4_DD1_4A' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_1_4_DD1_4B' as HMO_MODULE,
  'Community Area: &P6_PARAM2. for &P6_PARAM3.' as HMO_TITLE,
  'WPR_4_1_4_DD1_4B' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_1_4_TOP_4A' as HMO_MODULE,
  'Report Set 1' as HMO_TITLE,
  'WPR_4_1_4_TOP_4A' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_1_4_TOP_4B' as HMO_MODULE,
  'Report Set 1' as HMO_TITLE,
  'WPR_4_1_4_TOP_4B' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_1_5_DD1_5A' as HMO_MODULE,
  'Community Area: &P6_PARAM2. for &P6_PARAM3.' as HMO_TITLE,
  'WPR_4_1_5_DD1_5A' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_1_5_TOP_5A' as HMO_MODULE,
  'Report Set 1' as HMO_TITLE,
  'WPR_4_1_5_TOP_5A' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_2_2_DD1_1A' as HMO_MODULE,
  'Community Area: &P6_PARAM2. for &P6_PARAM3.' as HMO_TITLE,
  'WPR_4_2_2_DD1_1A' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_2_2_DD1_1B' as HMO_MODULE,
  'Community Area: &P6_PARAM2.' as HMO_TITLE,
  'WPR_4_2_2_DD1_1B' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_2_2_DD1_1C' as HMO_MODULE,
  'Community Area: &P6_PARAM2. for &P6_PARAM3.' as HMO_TITLE,
  'WPR_4_2_2_DD1_1C' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_2_2_TOP_1A' as HMO_MODULE,
  'Report Set 2 (1A)' as HMO_TITLE,
  'WPR_4_2_2_TOP_1A' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_2_2_TOP_1B' as HMO_MODULE,
  'Report Set 2 (Find and Fix)' as HMO_TITLE,
  'WPR_4_2_2_TOP_1B' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_2_2_TOP_1C' as HMO_MODULE,
  'Report Set 2 (Reactive Attendance)' as HMO_TITLE,
  'WPR_4_2_2_TOP_1C' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_3_1_DD1_7A' as HMO_MODULE,
  '&P6_PARAM2. for &P6_PARAM3.' as HMO_TITLE,
  'WPR_4_3_1_DD1_7A' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_3_1_TOP_7A' as HMO_MODULE,
  'Report Set 3 (7A)' as HMO_TITLE,
  'WPR_4_3_1_TOP_7A' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_3_2_DD1_7B' as HMO_MODULE,
  '&P6_PARAM2. for &P6_PARAM3.' as HMO_TITLE,
  'WPR_4_3_2_DD1_7B' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_3_2_TOP_7B' as HMO_MODULE,
  'Report Set 3 (7B)' as HMO_TITLE,
  'WPR_4_3_2_TOP_7B' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_3_3_DD1_7C' as HMO_MODULE,
  '&P6_PARAM2. for &P6_PARAM3.' as HMO_TITLE,
  'WPR_4_3_3_DD1_7C' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WPR_4_3_3_TOP_7C' as HMO_MODULE,
  'Report Set 3 (7C)' as HMO_TITLE,
  'WPR_4_3_3_TOP_7C' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

COMMIT;
