SET DEFINE OFF;
MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_1_1_DD1_1A' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_1_1_DD1_1B' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_1_1_TOP_1A' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_1_1_TOP_1B' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_1_2_DD1_2A' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_1_2_DD1_2B' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_1_2_TOP_2A' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_1_2_TOP_2B' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_1_3_DD1_3A' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_1_3_DD1_3B' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_1_3_TOP_3A' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_1_3_TOP_3B' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_1_4_DD1_4A' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_1_4_DD1_4B' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_1_4_TOP_4A' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_1_4_TOP_4B' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_1_5_DD1_5A' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_1_5_TOP_5A' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_2_2_DD1_1A' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_2_2_DD1_1B' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_2_2_DD1_1C' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_2_2_TOP_1A' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_2_2_TOP_1B' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_2_2_TOP_1C' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_3_1_DD1_7A' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_3_1_TOP_7A' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_3_2_DD1_7B' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_3_2_TOP_7B' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_3_3_DD1_7C' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WPR_4_3_3_TOP_7C' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

COMMIT;
