--nm_inv_domains
--nm_inv_attrib_lookup

SET DEFINE OFF;
Insert into NM_INV_DOMAINS
   (ID_DOMAIN, ID_TITLE, ID_START_DATE, ID_DATATYPE, ID_DATE_CREATED, 
    ID_DATE_MODIFIED, ID_MODIFIED_BY, ID_CREATED_BY)
 Values
   ('PROVIDER', 'A LIST OF VAILD PROVIDERS FOR RSD', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'VARCHAR2',sysdate, 
    sysdate, 'RAMS', 'RAMS');
	
Insert into NM_INV_DOMAINS
   (ID_DOMAIN, ID_TITLE, ID_START_DATE, ID_DATATYPE, ID_DATE_CREATED, 
    ID_DATE_MODIFIED, ID_MODIFIED_BY, ID_CREATED_BY)
 Values
   ('RSD_YN', 'Single Letter Yes/No Orginally for the RSD Asset', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'VARCHAR2',sysdate, 
    sysdate, 'RAMS', 'RAMS');
COMMIT;




----
-----
----
----
SET DEFINE OFF;
Insert into NM_INV_ATTRI_LOOKUP_ALL
   (IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ, 
    IAL_DATE_CREATED, IAL_DATE_MODIFIED, IAL_MODIFIED_BY, IAL_CREATED_BY)
 Values
   ('RSD_YN', 'Y', 'Yes', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 1, 
    TO_DATE('12/31/2014 08:01:20', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/31/2014 08:01:20', 'MM/DD/YYYY HH24:MI:SS'), 'RAMS', 'RAMS');
Insert into NM_INV_ATTRI_LOOKUP_ALL
   (IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ, 
    IAL_DATE_CREATED, IAL_DATE_MODIFIED, IAL_MODIFIED_BY, IAL_CREATED_BY)
 Values
   ('RSD_YN', 'N', 'No', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 2, 
    TO_DATE('12/31/2014 08:01:20', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('12/31/2014 08:01:20', 'MM/DD/YYYY HH24:MI:SS'), 'RAMS', 'RAMS');
COMMIT;
