SET DEFINE OFF;
MERGE INTO HIGHWAYS.HIG_MODULES A USING
 (SELECT
  'IM41016d' as HMO_MODULE,
  'EOT Request Report (EOP) - TOR' as HMO_TITLE,
  'IM41016d' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIGHWAYS.HIG_MODULES A USING
 (SELECT
  'IM41037a' as HMO_MODULE,
  'Rejected Work Orders Report - Task Order Requests' as HMO_TITLE,
  'IM41037a' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIGHWAYS.HIG_MODULES A USING
 (SELECT
  'IM41038a' as HMO_MODULE,
  'Held Work Orders Report' as HMO_TITLE,
  'IM41038a' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIGHWAYS.HIG_MODULES A USING
 (SELECT
  'IM41041a' as HMO_MODULE,
  'Updated EOPs Report' as HMO_TITLE,
  'IM41041a' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIGHWAYS.HIG_MODULES A USING
 (SELECT
  'IM41041b' as HMO_MODULE,
  'Updated EOPs Report - TOR' as HMO_TITLE,
  'IM41041b' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

COMMIT;

SET DEFINE OFF;
MERGE INTO HIGHWAYS.HIG_MODULE_ROLES A USING
 (SELECT
  'IM41041a' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIGHWAYS.HIG_MODULE_ROLES A USING
 (SELECT
  'IM41041b' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIGHWAYS.HIG_MODULE_ROLES A USING
 (SELECT
  'IM41038a' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIGHWAYS.HIG_MODULE_ROLES A USING
 (SELECT
  'IM41037a' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIGHWAYS.HIG_MODULE_ROLES A USING
 (SELECT
  'IM41016d' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

COMMIT;
