Insert into EXOR.NM_INV_TYPE_ATTRIBS_ALL (
 ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_DEC_PLACES, ITA_SCRN_TEXT, ITA_ID_DOMAIN,
 ITA_VALIDATE_YN, ITA_DTP_CODE, ITA_MAX, ITA_MIN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_END_DATE, ITA_QUERYABLE, ITA_UKPMS_PARAM_NO,
 ITA_UNITS, ITA_FORMAT_MASK, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_QUERY, ITA_DISPLAYED,
 ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
Values (
 'APRC', 'IIT_CHR_ATTRIB26', 'Y', 1, 'N', 'VARCHAR2', 1, null, 'Intersection Type', null,
 'Y', null, null, null, 'INTERSECTION_TYPE', 'INTERSECTION_TYPE', to_date('01-JAN-1950'), null, 'Y', null,
 null, null, 'N', 'N', to_date('01-JAN-1950'), to_date('01-JAN-1950'), 'EXOR', 'EXOR', null, 'Y',
 1, 'Y', 'UPPER');

Insert into EXOR.NM_INV_TYPE_ATTRIBS_ALL (
 ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_DEC_PLACES, ITA_SCRN_TEXT, ITA_ID_DOMAIN,
 ITA_VALIDATE_YN, ITA_DTP_CODE, ITA_MAX, ITA_MIN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_END_DATE, ITA_QUERYABLE, ITA_UKPMS_PARAM_NO,
 ITA_UNITS, ITA_FORMAT_MASK, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_QUERY, ITA_DISPLAYED,
 ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
Values (
 'APRC', 'IIT_NUM_ATTRIB16', 'Y', 2, 'N', 'NUMBER', 8, null, 'Intersection ID', null,
 'Y', null, null, null, 'Intersection_ID', 'Intersection_ID', to_date('01-JAN-1950'), null, 'Y', null,
 null, null, 'N', 'N', to_date('01-JAN-1950'), to_date('01-JAN-1950'), 'EXOR', 'EXOR', null, 'Y',
 1, 'Y', 'UPPER');



