   create or replace view c_pod_eop_updated as      
   --
   With Haud as
    (SELECT HAUD_PK_ID HAUD_PK_ID, 
                    HAUD_ATTRIBUTE_NAME HAUD_ATTRIBUTE_NAME,
                    MAX (HAUD_TIMESTAMP) HAUD_TIMESTAMP
               FROM HIG_AUDITS
              WHERE 1=1
                    AND HAUD_TABLE_NAME = 'WORK_ORDERS'
                    and HAUD_ATTRIBUTE_NAME = 'WOR_DATE_ATTRIB129'
                    AND HAUD_NEW_VALUE IS NOT null
                    AND HAUD_TIMESTAMP >= SYSDATE - 30.1                    
           GROUP BY HAUD_PK_ID, HAUD_ATTRIBUTE_NAME)    
  --
  SELECT DISTINCT
        WOL.WORK_ORDER_LINE_ID,
          DISCO.JG_GET_DEC_INV_ATTR_VALUE ('WFX$',
                                           'WOR_CHAR_ATTRIB101',
                                           WOR.WOR_CHAR_ATTRIB101)
             AS "WO_EOP",
          1 REQUESTS
     FROM IMF_MAI_WORK_ORDERS_ALL_ATTRIB WOR,
          IMF_MAI_WORK_ORDER_LINES WOL,
          IMF_MAI_DEFECT_REPAIRS DEF,
          IMF_MAI_BUDGETS BUD,
          CONTRACTS C,
          IMF_NET_NETWORK_MEMBERS NET,
          POD_BUDGET_SECURITY BUD_SEC,
          POD_NM_ELEMENT_SECURITY ELE_SEC,
          (  SELECT HAUD_PK_ID RA_HAUD_PK_ID, HAUD_ATTRIBUTE_NAME RA_HAUD_ATTRIBUTE_NAME, HAUD_TIMESTAMP RA_MAX_TS FROM HAUD) RA,  -- moved into With
          (SELECT HUS_ADMIN_UNIT USER_AU
             FROM HIG_USERS
            WHERE HUS_USERNAME = USER) AU,
          (SELECT NVL (MWU_RESTRICT_BY_ROAD_GROUP, 'N') RD_RST,
                  NVL (MWU_RESTRICT_BY_WORKCODE, 'N') WC_RST
             FROM MAI_WO_USERS, HIG_USERS
            WHERE MWU_USER_ID = HUS_USER_ID AND HUS_USERNAME = USER) SEC
    WHERE     WOR.WORKS_ORDER_NUMBER = WORK_ORDER_NUMBER
          AND WOR.WORKS_ORDER_NUMBER = RA_HAUD_PK_ID
          AND WOL.DEFECT_ID = DEF.DEFECT_ID(+)
          AND WOL.BUDGET_ID = BUD.BUDGET_ID
          AND WOL.NETWORK_ELEMENT_ID = CHILD_ELEMENT_ID
          AND PARENT_GROUP_TYPE = 'HMBG'
          AND WORK_ORDER_LINE_STATUS NOT IN ('COMPLETED', 'ACTIONED', 'PRELOHAC', 'INTERIM')
          AND upper(NVL (WORKS_ORDER_DESCRIPTION, 'EMPTY')) NOT LIKE '%**CANCELLED**%'
          AND NVL (WOR_CHAR_ATTRIB100, 'EMPTY') NOT IN ('REJ', 'HLD')
          AND WOR_DATE_ATTRIB129 IS NOT NULL
          AND WOR.CONTRACT_ID = C.CON_ID
          AND USER_AU IN (1, C.CON_ADMIN_ORG_ID)
          --AND WOR_CHAR_ATTRIB101 = DECODE(:P6_PARAM1,'APPROVED','APP','CONDITIONAL','CND','REJECTED','REJ')
          --AND RA_MAX_TS >= sysdate - 360
          AND WOL.NETWORK_ELEMENT_ID = ELE_SEC.ELEMENT_ID
          AND WOL.WORK_CATEGORY = BUD_SEC.BUDGET_CODE;