--
-- hig_module_roles
--
SET DEFINE OFF;
MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM50202' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IMFAZ01' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM100202' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM100203' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM100204' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM100205' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM100206' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM123SP' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM41021' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM20200' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM20201' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM20202' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM20203' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM20204' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM20205' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM41022' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM30200' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM30201' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM30202' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM30203' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM30204' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM30205' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM41031' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM40205' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM40206' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM41037' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM50201' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM50204' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM50205' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM50201' as HMR_MODULE,
  'NET_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM50204' as HMR_MODULE,
  'NET_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM50205' as HMR_MODULE,
  'NET_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM100202' as HMR_MODULE,
  'ENQ_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM100203' as HMR_MODULE,
  'ENQ_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM100204' as HMR_MODULE,
  'ENQ_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM100205' as HMR_MODULE,
  'ENQ_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM100206' as HMR_MODULE,
  'ENQ_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM20200' as HMR_MODULE,
  'TMA_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM20201' as HMR_MODULE,
  'TMA_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM20202' as HMR_MODULE,
  'TMA_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM20203' as HMR_MODULE,
  'TMA_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM20204' as HMR_MODULE,
  'TMA_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM20205' as HMR_MODULE,
  'TMA_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM30200' as HMR_MODULE,
  'TMA_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM30201' as HMR_MODULE,
  'TMA_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM30202' as HMR_MODULE,
  'TMA_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM30203' as HMR_MODULE,
  'TMA_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM30204' as HMR_MODULE,
  'TMA_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM30205' as HMR_MODULE,
  'TMA_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM40205' as HMR_MODULE,
  'MAI_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM40206' as HMR_MODULE,
  'MAI_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'DISCO-LINK' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM41016a' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM41016b' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM41041' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM_LOHAC_AS_00_TOP' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM41015' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM41040' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM41030' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM41020' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM41035' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WOWT002' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WOWT003' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'WOWT001' as HMR_MODULE,
  'IM_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM41016c' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM41023' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'test' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM41036' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM41038' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

MERGE INTO HIG_MODULE_ROLES A USING
 (SELECT
  'IM_LOHAC_AR_00_TOP' as HMR_MODULE,
  'HIG_USER' as HMR_ROLE,
  'NORMAL' as HMR_MODE
  FROM DUAL) B
ON (A.HMR_MODULE = B.HMR_MODULE and A.HMR_ROLE = B.HMR_ROLE)
WHEN NOT MATCHED THEN 
INSERT (
  HMR_MODULE, HMR_ROLE, HMR_MODE)
VALUES (
  B.HMR_MODULE, B.HMR_ROLE, B.HMR_MODE)
WHEN MATCHED THEN
UPDATE SET 
  A.HMR_MODE = B.HMR_MODE;

COMMIT;
