--
-- hig_modules
--
SET DEFINE OFF;
MERGE INTO HIG_MODULES A USING
 (SELECT
  'IMFAZ01' as HMO_MODULE,
  'Faz test POD' as HMO_TITLE,
  'IMFAZ01' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM41016a' as HMO_MODULE,
  ' EOT Request Report (Initial)' as HMO_TITLE,
  'IM41016a' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM41016b' as HMO_MODULE,
  'EOT Request Report (Repeat)' as HMO_TITLE,
  'IM41016b' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM41041' as HMO_MODULE,
  'Updated EOTs Report' as HMO_TITLE,
  'IM41041' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM123SP' as HMO_MODULE,
  'Simon Test 2' as HMO_TITLE,
  'IM123SP' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM41031' as HMO_MODULE,
  'Available Defects Report' as HMO_TITLE,
  'IM41031' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM41037' as HMO_MODULE,
  'Rejected Work Orders Report' as HMO_TITLE,
  'IM41037' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM41022' as HMO_MODULE,
  'Work Order due to be Completed (Lump Sum)' as HMO_TITLE,
  'IM41022' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM41021' as HMO_MODULE,
  'Work Order due to be Completed (Non Def)' as HMO_TITLE,
  'IM41021' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM50202' as HMO_MODULE,
  'Length of Road for Admin Unit &P6_PARAM1.' as HMO_TITLE,
  'IM50202' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'DISCO-LINK' as HMO_MODULE,
  'Discoverer link' as HMO_TITLE,
  'DISCO-LINK' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM100202' as HMO_MODULE,
  'Total Enquiries v Late Enquiries by Month Graph' as HMO_TITLE,
  'IM100202' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM100203' as HMO_MODULE,
  'Enquiries raised in MONTH by Type Table' as HMO_TITLE,
  'IM100203' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM100204' as HMO_MODULE,
  'Late Enquiries raised in MONTH by Type' as HMO_TITLE,
  'IM100204' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM100205' as HMO_MODULE,
  'Enquiries of TYPE raised in MONTH Report' as HMO_TITLE,
  'IM100205' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM100206' as HMO_MODULE,
  'Late Enquiries of TYPE raised in MONTH Report' as HMO_TITLE,
  'IM100206' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM1100' as HMO_MODULE,
  'Road Works' as HMO_TITLE,
  'IM1100' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM1200' as HMO_MODULE,
  'Enquiries' as HMO_TITLE,
  'IM1200' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM20200' as HMO_MODULE,
  'Notices by Month (12 Months) Graph' as HMO_TITLE,
  'IM20200' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM20201' as HMO_MODULE,
  'Sent or Received Notices in Month Table ' as HMO_TITLE,
  'IM20201' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM20202' as HMO_MODULE,
  'Sent or Received Notices in Month for Organisation Report ' as HMO_TITLE,
  'IM20202' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM20203' as HMO_MODULE,
  'Sample Inspections (12 Months) Stacked Bar Chart' as HMO_TITLE,
  'IM20203' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM20204' as HMO_MODULE,
  'Inspection Undertaker Count in Month for Inspection Type Table ' as HMO_TITLE,
  'IM20204' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM20205' as HMO_MODULE,
  'Inspections by Undertaker in Month for Inspection Type Report' as HMO_TITLE,
  'IM20205' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM30200' as HMO_MODULE,
  'Potential FPNs (12 Months) Stacked Bar Chart' as HMO_TITLE,
  'IM30200' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM30201' as HMO_MODULE,
  'Potential FPNs (Non Compliance Reason in Month) Table' as HMO_TITLE,
  'IM30201' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM30202' as HMO_MODULE,
  'Potential FPNs (Non Compliance Reason in Month) of Cat. for Org Report' as HMO_TITLE,
  'IM30202' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM30203' as HMO_MODULE,
  'Cost of Chargeable Inspections (12 Months) Stacked Bar Chart' as HMO_TITLE,
  'IM30203' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM30204' as HMO_MODULE,
  'Inspection Undertaker Count in Month for Inspection Type Table' as HMO_TITLE,
  'IM30204' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM30205' as HMO_MODULE,
  'Inspections by Undertaker in Month for Inspection Type Report' as HMO_TITLE,
  'IM30205' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM40205' as HMO_MODULE,
  'Overdue Repairs (30 Days) of TYPE Report' as HMO_TITLE,
  'IM40205' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM40206' as HMO_MODULE,
  'Overdue Repair Types (30 Days/Top 10) Pie Chart' as HMO_TITLE,
  'IM40206' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM50201' as HMO_MODULE,
  'Length Of Road by Admin Unit Bar Chart' as HMO_TITLE,
  'IM50201' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM50204' as HMO_MODULE,
  'Total Length of Road by Category (Top 5) Pie Chart' as HMO_TITLE,
  'IM50204' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM50205' as HMO_MODULE,
  'Roads of Road Category Report' as HMO_TITLE,
  'IM50205' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM_ENQ' as HMO_MODULE,
  'Enquiries' as HMO_TITLE,
  'IM_ENQ' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM_MAP' as HMO_MODULE,
  'Information Manager MAP Module' as HMO_TITLE,
  'x' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'N' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM_TMA' as HMO_MODULE,
  'Road Works' as HMO_TITLE,
  'IM_TMA' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM41015' as HMO_MODULE,
  'EOT Request' as HMO_TITLE,
  'IM41015' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM41020' as HMO_MODULE,
  'Work Order Due to be Completed' as HMO_TITLE,
  'IM41020' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM41030' as HMO_MODULE,
  'Available Defects' as HMO_TITLE,
  'IM41030' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM41035' as HMO_MODULE,
  'Rejected Work Orders' as HMO_TITLE,
  'IM41035' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM_LOHAC_AS_00_TOP' as HMO_MODULE,
  'lll' as HMO_TITLE,
  'IM_LOHAC_AS_00_TOP' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM41040' as HMO_MODULE,
  'Updated EOTs' as HMO_TITLE,
  'IM41040' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WOWT001' as HMO_MODULE,
  'Work Orders to Instruct' as HMO_TITLE,
  'WOWT001' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WOWT002' as HMO_MODULE,
  'Re-Submitted Work Orders' as HMO_TITLE,
  'WOWT002' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'WOWT003' as HMO_MODULE,
  'Work Orders - Draft Status' as HMO_TITLE,
  'WOWT003' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM41023' as HMO_MODULE,
  'Work Order due to be Completed' as HMO_TITLE,
  'IM41023' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM_LOHAC_AR_00_TOP' as HMO_MODULE,
  'Application Review' as HMO_TITLE,
  'IM_LOHAC_AR_00_TOP' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM41016c' as HMO_MODULE,
  'EOT Request Report (EOP)' as HMO_TITLE,
  'IM41016c' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'test' as HMO_MODULE,
  'TEST' as HMO_TITLE,
  'test' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM41036' as HMO_MODULE,
  'Held Work Orders' as HMO_TITLE,
  'IM41036' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

MERGE INTO HIG_MODULES A USING
 (SELECT
  'IM41038' as HMO_MODULE,
  'Held Work Orders Report' as HMO_TITLE,
  'IM41038' as HMO_FILENAME,
  'WEB' as HMO_MODULE_TYPE,
  NULL as HMO_FASTPATH_OPTS,
  'Y' as HMO_FASTPATH_INVALID,
  'N' as HMO_USE_GRI,
  'IM' as HMO_APPLICATION,
  NULL as HMO_MENU
  FROM DUAL) B
ON (A.HMO_MODULE = B.HMO_MODULE)
WHEN NOT MATCHED THEN 
INSERT (
  HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
  HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
VALUES (
  B.HMO_MODULE, B.HMO_TITLE, B.HMO_FILENAME, B.HMO_MODULE_TYPE, B.HMO_FASTPATH_OPTS, 
  B.HMO_FASTPATH_INVALID, B.HMO_USE_GRI, B.HMO_APPLICATION, B.HMO_MENU)
WHEN MATCHED THEN
UPDATE SET 
  A.HMO_TITLE = B.HMO_TITLE,
  A.HMO_FILENAME = B.HMO_FILENAME,
  A.HMO_MODULE_TYPE = B.HMO_MODULE_TYPE,
  A.HMO_FASTPATH_OPTS = B.HMO_FASTPATH_OPTS,
  A.HMO_FASTPATH_INVALID = B.HMO_FASTPATH_INVALID,
  A.HMO_USE_GRI = B.HMO_USE_GRI,
  A.HMO_APPLICATION = B.HMO_APPLICATION,
  A.HMO_MENU = B.HMO_MENU;

COMMIT;
