DROP TABLE XBCC_SAP_SYNC_SAMPLE CASCADE CONSTRAINTS;

CREATE TABLE XBCC_SAP_SYNC_SAMPLE
(
  INDICATOR  VARCHAR2(1 BYTE),
  BRAMS_ID   NUMBER(10),
  OBJECT     VARCHAR2(30 BYTE),
  NAME       VARCHAR2(30 BYTE),
  "START"    NUMBER(18,2),
  END        NUMBER(18,2)
);


Insert into XBCC_SAP_SYNC_SAMPLE
   (INDICATOR, BRAMS_ID, OBJECT, NAME, "START", END)
 Values
   ('I', 1234512345, 'ROAD', 'ANN STREET', 0, 
    300);
Insert into XBCC_SAP_SYNC_SAMPLE
   (INDICATOR, BRAMS_ID, OBJECT, NAME, "START", END)
 Values
   ('I', 1234512345, 'SUBURB_NAME', 'CBD', 0, 
    200);
Insert into XBCC_SAP_SYNC_SAMPLE
   (INDICATOR, BRAMS_ID, OBJECT, NAME, "START", END)
 Values
   ('I', 1234512345, 'SUBURB_NAME', 'NEW FARM', 200, 
    300);
Insert into XBCC_SAP_SYNC_SAMPLE
   (INDICATOR, BRAMS_ID, OBJECT, NAME, "START", END)
 Values
   ('I', 1234512345, 'ASSET_OWNER', 'BCC', 0, 
    250);
Insert into XBCC_SAP_SYNC_SAMPLE
   (INDICATOR, BRAMS_ID, OBJECT, NAME, "START", END)
 Values
   ('I', 1234512345, 'ASSET_OWNER', 'MAINROADS', 250, 
    300);
Insert into XBCC_SAP_SYNC_SAMPLE
   (INDICATOR, BRAMS_ID, OBJECT, NAME, "START", END)
 Values
   ('C', 1234512345, 'ROAD', 'ANN STREET', 0, 
    300);
Insert into XBCC_SAP_SYNC_SAMPLE
   (INDICATOR, BRAMS_ID, OBJECT, NAME, "START", END)
 Values
   ('C', 1234512345, 'SUBURB_NAME', 'CBD', 0, 
    230);
Insert into XBCC_SAP_SYNC_SAMPLE
   (INDICATOR, BRAMS_ID, OBJECT, NAME, "START", END)
 Values
   ('C', 1234512345, 'SUBURB_NAME', 'NEW FARM', 230, 
    250);
Insert into XBCC_SAP_SYNC_SAMPLE
   (INDICATOR, BRAMS_ID, OBJECT, NAME, "START", END)
 Values
   ('C', 1234512345, 'ASSET_OWNER', 'BCC', 0, 
    250);
Insert into XBCC_SAP_SYNC_SAMPLE
   (INDICATOR, BRAMS_ID, OBJECT, NAME, "START", END)
 Values
   ('C', 1234512345, 'ASSET_OWNER', 'MAINROADS', 250, 
    300);
Insert into XBCC_SAP_SYNC_SAMPLE
   (INDICATOR, BRAMS_ID, OBJECT, NAME, "START", END)
 Values
   ('C', 1234512345, 'SUBURB_NAME', 'ALBION', 250, 
    300);
Insert into XBCC_SAP_SYNC_SAMPLE
   (INDICATOR, BRAMS_ID, OBJECT, NAME)
 Values
   ('D', 1234512345, 'ROAD', 'ANN STREET');
COMMIT;
