SET DEFINE OFF;
Insert into HIG_MODULES
   (HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION)
 Values
   ('XWILTS001', 'Contract name and Financial year', 'XWILTS001', 'WEB', 
    'Y', 'N', 'IM');
Insert into HIG_MODULES
   (HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION)
 Values
   ('XWILTS001A', 'Work Order Listing: &P6_PARAM3', 'XWILTS001A', 'WEB', 
    'Y', 'N', 'IM');
Insert into HIG_MODULES
   (HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION)
 Values
   ('XWILTS001B', '&P6_PARAM2. Expenditure by Month', 'XWILTS001B', 'WEB', 
    'Y', 'N', 'IM');
Insert into HIG_MODULES
   (HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION)
 Values
   ('XWILTS001B2', 'WO &P6_PARAM1. Total Expenditure', 'XWILTS001B2', 'WEB', 
    'Y', 'N', 'IM');
Insert into HIG_MODULES
   (HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION)
 Values
   ('XWILTS002', 'Contractor name and Financial year', 'XWILTS002', 'WEB', 
    'Y', 'N', 'IM');
Insert into HIG_MODULES
   (HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION)
 Values
   ('XWILTS002A', 'Work Order Listing: &P6_PARAM3.', 'XWILTS002A', 'WEB', 
    'Y', 'N', 'IM');
Insert into HIG_MODULES
   (HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION)
 Values
   ('XWILTS002B', 'Contractor &P6_PARAM1. Expenditure by Month', 'XWILTS002B', 'WEB', 
    'Y', 'N', 'IM');
Insert into HIG_MODULES
   (HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION)
 Values
   ('XWILTS002B2', 'Contractor &P6_PARAM1. Staff Grade Breakdown', 'XWILTS002B2', 'WEB', 
    'Y', 'N', 'IM');
Insert into HIG_MODULES
   (HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION)
 Values
   ('XWILTS002B3', 'Scheme Type &P6_PARAM4. Expenditure by Month', 'XWILTS002B3', 'WEB', 
    'Y', 'N', 'IM');
Insert into HIG_MODULES
   (HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION)
 Values
   ('XWILTS002B4', 'Scheme Type &P6_PARAM3. &P6_PARAM4. Staff Grade Breakdown', 'XWILTS002B4', 'WEB', 
    'Y', 'N', 'IM');
Insert into HIG_MODULES
   (HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION)
 Values
   ('XWILTS002B5', 'MJR Project Monitoring for Work Order: &P6_PARAM1.', 'XWILTS002B5', 'WEB', 
    'Y', 'N', 'IM');
Insert into HIG_MODULES
   (HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION)
 Values
   ('XWILTS002B6', 'Cumulative Actual', 'XWILTS002B6', 'WEB', 
    'Y', 'N', 'IM');
Insert into HIG_MODULES
   (HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION)
 Values
   ('XWILTSDISCO', 'Discoverer Reports', 'XWILTSDISCO', 'WEB', 
    'Y', 'N', 'IM');
COMMIT;
