Insert into HIG_MODULE_ROLES
   (HMR_MODULE, HMR_ROLE, HMR_MODE)
 Values
   ('XWILTS001', 'IM_USER', 'NORMAL');
Insert into HIG_MODULE_ROLES
   (HMR_MODULE, HMR_ROLE, HMR_MODE)
 Values
   ('XWILTS001', 'HIG_USER', 'NORMAL');
Insert into HIG_MODULE_ROLES
   (HMR_MODULE, HMR_ROLE, HMR_MODE)
 Values
   ('XWILTS001A', 'HIG_USER', 'NORMAL');
Insert into HIG_MODULE_ROLES
   (HMR_MODULE, HMR_ROLE, HMR_MODE)
 Values
   ('XWILTS001B', 'HIG_USER', 'NORMAL');
Insert into HIG_MODULE_ROLES
   (HMR_MODULE, HMR_ROLE, HMR_MODE)
 Values
   ('XWILTS001B2', 'HIG_USER', 'NORMAL');
Insert into HIG_MODULE_ROLES
   (HMR_MODULE, HMR_ROLE, HMR_MODE)
 Values
   ('XWILTS002', 'HIG_USER', 'NORMAL');
Insert into HIG_MODULE_ROLES
   (HMR_MODULE, HMR_ROLE, HMR_MODE)
 Values
   ('XWILTS002A', 'HIG_USER', 'NORMAL');
Insert into HIG_MODULE_ROLES
   (HMR_MODULE, HMR_ROLE, HMR_MODE)
 Values
   ('XWILTS002B', 'HIG_USER', 'NORMAL');
Insert into HIG_MODULE_ROLES
   (HMR_MODULE, HMR_ROLE, HMR_MODE)
 Values
   ('XWILTS002B2', 'HIG_USER', 'NORMAL');
Insert into HIG_MODULE_ROLES
   (HMR_MODULE, HMR_ROLE, HMR_MODE)
 Values
   ('XWILTS002B3', 'HIG_USER', 'NORMAL');
Insert into HIG_MODULE_ROLES
   (HMR_MODULE, HMR_ROLE, HMR_MODE)
 Values
   ('XWILTS002B4', 'HIG_USER', 'NORMAL');
Insert into HIG_MODULE_ROLES
   (HMR_MODULE, HMR_ROLE, HMR_MODE)
 Values
   ('XWILTS002B5', 'HIG_USER', 'NORMAL');
Insert into HIG_MODULE_ROLES
   (HMR_MODULE, HMR_ROLE, HMR_MODE)
 Values
   ('XWILTS002B6', 'HIG_USER', 'NORMAL');
Insert into HIG_MODULE_ROLES
   (HMR_MODULE, HMR_ROLE, HMR_MODE)
 Values
   ('XWILTSDISCO', 'HIG_USER', 'NORMAL');
COMMIT;
