SET DEFINE OFF;
Insert into IM_POD_CHART
   (IP_ID, CHART_TYPE, CHART_ANIMATION, MARKER_TYPE, DISPLAY_ATTR, MARGINS, CUSTOM_COLORS, BGTYPE, X_AXIS_GROUP_SEP, Y_AXIS_GROUP_SEP, NAMES_FONT, NAMES_ROTATION, VALUES_FONT, VALUES_ROTATION, HINTS_FONT, LEGEND_FONT, CHART_TITLE_FONT, X_AXIS_TITLE_FONT, Y_AXIS_TITLE_FONT, SHOW_LEGEND, LEGEND_LAYOUT, CMODE, ENABLE_3D)
 Values
   (242, 'CategorizedVertical', 
    'Appear', 'None', 'Y::Y::Y:::::::V:T:N:N:', ':::', 
    'Y:Y:Y', 'T', 
    'Y', 'Y', 'Arial:10:', 0, 'Arial:10:#000000', 0, 'Arial:10:', 'Arial:10:#000000', 'Arial:10:', 'Arial:10:#000000', 'Arial:10:#000000', 'N', 'V', 'Normal', 'False');
Insert into IM_POD_CHART
   (IP_ID, CHART_TYPE, CHART_WIDTH, CHART_HEIGHT, CHART_ANIMATION, MARKER_TYPE, DISPLAY_ATTR, MARGINS, CUSTOM_COLORS, BGTYPE, X_AXIS_TITLE, X_AXIS_GROUP_SEP, Y_AXIS_GROUP_SEP, NAMES_FONT, NAMES_ROTATION, VALUES_FONT, VALUES_ROTATION, HINTS_FONT, LEGEND_FONT, CHART_TITLE_FONT, X_AXIS_TITLE_FONT, Y_AXIS_TITLE_FONT, SHOW_LEGEND, LEGEND_LAYOUT, CMODE, ENABLE_3D)
 Values
   (249, 'CategorizedVertical', '95%', '600', 
    'Appear', 'None', 'Y::Y::Y:Y::::::V:T:N:B:', ':::', 
    'Y:Y:Y:Y', 'T', 
    'Month', 
    'Y', 
    'Y', 'Arial:10:', 0, 'Arial:10:#000000', 0, 'Arial:10:', 'Arial:10:#000000', 'Arial:10:', 'Arial:10:#000000', 'Arial:10:#000000', 'N', 'V', 'Normal', 'True');
Insert into IM_POD_CHART
   (IP_ID, CHART_TYPE, CHART_WIDTH, CHART_HEIGHT, CHART_ANIMATION, MARKER_TYPE, DISPLAY_ATTR, MARGINS, CUSTOM_COLORS, BGTYPE, X_AXIS_GROUP_SEP, Y_AXIS_GROUP_SEP, NAMES_FONT, NAMES_ROTATION, VALUES_FONT, VALUES_ROTATION, HINTS_FONT, LEGEND_FONT, CHART_TITLE_FONT, X_AXIS_TITLE_FONT, Y_AXIS_TITLE_FONT, SHOW_LEGEND, LEGEND_LAYOUT, CMODE, ENABLE_3D)
 Values
   (253, 'Pie', '95%', '600', 
    'SideFromRightTop', 'None', 'Y:Y:Y::Y:Y::::::V:T:N:B:', ':::', 
    'Y:Y:Y:Y', 'T', 
    'Y', 'Y', 'Arial:10:', 90, 'Arial:10:#000000', 90, 'Arial:10:', 'Arial:10:#3366cc', 'Arial:10:', 'Arial:10:#000066', 'Arial:10:#000000', 'R', 'V', 'Normal', 'False');
Insert into IM_POD_CHART
   (IP_ID, CHART_TYPE, CHART_WIDTH, CHART_HEIGHT, CHART_ANIMATION, MARKER_TYPE, DISPLAY_ATTR, MARGINS, CUSTOM_COLORS, BGTYPE, X_AXIS_GROUP_SEP, Y_AXIS_GROUP_SEP, NAMES_FONT, NAMES_ROTATION, VALUES_FONT, VALUES_ROTATION, HINTS_FONT, LEGEND_FONT, CHART_TITLE_FONT, X_AXIS_TITLE_FONT, Y_AXIS_TITLE_FONT, SHOW_LEGEND, LEGEND_LAYOUT, CMODE, ENABLE_3D)
 Values
   (256, 'CategorizedVertical', '95%', '300', 
    'Appear', 'None', 'Y::Y::Y:::::::V:T:N:X:', ':::', 
    'Y:Y:Y:Y', 'T', 
    'Y', 'Y', 'Arial:10:', 0, 'Arial:10:#000000', 0, 'Arial:10:', 'Arial:10:#000000', 'Arial:10:', 'Arial:10:#000000', 'Arial:10:#000000', 'N', 'V', 'Normal', 'True');
Insert into IM_POD_CHART
   (IP_ID, CHART_TYPE, CHART_WIDTH, CHART_HEIGHT, CHART_ANIMATION, MARKER_TYPE, DISPLAY_ATTR, MARGINS, CUSTOM_COLORS, BGTYPE, X_AXIS_GROUP_SEP, Y_AXIS_GROUP_SEP, NAMES_FONT, NAMES_ROTATION, VALUES_FONT, VALUES_ROTATION, HINTS_FONT, LEGEND_FONT, CHART_TITLE_FONT, X_AXIS_TITLE_FONT, Y_AXIS_TITLE_FONT, SHOW_LEGEND, LEGEND_LAYOUT, CMODE, ENABLE_3D)
 Values
   (257, 'Pie', '95%', '300', 
    'Appear', 'None', 'Y:Y:Y::Y:::::::V:T:N:N:', ':::', 
    'Y:Y:Y:Y', 'T', 
    'Y', 'Y', 'Arial:10:', 0, 'Arial:10:#000000', 0, 'Arial:10:', 'Arial:10:#000000', 'Arial:10:', 'Arial:10:#000000', 'Arial:10:#000000', 'R', 'V', 'Normal', 'True');
Insert into IM_POD_CHART
   (IP_ID, CHART_TYPE, CHART_WIDTH, CHART_HEIGHT, CHART_ANIMATION, MARKER_TYPE, DISPLAY_ATTR, MARGINS, CUSTOM_COLORS, BGTYPE, X_AXIS_TITLE, X_AXIS_GROUP_SEP, Y_AXIS_GROUP_SEP, NAMES_FONT, NAMES_ROTATION, VALUES_FONT, VALUES_ROTATION, HINTS_FONT, LEGEND_FONT, CHART_TITLE_FONT, X_AXIS_TITLE_FONT, Y_AXIS_TITLE_FONT, SHOW_LEGEND, LEGEND_LAYOUT, CMODE, ENABLE_3D)
 Values
   (258, 'CategorizedVertical', '95%', '300', 
    'SideFromTop', 'None', 'Y::Y::Y:Y::::::V:T:N:X:', ':::', 
    'Y:Y:Y:Y', 'T', 
    'Month', 
    'Y', 
    'Y', 'Arial:10:', 0, 'Arial:10:#000000', 0, 'Arial:10:', 'Arial:10:#000000', 'Arial:10:', 'Arial:10:#000000', 'Arial:10:#000000', 'N', 'V', 'Normal', 'True');
Insert into IM_POD_CHART
   (IP_ID, CHART_TYPE, CHART_WIDTH, CHART_HEIGHT, CHART_ANIMATION, MARKER_TYPE, DISPLAY_ATTR, MARGINS, CUSTOM_COLORS, BGTYPE, X_AXIS_GROUP_SEP, Y_AXIS_GROUP_SEP, NAMES_FONT, NAMES_ROTATION, VALUES_FONT, VALUES_ROTATION, HINTS_FONT, LEGEND_FONT, CHART_TITLE_FONT, X_AXIS_TITLE_FONT, Y_AXIS_TITLE_FONT, SHOW_LEGEND, LEGEND_LAYOUT, CMODE, ENABLE_3D)
 Values
   (259, 'Pie', '95%', '300', 
    'Appear', 'None', 'Y:Y:Y::Y:::::::V:T:N:X:', ':::', 
    'Y:Y:Y:Y', 'T', 
    'Y', 'Y', 'Arial:10:', 0, 'Arial:10:#000000', 0, 'Arial:10:', 'Arial:10:#000000', 'Arial:10:', 'Arial:10:#000000', 'Arial:10:#000000', 'R', 'V', 'Normal', 'True');
Insert into IM_POD_CHART
   (IP_ID, CHART_TYPE, CHART_WIDTH, CHART_HEIGHT, CHART_ANIMATION, MARKER_TYPE, DISPLAY_ATTR, MARGINS, CUSTOM_COLORS, BGTYPE, X_AXIS_TITLE, X_AXIS_GROUP_SEP, Y_AXIS_GROUP_SEP, NAMES_FONT, NAMES_ROTATION, VALUES_FONT, VALUES_ROTATION, HINTS_FONT, LEGEND_FONT, CHART_TITLE_FONT, X_AXIS_TITLE_FONT, Y_AXIS_TITLE_FONT, SHOW_LEGEND, LEGEND_LAYOUT, CMODE, ENABLE_3D)
 Values
   (262, 'CategorizedVertical', '95%', '300', 
    'Appear', 'None', 'Y:Y:Y::Y:::::::V:T:N:X:', ':::', 
    'Y:Y:Y:Y', 'T', 
    'Month', 
    'Y', 
    'Y', 'Arial:10:', 0, 'Arial:10:#000000', 0, 'Arial:10:', 'Arial:10:#000000', 'Arial:10:', 'Arial:10:#000000', 'Arial:10:#000000', 'N', 'V', 'Normal', 'False');
COMMIT;
