--OHMS Sections Table

--Droping tables and views

declare
    i integer;
    sname varchar(50);
	
Cursor cur_views is  
  select VIEW_NAME from USER_VIEWS 
  where VIEW_NAME like 'V_OHMS_7%'
  OR VIEW_NAME like 'V_OHMS_FINAL_7%';
	

BEGIN

sname := 'OHMS_SUBMIT_SECTIONS';


    select COUNT(*) into I from USER_TABLES where TABLE_NAME = SNAME;
    if i <> 0 then
        execute immediate 'drop table ' || sname ;
    end if;
	
	for  C_ROW IN CUR_VIEWS LOOP    	
		execute immediate 'drop view ' || C_ROW.VIEW_NAME;  
	end loop;
	
	
END;
/

DROP PACKAGE xna_ohms;


------HPMS Prereqs

DROP TABLE OHMS_7_NETWORK_MV;
DROP TABLE OHMS_7_NETWORK_MV2;
DROP TABLE v_nm_urbn502_outer_mv_nt;
DROP TABLE v_nm_urbn502_outer_mv_nt;
DROP TABLE v_nm_nbi504_outer_mv_nw;
DROP TABLE v_nm_tunl504_outer_mv_nw;
DROP TABLE OHMS_TMP_7_507_RDGM;
DROP TABLE OHMS_TMP_RTE_7_507_RDGM;
DROP TABLE OHMS_tmp_seg_7_507_rdgm;
DROP TABLE OHMS_TMP_DETAIL_7_507_RDGM;
DROP TABLE v_nm_rdgm507_count_mv_nw;
DROP TABLE OHMS_TMP_7_508_RDGM;
DROP TABLE OHMS_TMP_RTE_ITEM_HWY;
DROP TABLE OHMS_TMP_RTE_7_508_RDGM;
DROP TABLE OHMS_TMP_RTE_7_507_RDGM;
DROP TABLE OHMS_TMP_RTE_ITEM_HWY;
DROP TABLE OHMS_TMP_7_507_RDGM;
DROP TABLE OHMS_TMP_SEG_7_507_RDGM;
DROP TABLE OHMS_TMP_DETAIL_7_507_RDGM;
DROP TABLE OHMS_tmp_seg_7_508_rdgm;
DROP TABLE OHMS_TMP_DETAIL_7_508_RDGM;
DROP TABLE v_nm_rdgm508_min_mv_nw;
DROP TABLE OHMS_TMP_RTE_7_508_RDGM;
DROP TABLE OHMS_TMP_RTE_ITEM_HWY;
DROP TABLE OHMS_TMP_7_508_RDGM;
DROP TABLE OHMS_TMP_SEG_7_508_RDGM;
DROP TABLE OHMS_TMP_DETAIL_7_508_RDGM;
DROP TABLE OHMS_TMP_7_509_RDGM;
DROP TABLE OHMS_TMP_RTE_ITEM_HWY;
DROP TABLE OHMS_TMP_RTE_7_509_RDGM;
DROP TABLE OHMS_tmp_seg_7_509_rdgm;
DROP TABLE OHMS_TMP_DETAIL_7_509_RDGM;
DROP TABLE v_nm_rdgm509_count_mv_nw;
DROP TABLE OHMS_TMP_RTE_7_509_RDGM;
DROP TABLE OHMS_TMP_RTE_ITEM_HWY;
DROP TABLE OHMS_TMP_7_509_RDGM;
DROP TABLE OHMS_TMP_SEG_7_509_RDGM;
DROP TABLE OHMS_TMP_DETAIL_7_509_RDGM;
DROP TABLE v_nm_urbn510_outer_mv_nt;
DROP TABLE v_nm_spzn514_outer_mv_nw;
DROP TABLE v_nm_urbn514_outer_mv_nt;
DROP TABLE OHMS_TMP_7_538_RDGM;
DROP TABLE OHMS_TMP_RTE_ITEM_HWY;
DROP TABLE OHMS_TMP_RTE_7_538_RDGM;
DROP TABLE OHMS_tmp_seg_7_538_rdgm;
DROP TABLE OHMS_TMP_DETAIL_7_538_RDGM;
DROP TABLE v_nm_rdgm538_sum_mv_nw;
DROP TABLE OHMS_TMP_RTE_7_538_RDGM;
DROP TABLE OHMS_TMP_RTE_ITEM_HWY;
DROP TABLE OHMS_TMP_7_538_RDGM;
DROP TABLE OHMS_TMP_SEG_7_538_RDGM;
DROP TABLE OHMS_TMP_DETAIL_7_538_RDGM;
DROP TABLE OHMS_TMP_7_539_RDGM;
DROP TABLE OHMS_TMP_RTE_ITEM_HWY;
DROP TABLE OHMS_TMP_RTE_7_539_RDGM;
DROP TABLE OHMS_tmp_seg_7_539_rdgm;
DROP TABLE OHMS_TMP_DETAIL_7_539_RDGM;
DROP TABLE v_nm_rdgm539_sum_mv_nw;
DROP TABLE OHMS_TMP_RTE_7_539_RDGM;
DROP TABLE OHMS_TMP_RTE_ITEM_HWY;
DROP TABLE OHMS_TMP_7_539_RDGM;
DROP TABLE OHMS_TMP_SEG_7_539_RDGM;
DROP TABLE OHMS_TMP_DETAIL_7_539_RDGM;
DROP TABLE OHMS_TMP_7_540_PRKR;
DROP TABLE OHMS_TMP_RTE_ITEM_HWY;
DROP TABLE OHMS_TMP_RTE_7_540_PRKR;
DROP TABLE OHMS_tmp_seg_7_540_prkr;
DROP TABLE OHMS_TMP_DETAIL_7_540_PRKR;
DROP TABLE v_nm_prkr540_count_mv_nw;
DROP TABLE OHMS_TMP_RTE_7_540_PRKR;
DROP TABLE OHMS_TMP_RTE_ITEM_HWY;
DROP TABLE OHMS_TMP_7_540_PRKR;
DROP TABLE OHMS_TMP_SEG_7_540_PRKR;
DROP TABLE OHMS_TMP_DETAIL_7_540_PRKR;
DROP TABLE v_nm_secw566_outer_mv_nt;


DROP TABLE OHMS_TMP_7_610_RDGM;
DROP TABLE OHMS_TMP_RTE_ITEM_HWY;
DROP TABLE OHMS_TMP_RTE_7_610_RDGM;
DROP TABLE OHMS_tmp_seg_7_610_rdgm;
DROP TABLE OHMS_TMP_DETAIL_7_610_RDGM;
DROP TABLE OHMS_TMP_RTE_7_610_RDGM;
DROP TABLE OHMS_TMP_RTE_ITEM_HWY;
DROP TABLE OHMS_TMP_7_610_RDGM;
DROP TABLE OHMS_TMP_SEG_7_610_RDGM;
DROP TABLE OHMS_TMP_DETAIL_7_610_RDGM;
DROP TABLE OHMS_TMP_7_611_RDGM;
DROP TABLE OHMS_TMP_RTE_ITEM_HWY;
DROP TABLE OHMS_TMP_RTE_7_611_RDGM;
DROP TABLE OHMS_tmp_seg_7_611_rdgm;
DROP TABLE OHMS_TMP_DETAIL_7_611_RDGM;
DROP TABLE v_nm_rdgm611_count_mv_nw;
DROP TABLE OHMS_TMP_RTE_7_611_RDGM;
DROP TABLE OHMS_TMP_RTE_ITEM_HWY;
DROP TABLE OHMS_TMP_7_611_RDGM;
DROP TABLE OHMS_TMP_SEG_7_611_RDGM;
DROP TABLE OHMS_TMP_DETAIL_7_611_RDGM;



