-------------------------------------------------------------------------
--   PVCS Identifiers :-
--
--       PVCS id          : $Header:   //vm_latest/archives/customer/rta/XRTA_DROP_LOG_708593.sql-arc   1.0   Mar 11 2009 11:58:40   cstrettle  $
--       Module Name      : $Workfile:   XRTA_DROP_LOG_708593.sql  $
--       Date into PVCS   : $Date:   Mar 11 2009 11:58:40  $
--       Date fetched Out : $Modtime:   Mar 11 2009 11:40:16  $
--       Version          : $Revision:   1.0  $
--       Based on SCCS version : NA
-------------------------------------------------------------------------
PROMPT
PROMPT START DROPPING TABLES

PROMPT START DROPPING XRTA_NM_UNIQUES_POP_ELEMENTS
BEGIN
EXECUTE IMMEDIATE 'DROP TRIGGER XRTA_NM_UNIQUES_POP_ELEMENTS';
EXCEPTION
WHEN OTHERS THEN
NULL;
END;
/
PROMPT START DROPPING XRTA_NM_UNIQUES_POP_INV_ITEMS
BEGIN
EXECUTE IMMEDIATE 'DROP TRIGGER XRTA_NM_UNIQUES_POP_INV_ITEMS';
EXCEPTION
WHEN OTHERS THEN
NULL;
END;
/
PROMPT START DROPPING XRTA_NM_UNIQUES_POP_ELEMENTS
BEGIN
EXECUTE IMMEDIATE 'DROP PACKAGE XRTA_NM_UNIQUE';
EXCEPTION
WHEN OTHERS THEN
NULL;
END;
/
PROMPT START DROPPING XRTA_NM_UNIQUES_POP_ELEMENTS
--
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE XRTA_ERRORS';
EXCEPTION
WHEN OTHERS THEN
NULL;
END;
/
PROMPT START DROPPING XRTA_NM_UNIQUES_POP_ELEMENTS
--
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE XRTA_NM_UNIQUES';
EXCEPTION
WHEN OTHERS THEN
NULL;
END;
/
PROMPT END DROPPING TABLES
