-
-----------------------------------------------------------------------------
--
--   PVCS Identifiers :-
--
--       pvcsid                 : $Header:   //vm_latest/archives/customer/HA/insp_scheduling/admin/sql/metadata.sql-arc   1.2   Jun 07 2012 12:36:56   Ian.Turnbull  $
--       Module Name      : $Workfile:   metadata.sql  $
--       Date into PVCS   : $Date:   Jun 07 2012 12:36:56  $
--       Date fetched Out : $Modtime:   Jun 06 2012 15:06:58  $
--       PVCS Version     : $Revision:   1.2  $
--
--
--   Author : P Stanton
--
-----------------------------------------------------------------------------
--	Copyright (c) Bentley ltd, 2012
-----------------------------------------------------------------------------
--

----------------------------------------------------------------------------------------
-- HIG_MODULES
--
-- select * from nm3_metadata.hig_modules
-- order by hmo_module
--
----------------------------------------------------------------------------------------

SET TERM ON
PROMPT hig_modules
SET TERM OFF

INSERT INTO HIG_MODULES
       (HMO_MODULE
       ,HMO_TITLE
       ,HMO_FILENAME
       ,HMO_MODULE_TYPE
       ,HMO_FASTPATH_OPTS
       ,HMO_FASTPATH_INVALID
       ,HMO_USE_GRI
       ,HMO_APPLICATION
       ,HMO_MENU
       )
SELECT 
        'MAI3700'
       ,'Schedule Inspections by Interval'
       ,'MAI3700.sql'
       ,'SQL'
       ,''
       ,'N'
       ,'Y'
       ,'MAI'
       ,'FORM' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM HIG_MODULES
                   WHERE HMO_MODULE = 'MAI3700');
                   
INSERT INTO HIG_MODULES
       (HMO_MODULE
       ,HMO_TITLE
       ,HMO_FILENAME
       ,HMO_MODULE_TYPE
       ,HMO_FASTPATH_OPTS
       ,HMO_FASTPATH_INVALID
       ,HMO_USE_GRI
       ,HMO_APPLICATION
       ,HMO_MENU
       )
SELECT 
        'MAI3710'
       ,'Schedule Inspections by Date'
       ,'MAI3710.sql'
       ,'SQL'
       ,''
       ,'N'
       ,'Y'
       ,'MAI'
       ,'FORM' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM HIG_MODULES
                   WHERE HMO_MODULE = 'MAI3710');  

INSERT INTO HIG_MODULES
       (HMO_MODULE
       ,HMO_TITLE
       ,HMO_FILENAME
       ,HMO_MODULE_TYPE
       ,HMO_FASTPATH_OPTS
       ,HMO_FASTPATH_INVALID
       ,HMO_USE_GRI
       ,HMO_APPLICATION
       ,HMO_MENU
       )
SELECT 
        'MAI3720'
       ,'Create Inspection Batches'
       ,'MAI3720.sql'
       ,'SQL'
       ,''
       ,'N'
       ,'Y'
       ,'MAI'
       ,'FORM' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM HIG_MODULES
                   WHERE HMO_MODULE = 'MAI3720');	

INSERT INTO HIG_MODULES
       (HMO_MODULE
       ,HMO_TITLE
       ,HMO_FILENAME
       ,HMO_MODULE_TYPE
       ,HMO_FASTPATH_OPTS
       ,HMO_FASTPATH_INVALID
       ,HMO_USE_GRI
       ,HMO_APPLICATION
       ,HMO_MENU
       )
SELECT 
        'MAI3730'
       ,'Download Inspection Batches'
       ,'MAI3730.sql'
       ,'SQL'
       ,''
       ,'N'
       ,'Y'
       ,'MAI'
       ,'FORM' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM HIG_MODULES
                   WHERE HMO_MODULE = 'MAI3730');					   
----------------------------------------------------------------------------------------
-- GRI_MODULES
--
-- select * from nm3_metadata.gri_modules
-- order by grm_module
--
----------------------------------------------------------------------------------------

SET TERM ON
PROMPT gri_modules
SET TERM OFF


INSERT INTO GRI_MODULES
       (GRM_MODULE
       ,GRM_MODULE_TYPE
       ,GRM_MODULE_PATH
       ,GRM_FILE_TYPE
       ,GRM_TAG_FLAG
       ,GRM_TAG_TABLE
       ,GRM_TAG_COLUMN
       ,GRM_TAG_WHERE
       ,GRM_LINESIZE
       ,GRM_PAGESIZE
       ,GRM_PRE_PROCESS
       )
SELECT 
        'MAI3700'
       ,'SVR'
       ,'$PROD_HOME/bin'
       ,'lis'
       ,'N'
       ,''
       ,''
       ,''
       ,80
       ,66
       ,'' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM GRI_MODULES
                  WHERE GRM_MODULE = 'MAI3700');
                  

INSERT INTO GRI_MODULES
       (GRM_MODULE
       ,GRM_MODULE_TYPE
       ,GRM_MODULE_PATH
       ,GRM_FILE_TYPE
       ,GRM_TAG_FLAG
       ,GRM_TAG_TABLE
       ,GRM_TAG_COLUMN
       ,GRM_TAG_WHERE
       ,GRM_LINESIZE
       ,GRM_PAGESIZE
       ,GRM_PRE_PROCESS
       )
SELECT 
        'MAI3710'
       ,'SVR'
       ,'$PROD_HOME/bin'
       ,'lis'
       ,'N'
       ,''
       ,''
       ,''
       ,80
       ,66
       ,'' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM GRI_MODULES
                 WHERE GRM_MODULE = 'MAI3710');                  
                 
INSERT INTO GRI_MODULES
       (GRM_MODULE
       ,GRM_MODULE_TYPE
       ,GRM_MODULE_PATH
       ,GRM_FILE_TYPE
       ,GRM_TAG_FLAG
       ,GRM_TAG_TABLE
       ,GRM_TAG_COLUMN
       ,GRM_TAG_WHERE
       ,GRM_LINESIZE
       ,GRM_PAGESIZE
       ,GRM_PRE_PROCESS
       )
SELECT 
        'MAI3720'
       ,'SVR'
       ,'$PROD_HOME/bin'
       ,'lis'
       ,'N'
       ,''
       ,''
       ,''
       ,80
       ,66
       ,'' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM GRI_MODULES
                 WHERE GRM_MODULE = 'MAI3720');                  

INSERT INTO GRI_MODULES
       (GRM_MODULE
       ,GRM_MODULE_TYPE
       ,GRM_MODULE_PATH
       ,GRM_FILE_TYPE
       ,GRM_TAG_FLAG
       ,GRM_TAG_TABLE
       ,GRM_TAG_COLUMN
       ,GRM_TAG_WHERE
       ,GRM_LINESIZE
       ,GRM_PAGESIZE
       ,GRM_PRE_PROCESS
       )
SELECT 
        'MAI3730'
       ,'SVR'
       ,'$PROD_HOME/bin'
       ,'lis'
       ,'N'
       ,''
       ,''
       ,''
       ,80
       ,66
       ,'' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM GRI_MODULES
                 WHERE GRM_MODULE = 'MAI3730');				 
----------------------------------------------------------------------------------------
-- GRI_PARAMS
--
-- select * from nm3_metadata.gri_params
-- order by gp_param
--
----------------------------------------------------------------------------------------

SET TERM ON
PROMPT gri_params
SET TERM OFF
INSERT INTO GRI_PARAMS
       (GP_PARAM
       ,GP_PARAM_TYPE
       ,GP_TABLE
       ,GP_COLUMN
       ,GP_DESCR_COLUMN
       ,GP_SHOWN_COLUMN
       ,GP_SHOWN_TYPE
       ,GP_DESCR_TYPE
       ,GP_ORDER
       ,GP_CASE
       ,GP_GAZ_RESTRICTION
       ) SELECT 'YES_NO','CHAR','GRI_PARAM_LOOKUP','GPL_VALUE','GPL_DESCR','GPL_VALUE','CHAR','','','',''FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM GRI_PARAMS
                   WHERE GP_PARAM = 'YES_NO');
                   
INSERT INTO GRI_PARAMS
       (GP_PARAM
       ,GP_PARAM_TYPE
       ,GP_TABLE
       ,GP_COLUMN
       ,GP_DESCR_COLUMN
       ,GP_SHOWN_COLUMN
       ,GP_SHOWN_TYPE
       ,GP_DESCR_TYPE
       ,GP_ORDER
       ,GP_CASE
       ,GP_GAZ_RESTRICTION
       ) SELECT 'INSP_ASSET_TYPE','CHAR','MAI3700_ASSET_LIST','NIT_INV_TYPE','NIT_DESCR','NIT_INV_TYPE','CHAR','CHAR','','',''FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM GRI_PARAMS
                   WHERE GP_PARAM = 'INSP_ASSET_TYPE');
				   
INSERT INTO GRI_PARAMS
       (GP_PARAM
       ,GP_PARAM_TYPE
       ,GP_TABLE
       ,GP_COLUMN
       ,GP_DESCR_COLUMN
       ,GP_SHOWN_COLUMN
       ,GP_SHOWN_TYPE
       ,GP_DESCR_TYPE
       ,GP_ORDER
       ,GP_CASE
       ,GP_GAZ_RESTRICTION
       ) SELECT 'FROM_DATE','DATE','','','','','','','','',''FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM GRI_PARAMS
                   WHERE GP_PARAM = 'FROM_DATE');
				   
INSERT INTO GRI_PARAMS
       (GP_PARAM
       ,GP_PARAM_TYPE
       ,GP_TABLE
       ,GP_COLUMN
       ,GP_DESCR_COLUMN
       ,GP_SHOWN_COLUMN
       ,GP_SHOWN_TYPE
       ,GP_DESCR_TYPE
       ,GP_ORDER
       ,GP_CASE
       ,GP_GAZ_RESTRICTION
       ) SELECT 'HA_INSPECTION_TYPE','CHAR','NM_INV_ATTRI_LOOKUP','IAL_VALUE','IAL_MEANING','IAL_VALUE','CHAR','CHAR','','UPPER',''FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM GRI_PARAMS
                   WHERE GP_PARAM = 'HA_INSPECTION_TYPE');
				   
INSERT INTO GRI_PARAMS
       (GP_PARAM
       ,GP_PARAM_TYPE
       ,GP_TABLE
       ,GP_COLUMN
       ,GP_DESCR_COLUMN
       ,GP_SHOWN_COLUMN
       ,GP_SHOWN_TYPE
       ,GP_DESCR_TYPE
       ,GP_ORDER
       ,GP_CASE
       ,GP_GAZ_RESTRICTION
       ) SELECT 'REGION_OF_INTEREST','NUMBER','NM_ELEMENTS_ALL','NE_ID','NE_DESCR','NE_UNIQUE','CHAR','CHAR','','',''FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM GRI_PARAMS
                   WHERE GP_PARAM = 'REGION_OF_INTEREST');
				   
INSERT INTO GRI_PARAMS
       (GP_PARAM
       ,GP_PARAM_TYPE
       ,GP_TABLE
       ,GP_COLUMN
       ,GP_DESCR_COLUMN
       ,GP_SHOWN_COLUMN
       ,GP_SHOWN_TYPE
       ,GP_DESCR_TYPE
       ,GP_ORDER
       ,GP_CASE
       ,GP_GAZ_RESTRICTION
       ) SELECT 'TO_DATE','DATE','','','','','','','','',''FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM GRI_PARAMS
                   WHERE GP_PARAM = 'TO_DATE'); 

INSERT INTO GRI_PARAMS
       (GP_PARAM
       ,GP_PARAM_TYPE
       ,GP_TABLE
       ,GP_COLUMN
       ,GP_DESCR_COLUMN
       ,GP_SHOWN_COLUMN
       ,GP_SHOWN_TYPE
       ,GP_DESCR_TYPE
       ,GP_ORDER
       ,GP_CASE
       ,GP_GAZ_RESTRICTION
       ) SELECT 'BATCH_NUM','NUMBER','','','','','','','','',''FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM GRI_PARAMS
                   WHERE GP_PARAM = 'BATCH_NUM');				   
----------------------------------------------------------------------------------------

Insert into GRI_PARAM_LOOKUP
   (GPL_PARAM, GPL_VALUE, GPL_DESCR)
select 'YES_NO', 'Y', 'Yes' from dual
where not exists (select 1 from gri_param_lookup
                  where gpl_param = 'YES_NO'
                  and gpl_value = 'Y');


Insert into GRI_PARAM_LOOKUP
   (GPL_PARAM, GPL_VALUE, GPL_DESCR)
select 'YES_NO', 'N', 'No' from dual
where not exists (select 1 from gri_param_lookup
                  where gpl_param = 'YES_NO'
                  and gpl_value = 'N');

----------------------------------------------------------------------------------------
-- GRI_MODULE_PARAMS
--
-- select * from nm3_metadata.gri_module_params
-- order by gmp_module
--         ,gmp_param
--
----------------------------------------------------------------------------------------

SET TERM ON
PROMPT gri_module_params
SET TERM OFF                                   
                   
Insert into GRI_MODULE_PARAMS
   (GMP_MODULE, GMP_PARAM, GMP_SEQ, GMP_PARAM_DESCR, GMP_MANDATORY, 
    GMP_NO_ALLOWED, GMP_TAG_RESTRICTION, GMP_VISIBLE, GMP_GAZETTEER, GMP_LOV, 
    GMP_WILDCARD, GMP_HINT_TEXT, GMP_ALLOW_PARTIAL)
 SELECT 'MAI3700', 'INSP_ASSET_TYPE', 1, 'Asset Type', 'Y', 
    10, 'N', 'Y', 'N', 'Y', 
    'N', 'Select Asset Types', 'N' FROM dual
    WHERE NOT EXISTS (SELECT 1 FROM GRI_MODULE_PARAMS
                   WHERE GMP_MODULE = 'MAI3700' AND  GMP_PARAM = 'INSP_ASSET_TYPE');
    
Insert into GRI_MODULE_PARAMS
   (GMP_MODULE, GMP_PARAM, GMP_SEQ, GMP_PARAM_DESCR, GMP_MANDATORY, 
    GMP_NO_ALLOWED, GMP_WHERE, GMP_TAG_RESTRICTION, GMP_VISIBLE, GMP_GAZETTEER, 
    GMP_LOV, GMP_WILDCARD, GMP_HINT_TEXT, GMP_ALLOW_PARTIAL)
    SELECT 'MAI3700', 'HA_INSPECTION_TYPE', 2, 'Inspection Type', 'Y', 
    1, 'IAL_DOMAIN=''INSP_TYPE''', 'N', 'Y', 'N', 
    'Y', 'N', 'Enter the Inspection Type (Mandatory)', 'N' FROM dual
    WHERE NOT EXISTS (SELECT 1 FROM GRI_MODULE_PARAMS
                   WHERE GMP_MODULE = 'MAI3700' AND  GMP_PARAM = 'HA_INSPECTION_TYPE');
    
Insert into GRI_MODULE_PARAMS
   (GMP_MODULE, GMP_PARAM, GMP_SEQ, GMP_PARAM_DESCR, GMP_MANDATORY, 
    GMP_NO_ALLOWED, GMP_WHERE, GMP_TAG_RESTRICTION, GMP_VISIBLE, GMP_GAZETTEER, 
    GMP_LOV, GMP_WILDCARD, GMP_HINT_TEXT, GMP_ALLOW_PARTIAL)
 SELECT 'MAI3700', 'REGION_OF_INTEREST', 3, 'Region of Interest', 'Y', 
    1, 'NE_TYPE IN (''G'',''P'',''S'')', 'N', 'Y', 'Y', 
    'N', 'N', 'Select Region of Interest (Gaz)', 'N' FROM dual
    WHERE NOT EXISTS (SELECT 1 FROM GRI_MODULE_PARAMS
                   WHERE GMP_MODULE = 'MAI3700' AND  GMP_PARAM = 'REGION_OF_INTEREST');
                   
Insert into GRI_MODULE_PARAMS
   (GMP_MODULE, GMP_PARAM, GMP_SEQ, GMP_PARAM_DESCR, GMP_MANDATORY, 
    GMP_NO_ALLOWED, GMP_WHERE, GMP_TAG_RESTRICTION, GMP_VISIBLE, GMP_GAZETTEER, 
    GMP_LOV, GMP_WILDCARD, GMP_HINT_TEXT, GMP_ALLOW_PARTIAL)
 SELECT 'MAI3700', 'FROM_DATE', 4, 'From Date', 'Y', 
    1, '((:FROM_DATE <= :TO_DATE AND :FROM_DATE <=SYSDATE) OR (:TO_DATE IS NULL AND :FROM_DATE <=SYSDATE))', 'N', 'Y', 'N', 
    'N', 'N', 'Enter From Date', 'N' FROM dual
    WHERE NOT EXISTS (SELECT 1 FROM GRI_MODULE_PARAMS
                   WHERE GMP_MODULE = 'MAI3700' AND  GMP_PARAM = 'FROM_DATE');
                   
Insert into GRI_MODULE_PARAMS
   (GMP_MODULE, GMP_PARAM, GMP_SEQ, GMP_PARAM_DESCR, GMP_MANDATORY, 
    GMP_NO_ALLOWED, GMP_WHERE, GMP_TAG_RESTRICTION, GMP_VISIBLE, GMP_GAZETTEER, 
    GMP_LOV, GMP_WILDCARD, GMP_HINT_TEXT, GMP_ALLOW_PARTIAL)
 SELECT 'MAI3700', 'TO_DATE', 5, 'To Date', 'Y', 
    1, '((:FROM_DATE <= :TO_DATE AND :TO_DATE <=SYSDATE) OR (:FROM_DATE IS NULL AND :TO_DATE <=SYSDATE)', 'N', 'Y', 'N', 
    'N', 'N', 'Enter To Date', 'N' FROM dual
    WHERE NOT EXISTS (SELECT 1 FROM GRI_MODULE_PARAMS
                   WHERE GMP_MODULE = 'MAI3700' AND  GMP_PARAM = 'TO_DATE');
                   
Insert into GRI_MODULE_PARAMS
   (GMP_MODULE, GMP_PARAM, GMP_SEQ, GMP_PARAM_DESCR, GMP_MANDATORY, 
    GMP_NO_ALLOWED, GMP_WHERE, GMP_TAG_RESTRICTION, GMP_VISIBLE, GMP_GAZETTEER, 
    GMP_LOV, GMP_WILDCARD, GMP_HINT_TEXT, GMP_ALLOW_PARTIAL)
 select 'MAI3710', 'HA_INSPECTION_TYPE', 1, 'Inspection Type', 'Y', 
    1, 'IAL_DOMAIN=''INSP_TYPE''', 'N', 'Y', 'N', 
    'Y', 'N', 'Enter the Inspection Type', 'N' FROM dual
    WHERE NOT EXISTS (SELECT 1 FROM GRI_MODULE_PARAMS
                   WHERE GMP_MODULE = 'MAI3710' AND  GMP_PARAM = 'HA_INSPECTION_TYPE');
                   
Insert into GRI_MODULE_PARAMS
   (GMP_MODULE, GMP_PARAM, GMP_SEQ, GMP_PARAM_DESCR, GMP_MANDATORY, 
    GMP_NO_ALLOWED, GMP_TAG_RESTRICTION, GMP_VISIBLE, GMP_GAZETTEER, GMP_LOV, 
    GMP_WILDCARD, GMP_HINT_TEXT, GMP_ALLOW_PARTIAL)
 select 'MAI3710', 'INSP_ASSET_TYPE', 2, 'Asset Type', 'Y', 
    10, 'N', 'Y', 'N', 'Y', 
    'N', 'Select Asset Types', 'N' FROM dual
    WHERE NOT EXISTS (SELECT 1 FROM GRI_MODULE_PARAMS
                   WHERE GMP_MODULE = 'MAI3710' AND  GMP_PARAM = 'INSP_ASSET_TYPE');
                   
Insert into GRI_MODULE_PARAMS
   (GMP_MODULE, GMP_PARAM, GMP_SEQ, GMP_PARAM_DESCR, GMP_MANDATORY, 
    GMP_NO_ALLOWED, GMP_WHERE, GMP_TAG_RESTRICTION, GMP_VISIBLE, GMP_GAZETTEER, 
    GMP_LOV, GMP_WILDCARD, GMP_HINT_TEXT, GMP_ALLOW_PARTIAL)
 select 'MAI3710', 'REGION_OF_INTEREST', 3, 'Region of Interest', 'Y', 
    1, 'NE_TYPE IN (''G'',''P'',''S'')', 'N', 'Y', 'Y', 
    'N', 'N', 'Select Region of Interest (Gaz)', 'N' FROM dual
    WHERE NOT EXISTS (SELECT 1 FROM GRI_MODULE_PARAMS
                   WHERE GMP_MODULE = 'MAI3710' AND  GMP_PARAM = 'REGION_OF_INTEREST');
                   
Insert into GRI_MODULE_PARAMS
   (GMP_MODULE, GMP_PARAM, GMP_SEQ, GMP_PARAM_DESCR, GMP_MANDATORY, 
    GMP_NO_ALLOWED, GMP_WHERE, GMP_TAG_RESTRICTION, GMP_VISIBLE, GMP_GAZETTEER, 
    GMP_LOV, GMP_WILDCARD, GMP_HINT_TEXT, GMP_ALLOW_PARTIAL)
select 'MAI3710', 'FROM_DATE', 4, 'Scheduled Date', 'Y', 
    10, '((:FROM_DATE <= :TO_DATE AND :FROM_DATE <=SYSDATE) OR (:TO_DATE IS NULL AND :FROM_DATE <=SYSDATE))', 'N', 'Y', 'N', 
    'N', 'N', 'Enter Scheduled Date', 'N' FROM dual
    WHERE NOT EXISTS (SELECT 1 FROM GRI_MODULE_PARAMS
                   WHERE GMP_MODULE = 'MAI3710' AND  GMP_PARAM = 'FROM_DATE');

Insert into GRI_MODULE_PARAMS
   (GMP_MODULE, GMP_PARAM, GMP_SEQ, GMP_PARAM_DESCR, GMP_MANDATORY, 
    GMP_NO_ALLOWED, GMP_WHERE, GMP_TAG_RESTRICTION, GMP_VISIBLE, GMP_GAZETTEER, 
    GMP_LOV, GMP_WILDCARD, GMP_HINT_TEXT, GMP_ALLOW_PARTIAL)
 select 'MAI3720', 'REGION_OF_INTEREST', 1, 'Region of Interest', 'Y', 
    1, 'NE_TYPE IN (''G'',''P'',''S'')', 'N', 'Y', 'Y', 
    'N', 'N', 'Select region of Interest (Gaz)', 'N' FROM dual
    WHERE NOT EXISTS (SELECT 1 FROM GRI_MODULE_PARAMS
                   WHERE GMP_MODULE = 'MAI3720' AND  GMP_PARAM = 'REGION_OF_INTEREST');
                   
Insert into GRI_MODULE_PARAMS
   (GMP_MODULE, GMP_PARAM, GMP_SEQ, GMP_PARAM_DESCR, GMP_MANDATORY, 
    GMP_NO_ALLOWED, GMP_TAG_RESTRICTION, GMP_VISIBLE, GMP_GAZETTEER, GMP_LOV, 
    GMP_WILDCARD, GMP_HINT_TEXT, GMP_ALLOW_PARTIAL)
 select 'MAI3720', 'INSP_ASSET_TYPE', 2, 'Asset Type', 'Y', 
    10, 'N', 'Y', 'N', 'Y', 
    'N', 'Select Asset Types', 'N' FROM dual
    WHERE NOT EXISTS (SELECT 1 FROM GRI_MODULE_PARAMS
                   WHERE GMP_MODULE = 'MAI3720' AND  GMP_PARAM = 'INSP_ASSET_TYPE');
                   
Insert into GRI_MODULE_PARAMS
   (GMP_MODULE, GMP_PARAM, GMP_SEQ, GMP_PARAM_DESCR, GMP_MANDATORY, 
    GMP_NO_ALLOWED, GMP_WHERE, GMP_TAG_RESTRICTION, GMP_VISIBLE, GMP_GAZETTEER, 
    GMP_LOV, GMP_WILDCARD, GMP_HINT_TEXT, GMP_ALLOW_PARTIAL)
 select 'MAI3720', 'HA_INSPECTION_TYPE', 3, 'Inspection Type', 'Y', 
    1, 'IAL_DOMAIN=''INSP_TYPE''', 'N', 'Y', 'N', 
    'Y', 'N', 'Enter the Inspection Type (Mandatory)', 'N' FROM dual
    WHERE NOT EXISTS (SELECT 1 FROM GRI_MODULE_PARAMS
                   WHERE GMP_MODULE = 'MAI3720' AND  GMP_PARAM = 'HA_INSPECTION_TYPE');
                   
Insert into GRI_MODULE_PARAMS
   (GMP_MODULE, GMP_PARAM, GMP_SEQ, GMP_PARAM_DESCR, GMP_MANDATORY, 
    GMP_NO_ALLOWED, GMP_WHERE, GMP_TAG_RESTRICTION, GMP_VISIBLE, GMP_GAZETTEER, 
    GMP_LOV, GMP_WILDCARD, GMP_HINT_TEXT, GMP_ALLOW_PARTIAL)
select 'MAI3720', 'FROM_DATE', 4, 'From Date', 'Y', 
    1, '((:FROM_DATE <= :TO_DATE AND :FROM_DATE <=SYSDATE) OR (:TO_DATE IS NULL AND :FROM_DATE <=SYSDATE))', 'N', 'Y', 'N', 
    'N', 'N', 'Enter From Date', 'N' FROM dual
    WHERE NOT EXISTS (SELECT 1 FROM GRI_MODULE_PARAMS
                   WHERE GMP_MODULE = 'MAI3720' AND  GMP_PARAM = 'FROM_DATE');
                   
Insert into GRI_MODULE_PARAMS
   (GMP_MODULE, GMP_PARAM, GMP_SEQ, GMP_PARAM_DESCR, GMP_MANDATORY, 
    GMP_NO_ALLOWED, GMP_WHERE, GMP_TAG_RESTRICTION, GMP_VISIBLE, GMP_GAZETTEER, 
    GMP_LOV, GMP_WILDCARD, GMP_HINT_TEXT, GMP_ALLOW_PARTIAL)
 select 'MAI3720', 'TO_DATE', 5, 'To Date', 'Y', 
    1, '((:FROM_DATE <= :TO_DATE AND :TO_DATE <=SYSDATE) OR (:FROM_DATE IS NULL AND :TO_DATE <=SYSDATE)', 'N', 'Y', 'N', 
    'N', 'N', 'Enter To date', 'N' FROM dual
    WHERE NOT EXISTS (SELECT 1 FROM GRI_MODULE_PARAMS
                   WHERE GMP_MODULE = 'MAI3720' AND  GMP_PARAM = 'TO_DATE');
                   
Insert into GRI_MODULE_PARAMS
   (GMP_MODULE, GMP_PARAM, GMP_SEQ, GMP_PARAM_DESCR, GMP_MANDATORY, 
    GMP_NO_ALLOWED, GMP_WHERE, GMP_TAG_RESTRICTION, GMP_VISIBLE, GMP_GAZETTEER, GMP_LOV, 
    GMP_WILDCARD, GMP_HINT_TEXT, GMP_ALLOW_PARTIAL)
 SELECT 'MAI3720', 'YES_NO', 6, 'Download Immediately', 'Y', 
    1,'GPL_PARAM = '||''''||'YES_NO'||'''', 'N', 'Y', 'N', 'Y', 
    'N', 'Create Batch and Download?', 'N' FROM dual
    WHERE NOT EXISTS (SELECT 1 FROM GRI_MODULE_PARAMS
                   WHERE GMP_MODULE = 'MAI3720' AND  GMP_PARAM = 'YES_NO');

Insert into GRI_MODULE_PARAMS
   (GMP_MODULE, GMP_PARAM, GMP_SEQ, GMP_PARAM_DESCR, GMP_MANDATORY, 
    GMP_NO_ALLOWED, GMP_TAG_RESTRICTION, GMP_VISIBLE, GMP_GAZETTEER, GMP_LOV, 
    GMP_WILDCARD, GMP_HINT_TEXT, GMP_ALLOW_PARTIAL)
 SELECT 'MAI3730','BATCH_NUM',1,'Inspection Batch Number','Y',1,'N','Y','N','N','N',null,'N'FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM GRI_MODULE_PARAMS
                   WHERE GMP_MODULE = 'MAI3730'AND  GMP_PARAM = 'BATCH_NUM');					   
                   
----------------------------------------------------------------------------------------
-- HIG_MODULE_ROLES
--
-- select * from nm3_metadata.hig_module_roles
-- order by hmr_module
--         ,hmr_role
--
----------------------------------------------------------------------------------------

SET TERM ON
PROMPT hig_module_roles
SET TERM OFF

INSERT INTO HIG_MODULE_ROLES
       (HMR_MODULE
       ,HMR_ROLE
       ,HMR_MODE
       )
SELECT 
        'MAI3700'
       ,'MAI_ADMIN'
       ,'NORMAL' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM HIG_MODULE_ROLES
                   WHERE HMR_MODULE = 'MAI3700'
                    AND  HMR_ROLE = 'MAI_ADMIN');
                    
INSERT INTO HIG_MODULE_ROLES
       (HMR_MODULE
       ,HMR_ROLE
       ,HMR_MODE
       )
SELECT 
        'MAI3710'
       ,'MAI_ADMIN'
       ,'NORMAL' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM HIG_MODULE_ROLES
                   WHERE HMR_MODULE = 'MAI3710'
                    AND  HMR_ROLE = 'MAI_ADMIN');

INSERT INTO HIG_MODULE_ROLES
       (HMR_MODULE
       ,HMR_ROLE
       ,HMR_MODE
       )
SELECT 
        'MAI3720'
       ,'MAI_ADMIN'
       ,'NORMAL' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM HIG_MODULE_ROLES
                   WHERE HMR_MODULE = 'MAI3720'
                    AND  HMR_ROLE = 'MAI_ADMIN');

INSERT INTO HIG_MODULE_ROLES
       (HMR_MODULE
       ,HMR_ROLE
       ,HMR_MODE
       )
SELECT 
        'MAI3730'
       ,'MAI_ADMIN'
       ,'NORMAL' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM HIG_MODULE_ROLES
                   WHERE HMR_MODULE = 'MAI3730'
                    AND  HMR_ROLE = 'MAI_ADMIN');					
 
----------------------------------------------------------------------------------------
--
--nm_inv_domains_all
--
----------------------------------------------------------------------------------------
SET TERM ON
PROMPT nm_inv_domains_all
SET TERM OFF

INSERT INTO nm_inv_domains_all
       (ID_DOMAIN
       ,ID_TITLE
       ,ID_START_DATE
       ,ID_DATATYPE
       )
SELECT 
        'INSP_COND'
       ,'ASSET CONDITION'
       ,TO_DATE('01/JAN/1900')
       ,'VARCHAR2'
        FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM nm_inv_domains_all
                   WHERE ID_DOMAIN = 'INSP_COND');
                   
INSERT INTO nm_inv_domains_all
       (ID_DOMAIN
       ,ID_TITLE
       ,ID_START_DATE
       ,ID_DATATYPE
       )
SELECT 
        'INSP_INTERVALS'
       ,'INSPECTION INTERVALS'
       ,TO_DATE('01/JAN/1900')
       ,'VARCHAR2'
        FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM nm_inv_domains_all
                   WHERE ID_DOMAIN = 'INSP_INTERVALS');

INSERT INTO nm_inv_domains_all
       (ID_DOMAIN
       ,ID_TITLE
       ,ID_START_DATE
       ,ID_DATATYPE
       )
SELECT 
        'INSP_SOURCE'
       ,'INSPECTION SOURCE'
       ,TO_DATE('01/JAN/1900')
       ,'VARCHAR2'
        FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM nm_inv_domains_all
                   WHERE ID_DOMAIN = 'INSP_SOURCE');                                      

INSERT INTO nm_inv_domains_all
       (ID_DOMAIN
       ,ID_TITLE
       ,ID_START_DATE
       ,ID_DATATYPE
       )
SELECT 
        'INSP_TYPE'
       ,'INSPECTION TYPE'
       ,TO_DATE('01/JAN/1900')
       ,'VARCHAR2'
        FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM nm_inv_domains_all
                   WHERE ID_DOMAIN = 'INSP_TYPE');                                      

INSERT INTO nm_inv_domains_all
       (ID_DOMAIN
       ,ID_TITLE
       ,ID_START_DATE
       ,ID_DATATYPE
       )
SELECT 
        'Y_OR_N'
       ,'Y_OR_N'
       ,TO_DATE('01/JAN/1900')
       ,'VARCHAR2'
        FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM nm_inv_domains_all
                   WHERE ID_DOMAIN = 'Y_OR_N');                              
 ----------------------------------------------------------------------------------------
--
--nm_inv_attri_lookup_all
--
----------------------------------------------------------------------------------------
SET TERM ON
PROMPT nm_inv_attri_lookup_all
SET TERM OFF


INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_COND','0','Not Applicable', TO_DATE('01-JAN-00'),1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_COND' AND IAL_VALUE = '0');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_COND','1','As New', TO_DATE('01-JAN-00'),2 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_COND' AND IAL_VALUE = '1');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_COND','2','Condition 2', TO_DATE('01-JAN-00'),3 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_COND' AND IAL_VALUE = '2');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_COND','3','Condition 3', TO_DATE('01-JAN-00'),4 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_COND' AND IAL_VALUE = '3');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_COND','4','Condition 4', TO_DATE('01-JAN-00'),5 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_COND' AND IAL_VALUE = '4');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_COND','5','Condition 5', TO_DATE('01-JAN-00'),5 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_COND' AND IAL_VALUE = '5');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_COND','6','Start of Contract', TO_DATE('01-JAN-00'),5 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_COND' AND IAL_VALUE = '6');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_INTERVALS','100','None', TO_DATE('01-JAN-00'),1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_INTERVALS' AND IAL_VALUE = '100');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_INTERVALS','101','Not Set', TO_DATE('01-JAN-00'),2 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_INTERVALS' AND IAL_VALUE = '101');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_INTERVALS','224','24 Hours', TO_DATE('01-JAN-00'),3 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_INTERVALS' AND IAL_VALUE = '224');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_INTERVALS','301',' 1 Days', TO_DATE('01-JAN-00'),4 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_INTERVALS' AND IAL_VALUE = '301');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_INTERVALS','305',' 5 Days', TO_DATE('01-JAN-00'),5 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_INTERVALS' AND IAL_VALUE = '305');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_INTERVALS','307',' 7 Days', TO_DATE('01-JAN-00'),6 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_INTERVALS' AND IAL_VALUE = '307');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_INTERVALS','314','14 Days', TO_DATE('01-JAN-00'),7 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_INTERVALS' AND IAL_VALUE = '314');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_INTERVALS','321','21 Days', TO_DATE('01-JAN-00'),8 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_INTERVALS' AND IAL_VALUE = '321');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_INTERVALS','328','28 Days', TO_DATE('01-JAN-00'),9 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_INTERVALS' AND IAL_VALUE = '328');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_INTERVALS','335','35 Days', TO_DATE('01-JAN-00'),10 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_INTERVALS' AND IAL_VALUE = '335');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_INTERVALS','401',' 1 Months', TO_DATE('01-JAN-00'),11 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_INTERVALS' AND IAL_VALUE = '401');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_INTERVALS','403',' 3 Months', TO_DATE('01-JAN-00'),12 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_INTERVALS' AND IAL_VALUE = '403');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_INTERVALS','406',' 6 Months', TO_DATE('01-JAN-00'),13 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_INTERVALS' AND IAL_VALUE = '406');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_INTERVALS','412','12 Months=4000hrs', TO_DATE('01-JAN-00'),14 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_INTERVALS' AND IAL_VALUE = '412');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_INTERVALS','418','18 Months=6000hrs', TO_DATE('01-JAN-00'),15 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_INTERVALS' AND IAL_VALUE = '418');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_INTERVALS','424','24 Months=8000hrs', TO_DATE('01-JAN-00'),16 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_INTERVALS' AND IAL_VALUE = '424');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_INTERVALS','430','30 Months', TO_DATE('01-JAN-00'),17 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_INTERVALS' AND IAL_VALUE = '430');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_INTERVALS','501',' 1 Year', TO_DATE('01-JAN-00'),18 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_INTERVALS' AND IAL_VALUE = '501');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_INTERVALS','502',' 2 Years', TO_DATE('01-JAN-00'),19 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_INTERVALS' AND IAL_VALUE = '502');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_INTERVALS','503',' 3 Years', TO_DATE('01-JAN-00'),20 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_INTERVALS' AND IAL_VALUE = '503');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_INTERVALS','505',' 5 Years', TO_DATE('01-JAN-00'),21 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_INTERVALS' AND IAL_VALUE = '505');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_INTERVALS','506',' 6 Years', TO_DATE('01-JAN-00'),22 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_INTERVALS' AND IAL_VALUE = '506');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_INTERVALS','507',' 7 Years', TO_DATE('01-JAN-00'),23 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_INTERVALS' AND IAL_VALUE = '507');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_INTERVALS','510','10 Years', TO_DATE('01-JAN-00'),24 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_INTERVALS' AND IAL_VALUE = '510');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_INTERVALS','999','1 hour', TO_DATE('01-JAN-00'),25 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_INTERVALS' AND IAL_VALUE = '999');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_INTERVALS','310','10 Days', TO_DATE('01-JAN-00'),26 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_INTERVALS' AND IAL_VALUE = '310');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_SOURCE','SCHEDULED','Scheduled Inspection', TO_DATE('01-JAN-00'),1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_SOURCE' AND IAL_VALUE = 'SCHEDULED');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_SOURCE','AD-HOC','Ad Hoc Inspection', TO_DATE('01-JAN-00'),2 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_SOURCE' AND IAL_VALUE = 'AD-HOC');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_TYPE','TYPE 1','Type 1 Inspection', TO_DATE('01-JAN-00'),1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_TYPE' AND IAL_VALUE = 'TYPE 1');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_TYPE','TYPE 2','Type 2 Inspection', TO_DATE('01-JAN-00'),2 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_TYPE' AND IAL_VALUE = 'TYPE 2');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_TYPE','TYPE 3','Type 3 Inspection', TO_DATE('01-JAN-00'),3 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_TYPE' AND IAL_VALUE = 'TYPE 3');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_TYPE','TYPE 4','Type 4 Inspection', TO_DATE('01-JAN-00'),4 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_TYPE' AND IAL_VALUE = 'TYPE 4');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_TYPE','TYPE 5','Type 5 Inspection', TO_DATE('01-JAN-00'),5 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_TYPE' AND IAL_VALUE = 'TYPE 5');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_TYPE','TYPE 6','Type 6 Inspection', TO_DATE('01-JAN-00'),6 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_TYPE' AND IAL_VALUE = 'TYPE 6');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_TYPE','TYPE 7','Type 7 Inspection', TO_DATE('01-JAN-00'),7 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_TYPE' AND IAL_VALUE = 'TYPE 7');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_TYPE','TYPE 8','Type 8 Inspection', TO_DATE('01-JAN-00'),8 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_TYPE' AND IAL_VALUE = 'TYPE 8');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_TYPE','TYPE 9','Type 9 Inspection', TO_DATE('01-JAN-00'),9 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_TYPE' AND IAL_VALUE = 'TYPE 9');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'INSP_TYPE','TYPE 10','Type 10 Inspection', TO_DATE('01-JAN-00'),10 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'INSP_TYPE' AND IAL_VALUE = 'TYPE 10');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'Y_OR_N','N','No', TO_DATE('01-JAN-00'),1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'Y_OR_N' AND IAL_VALUE = 'N');

INSERT INTO NM_INV_ATTRI_LOOKUP_ALL
(IAL_DOMAIN, IAL_VALUE, IAL_MEANING, IAL_START_DATE, IAL_SEQ)
SELECT 'Y_OR_N','Y','Yes', TO_DATE('01-JAN-00'),1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM NM_INV_ATTRI_LOOKUP_ALL WHERE IAL_DOMAIN = 'Y_OR_N' AND IAL_VALUE = 'Y');
----------------------------------------------------------------------------------------
-- NM_INV_TYPES_ALL
--
-- select * from nm3_metadata.nm_inv_types_all
-- order by nit_inv_type
--
----------------------------------------------------------------------------------------

SET TERM ON
PROMPT nm_inv_types_all
SET TERM OFF
INSERT INTO NM_INV_TYPES_ALL     (NIT_INV_TYPE
       ,NIT_PNT_OR_CONT
       ,NIT_X_SECT_ALLOW_FLAG
       ,NIT_ELEC_DRAIN_CARR
       ,NIT_CONTIGUOUS
       ,NIT_REPLACEABLE
       ,NIT_EXCLUSIVE
       ,NIT_CATEGORY
       ,NIT_DESCR
       ,NIT_LINEAR
       ,NIT_USE_XY
       ,NIT_MULTIPLE_ALLOWED
       ,NIT_END_LOC_ONLY
       ,NIT_SCREEN_SEQ
       ,NIT_VIEW_NAME
       ,NIT_START_DATE
       ,NIT_END_DATE
       ,NIT_SHORT_DESCR
       ,NIT_FLEX_ITEM_FLAG
       ,NIT_TABLE_NAME
       ,NIT_LR_NE_COLUMN_NAME
       ,NIT_LR_ST_CHAIN
       ,NIT_LR_END_CHAIN
       ,NIT_ADMIN_TYPE
       ,NIT_ICON_NAME
       ,NIT_TOP
       ,NIT_FOREIGN_PK_COLUMN
       ,NIT_UPDATE_ALLOWED
       ,NIT_NOTES
       )
SELECT 'INSP','P','N','C','N','Y','N','I','Inspections','N','N','N','N',null
       ,'V_NM_INSP',to_date('01-JAN-00')
       ,null
       ,'','N','','','','','NETW','','N','','Y','' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM NM_INV_TYPES_ALL
                   WHERE NIT_INV_TYPE = 'INSP');


----------------------------------------------------------------------------------------
-- NM_INV_TYPE_ATTRIBS_ALL
--
-- select * from nm3_metadata.nm_inv_type_attribs_all
-- order by ita_inv_type
--         ,ita_attrib_name
--
----------------------------------------------------------------------------------------

SET TERM ON
PROMPT nm_inv_type_attribs_all
SET TERM OFF
INSERT INTO NM_INV_TYPE_ATTRIBS_ALL
       (ITA_INV_TYPE
       ,ITA_ATTRIB_NAME
       ,ITA_DYNAMIC_ATTRIB
       ,ITA_DISP_SEQ_NO
       ,ITA_MANDATORY_YN
       ,ITA_FORMAT
       ,ITA_FLD_LENGTH
       ,ITA_DEC_PLACES
       ,ITA_SCRN_TEXT
       ,ITA_ID_DOMAIN
       ,ITA_VALIDATE_YN
       ,ITA_DTP_CODE
       ,ITA_MAX
       ,ITA_MIN
       ,ITA_VIEW_ATTRI
       ,ITA_VIEW_COL_NAME
       ,ITA_START_DATE
       ,ITA_END_DATE
       ,ITA_QUERYABLE
       ,ITA_UKPMS_PARAM_NO
       ,ITA_UNITS
       ,ITA_FORMAT_MASK
       ,ITA_EXCLUSIVE
       ,ITA_KEEP_HISTORY_YN
       ,ITA_QUERY
       ,ITA_DISPLAYED
       ,ITA_DISP_WIDTH
       ,ITA_INSPECTABLE
       ,ITA_CASE
       )
SELECT 'INSP','IIT_CHR_ATTRIB26','N',3,'Y','VARCHAR2',50,null
       ,'Inspection Type','INSP_TYPE','Y','',null
       ,null
       ,'INSP_TYPE','INSP_TYPE',to_date('01-JAN-00')
       ,null
       ,'Y',null
       ,null
       ,'','N','N','','Y',10,'Y','UPPER'FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM NM_INV_TYPE_ATTRIBS_ALL
                   WHERE ITA_INV_TYPE = 'INSP'AND  ITA_ATTRIB_NAME = 'IIT_CHR_ATTRIB26');
				   
INSERT INTO NM_INV_TYPE_ATTRIBS_ALL
       (ITA_INV_TYPE
       ,ITA_ATTRIB_NAME
       ,ITA_DYNAMIC_ATTRIB
       ,ITA_DISP_SEQ_NO
       ,ITA_MANDATORY_YN
       ,ITA_FORMAT
       ,ITA_FLD_LENGTH
       ,ITA_DEC_PLACES
       ,ITA_SCRN_TEXT
       ,ITA_ID_DOMAIN
       ,ITA_VALIDATE_YN
       ,ITA_DTP_CODE
       ,ITA_MAX
       ,ITA_MIN
       ,ITA_VIEW_ATTRI
       ,ITA_VIEW_COL_NAME
       ,ITA_START_DATE
       ,ITA_END_DATE
       ,ITA_QUERYABLE
       ,ITA_UKPMS_PARAM_NO
       ,ITA_UNITS
       ,ITA_FORMAT_MASK
       ,ITA_EXCLUSIVE
       ,ITA_KEEP_HISTORY_YN
       ,ITA_QUERY
       ,ITA_DISPLAYED
       ,ITA_DISP_WIDTH
       ,ITA_INSPECTABLE
       ,ITA_CASE
       )
SELECT 'INSP','IIT_CHR_ATTRIB27','N',5,'Y','VARCHAR2',50,null
       ,'Inspection Source','INSP_SOURCE','Y','',null
       ,null
       ,'INSP_SOURCE','INSP_SOURCE',to_date('01-JAN-00')
       ,null
       ,'Y',null
       ,null
       ,'','N','N','','Y',10,'Y','UPPER'FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM NM_INV_TYPE_ATTRIBS_ALL
                   WHERE ITA_INV_TYPE = 'INSP'AND  ITA_ATTRIB_NAME = 'IIT_CHR_ATTRIB27');
				   
INSERT INTO NM_INV_TYPE_ATTRIBS_ALL
       (ITA_INV_TYPE
       ,ITA_ATTRIB_NAME
       ,ITA_DYNAMIC_ATTRIB
       ,ITA_DISP_SEQ_NO
       ,ITA_MANDATORY_YN
       ,ITA_FORMAT
       ,ITA_FLD_LENGTH
       ,ITA_DEC_PLACES
       ,ITA_SCRN_TEXT
       ,ITA_ID_DOMAIN
       ,ITA_VALIDATE_YN
       ,ITA_DTP_CODE
       ,ITA_MAX
       ,ITA_MIN
       ,ITA_VIEW_ATTRI
       ,ITA_VIEW_COL_NAME
       ,ITA_START_DATE
       ,ITA_END_DATE
       ,ITA_QUERYABLE
       ,ITA_UKPMS_PARAM_NO
       ,ITA_UNITS
       ,ITA_FORMAT_MASK
       ,ITA_EXCLUSIVE
       ,ITA_KEEP_HISTORY_YN
       ,ITA_QUERY
       ,ITA_DISPLAYED
       ,ITA_DISP_WIDTH
       ,ITA_INSPECTABLE
       ,ITA_CASE
       )
SELECT 'INSP','IIT_CHR_ATTRIB28','N',8,'N','VARCHAR2',3,null
       ,'Defects Found?','Y_OR_N','Y','',null
       ,null
       ,'INSP_DEF_FOUND_FLAG','INSP_DEF_FOUND_FLAG',to_date('01-JAN-00')
       ,null
       ,'Y',null
       ,null
       ,'','N','N','','Y',2,'Y','UPPER'FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM NM_INV_TYPE_ATTRIBS_ALL
                   WHERE ITA_INV_TYPE = 'INSP'AND  ITA_ATTRIB_NAME = 'IIT_CHR_ATTRIB28');
				   
INSERT INTO NM_INV_TYPE_ATTRIBS_ALL
       (ITA_INV_TYPE
       ,ITA_ATTRIB_NAME
       ,ITA_DYNAMIC_ATTRIB
       ,ITA_DISP_SEQ_NO
       ,ITA_MANDATORY_YN
       ,ITA_FORMAT
       ,ITA_FLD_LENGTH
       ,ITA_DEC_PLACES
       ,ITA_SCRN_TEXT
       ,ITA_ID_DOMAIN
       ,ITA_VALIDATE_YN
       ,ITA_DTP_CODE
       ,ITA_MAX
       ,ITA_MIN
       ,ITA_VIEW_ATTRI
       ,ITA_VIEW_COL_NAME
       ,ITA_START_DATE
       ,ITA_END_DATE
       ,ITA_QUERYABLE
       ,ITA_UKPMS_PARAM_NO
       ,ITA_UNITS
       ,ITA_FORMAT_MASK
       ,ITA_EXCLUSIVE
       ,ITA_KEEP_HISTORY_YN
       ,ITA_QUERY
       ,ITA_DISPLAYED
       ,ITA_DISP_WIDTH
       ,ITA_INSPECTABLE
       ,ITA_CASE
       )
SELECT 'INSP','IIT_CHR_ATTRIB29','N',9,'N','VARCHAR2',3,null
       ,'Inspected?','Y_OR_N','Y','',null
       ,null
       ,'INSP_INSPECTED_FLAG','INSP_INSPECTED_FLAG',to_date('01-JAN-00')
       ,null
       ,'Y',null
       ,null
       ,'','N','N','','Y',2,'Y','UPPER'FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM NM_INV_TYPE_ATTRIBS_ALL
                   WHERE ITA_INV_TYPE = 'INSP'AND  ITA_ATTRIB_NAME = 'IIT_CHR_ATTRIB29');
				   
INSERT INTO NM_INV_TYPE_ATTRIBS_ALL
       (ITA_INV_TYPE
       ,ITA_ATTRIB_NAME
       ,ITA_DYNAMIC_ATTRIB
       ,ITA_DISP_SEQ_NO
       ,ITA_MANDATORY_YN
       ,ITA_FORMAT
       ,ITA_FLD_LENGTH
       ,ITA_DEC_PLACES
       ,ITA_SCRN_TEXT
       ,ITA_ID_DOMAIN
       ,ITA_VALIDATE_YN
       ,ITA_DTP_CODE
       ,ITA_MAX
       ,ITA_MIN
       ,ITA_VIEW_ATTRI
       ,ITA_VIEW_COL_NAME
       ,ITA_START_DATE
       ,ITA_END_DATE
       ,ITA_QUERYABLE
       ,ITA_UKPMS_PARAM_NO
       ,ITA_UNITS
       ,ITA_FORMAT_MASK
       ,ITA_EXCLUSIVE
       ,ITA_KEEP_HISTORY_YN
       ,ITA_QUERY
       ,ITA_DISPLAYED
       ,ITA_DISP_WIDTH
       ,ITA_INSPECTABLE
       ,ITA_CASE
       )
SELECT 'INSP','IIT_CHR_ATTRIB30','N',11,'N','VARCHAR2',50,null
       ,'Condition Rating','INSP_COND','Y','',null
       ,null
       ,'INSP_CONDITION','INSP_CONDITION',to_date('01-JAN-00')
       ,null
       ,'Y',null
       ,null
       ,'','N','N','','Y',5,'Y','UPPER'FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM NM_INV_TYPE_ATTRIBS_ALL
                   WHERE ITA_INV_TYPE = 'INSP'AND  ITA_ATTRIB_NAME = 'IIT_CHR_ATTRIB30');
				   
INSERT INTO NM_INV_TYPE_ATTRIBS_ALL
       (ITA_INV_TYPE
       ,ITA_ATTRIB_NAME
       ,ITA_DYNAMIC_ATTRIB
       ,ITA_DISP_SEQ_NO
       ,ITA_MANDATORY_YN
       ,ITA_FORMAT
       ,ITA_FLD_LENGTH
       ,ITA_DEC_PLACES
       ,ITA_SCRN_TEXT
       ,ITA_ID_DOMAIN
       ,ITA_VALIDATE_YN
       ,ITA_DTP_CODE
       ,ITA_MAX
       ,ITA_MIN
       ,ITA_VIEW_ATTRI
       ,ITA_VIEW_COL_NAME
       ,ITA_START_DATE
       ,ITA_END_DATE
       ,ITA_QUERYABLE
       ,ITA_UKPMS_PARAM_NO
       ,ITA_UNITS
       ,ITA_FORMAT_MASK
       ,ITA_EXCLUSIVE
       ,ITA_KEEP_HISTORY_YN
       ,ITA_QUERY
       ,ITA_DISPLAYED
       ,ITA_DISP_WIDTH
       ,ITA_INSPECTABLE
       ,ITA_CASE
       )
SELECT 'INSP','IIT_CHR_ATTRIB31','N',4,'Y','VARCHAR2',50,null
       ,'Asset type','','N','',null
       ,null
       ,'ASSET_TYPE','ASSET_TYPE',to_date('01-JAN-01')
       ,null
       ,'Y',null
       ,null
       ,'','N','N','','Y',10,'Y','UPPER'FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM NM_INV_TYPE_ATTRIBS_ALL
                   WHERE ITA_INV_TYPE = 'INSP'AND  ITA_ATTRIB_NAME = 'IIT_CHR_ATTRIB31');
				   
INSERT INTO NM_INV_TYPE_ATTRIBS_ALL
       (ITA_INV_TYPE
       ,ITA_ATTRIB_NAME
       ,ITA_DYNAMIC_ATTRIB
       ,ITA_DISP_SEQ_NO
       ,ITA_MANDATORY_YN
       ,ITA_FORMAT
       ,ITA_FLD_LENGTH
       ,ITA_DEC_PLACES
       ,ITA_SCRN_TEXT
       ,ITA_ID_DOMAIN
       ,ITA_VALIDATE_YN
       ,ITA_DTP_CODE
       ,ITA_MAX
       ,ITA_MIN
       ,ITA_VIEW_ATTRI
       ,ITA_VIEW_COL_NAME
       ,ITA_START_DATE
       ,ITA_END_DATE
       ,ITA_QUERYABLE
       ,ITA_UKPMS_PARAM_NO
       ,ITA_UNITS
       ,ITA_FORMAT_MASK
       ,ITA_EXCLUSIVE
       ,ITA_KEEP_HISTORY_YN
       ,ITA_QUERY
       ,ITA_DISPLAYED
       ,ITA_DISP_WIDTH
       ,ITA_INSPECTABLE
       ,ITA_CASE
       )
SELECT 'INSP','IIT_CHR_ATTRIB66','N',10,'N','VARCHAR2',500,null
       ,'Reason Not Inspected','','N','',null
       ,null
       ,'INSP_NOT_INSP_REASON','INSP_NOT_INSP_REASON',to_date('01-JAN-00')
       ,null
       ,'Y',null
       ,null
       ,'','N','N','','Y',10,'Y','MIXED'FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM NM_INV_TYPE_ATTRIBS_ALL
                   WHERE ITA_INV_TYPE = 'INSP'AND  ITA_ATTRIB_NAME = 'IIT_CHR_ATTRIB66');
				   
INSERT INTO NM_INV_TYPE_ATTRIBS_ALL
       (ITA_INV_TYPE
       ,ITA_ATTRIB_NAME
       ,ITA_DYNAMIC_ATTRIB
       ,ITA_DISP_SEQ_NO
       ,ITA_MANDATORY_YN
       ,ITA_FORMAT
       ,ITA_FLD_LENGTH
       ,ITA_DEC_PLACES
       ,ITA_SCRN_TEXT
       ,ITA_ID_DOMAIN
       ,ITA_VALIDATE_YN
       ,ITA_DTP_CODE
       ,ITA_MAX
       ,ITA_MIN
       ,ITA_VIEW_ATTRI
       ,ITA_VIEW_COL_NAME
       ,ITA_START_DATE
       ,ITA_END_DATE
       ,ITA_QUERYABLE
       ,ITA_UKPMS_PARAM_NO
       ,ITA_UNITS
       ,ITA_FORMAT_MASK
       ,ITA_EXCLUSIVE
       ,ITA_KEEP_HISTORY_YN
       ,ITA_QUERY
       ,ITA_DISPLAYED
       ,ITA_DISP_WIDTH
       ,ITA_INSPECTABLE
       ,ITA_CASE
       )
SELECT 'INSP','IIT_CHR_ATTRIB67','N',12,'N','VARCHAR2',500,null
       ,'Condition Comment','','N','',null
       ,null
       ,'INSP_CONDITION_COMMENT','INSP_CONDITION_COMMENT',to_date('01-JAN-00')
       ,null
       ,'Y',null
       ,null
       ,'','N','N','','Y',10,'Y','MIXED'FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM NM_INV_TYPE_ATTRIBS_ALL
                   WHERE ITA_INV_TYPE = 'INSP'AND  ITA_ATTRIB_NAME = 'IIT_CHR_ATTRIB67');
				   
INSERT INTO NM_INV_TYPE_ATTRIBS_ALL
       (ITA_INV_TYPE
       ,ITA_ATTRIB_NAME
       ,ITA_DYNAMIC_ATTRIB
       ,ITA_DISP_SEQ_NO
       ,ITA_MANDATORY_YN
       ,ITA_FORMAT
       ,ITA_FLD_LENGTH
       ,ITA_DEC_PLACES
       ,ITA_SCRN_TEXT
       ,ITA_ID_DOMAIN
       ,ITA_VALIDATE_YN
       ,ITA_DTP_CODE
       ,ITA_MAX
       ,ITA_MIN
       ,ITA_VIEW_ATTRI
       ,ITA_VIEW_COL_NAME
       ,ITA_START_DATE
       ,ITA_END_DATE
       ,ITA_QUERYABLE
       ,ITA_UKPMS_PARAM_NO
       ,ITA_UNITS
       ,ITA_FORMAT_MASK
       ,ITA_EXCLUSIVE
       ,ITA_KEEP_HISTORY_YN
       ,ITA_QUERY
       ,ITA_DISPLAYED
       ,ITA_DISP_WIDTH
       ,ITA_INSPECTABLE
       ,ITA_CASE
       )
SELECT 'INSP','IIT_DATE_ATTRIB86','N',6,'N','DATE',7,null
       ,'Date Inspection Due','','N','',null
       ,null
       ,'INSP_DATE_DUE','INSP_DATE_DUE',to_date('01-JAN-00')
       ,null
       ,'Y',null
       ,null
       ,'','N','N','','Y',10,'Y','UPPER'FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM NM_INV_TYPE_ATTRIBS_ALL
                   WHERE ITA_INV_TYPE = 'INSP'AND  ITA_ATTRIB_NAME = 'IIT_DATE_ATTRIB86');
				   
INSERT INTO NM_INV_TYPE_ATTRIBS_ALL
       (ITA_INV_TYPE
       ,ITA_ATTRIB_NAME
       ,ITA_DYNAMIC_ATTRIB
       ,ITA_DISP_SEQ_NO
       ,ITA_MANDATORY_YN
       ,ITA_FORMAT
       ,ITA_FLD_LENGTH
       ,ITA_DEC_PLACES
       ,ITA_SCRN_TEXT
       ,ITA_ID_DOMAIN
       ,ITA_VALIDATE_YN
       ,ITA_DTP_CODE
       ,ITA_MAX
       ,ITA_MIN
       ,ITA_VIEW_ATTRI
       ,ITA_VIEW_COL_NAME
       ,ITA_START_DATE
       ,ITA_END_DATE
       ,ITA_QUERYABLE
       ,ITA_UKPMS_PARAM_NO
       ,ITA_UNITS
       ,ITA_FORMAT_MASK
       ,ITA_EXCLUSIVE
       ,ITA_KEEP_HISTORY_YN
       ,ITA_QUERY
       ,ITA_DISPLAYED
       ,ITA_DISP_WIDTH
       ,ITA_INSPECTABLE
       ,ITA_CASE
       )
SELECT 'INSP','IIT_DATE_ATTRIB87','N',7,'N','DATE',7,null
       ,'Date Inspected','','N','',null
       ,null
       ,'INSP_DATE_INSPECTED','INSP_DATE_INSPECTED',to_date('01-JAN-00')
       ,null
       ,'Y',null
       ,null
       ,'','N','N','','Y',10,'Y','UPPER'FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM NM_INV_TYPE_ATTRIBS_ALL
                   WHERE ITA_INV_TYPE = 'INSP'AND  ITA_ATTRIB_NAME = 'IIT_DATE_ATTRIB87');

INSERT INTO NM_INV_TYPE_ATTRIBS_ALL
       (ITA_INV_TYPE
       ,ITA_ATTRIB_NAME
       ,ITA_DYNAMIC_ATTRIB
       ,ITA_DISP_SEQ_NO
       ,ITA_MANDATORY_YN
       ,ITA_FORMAT
       ,ITA_FLD_LENGTH
       ,ITA_DEC_PLACES
       ,ITA_SCRN_TEXT
       ,ITA_ID_DOMAIN
       ,ITA_VALIDATE_YN
       ,ITA_DTP_CODE
       ,ITA_MAX
       ,ITA_MIN
       ,ITA_VIEW_ATTRI
       ,ITA_VIEW_COL_NAME
       ,ITA_START_DATE
       ,ITA_END_DATE
       ,ITA_QUERYABLE
       ,ITA_UKPMS_PARAM_NO
       ,ITA_UNITS
       ,ITA_FORMAT_MASK
       ,ITA_EXCLUSIVE
       ,ITA_KEEP_HISTORY_YN
       ,ITA_QUERY
       ,ITA_DISPLAYED
       ,ITA_DISP_WIDTH
       ,ITA_INSPECTABLE
       ,ITA_CASE
       )
SELECT 'INSP','IIT_FOREIGN_KEY','N',2,'Y','VARCHAR2',50,null
       ,'Parent Asset ID','','N','',null
       ,null
       ,'INSP_PARENT_ID','INSP_PARENT_ID',to_date('01-JAN-00')
       ,null
       ,'Y',null
       ,null
       ,'','N','N','','Y',10,'Y','UPPER'FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM NM_INV_TYPE_ATTRIBS_ALL
                   WHERE ITA_INV_TYPE = 'INSP'AND  ITA_ATTRIB_NAME = 'IIT_FOREIGN_KEY');

				   INSERT INTO NM_INV_TYPE_ATTRIBS_ALL
       (ITA_INV_TYPE
       ,ITA_ATTRIB_NAME
       ,ITA_DYNAMIC_ATTRIB
       ,ITA_DISP_SEQ_NO
       ,ITA_MANDATORY_YN
       ,ITA_FORMAT
       ,ITA_FLD_LENGTH
       ,ITA_DEC_PLACES
       ,ITA_SCRN_TEXT
       ,ITA_ID_DOMAIN
       ,ITA_VALIDATE_YN
       ,ITA_DTP_CODE
       ,ITA_MAX
       ,ITA_MIN
       ,ITA_VIEW_ATTRI
       ,ITA_VIEW_COL_NAME
       ,ITA_START_DATE
       ,ITA_END_DATE
       ,ITA_QUERYABLE
       ,ITA_UKPMS_PARAM_NO
       ,ITA_UNITS
       ,ITA_FORMAT_MASK
       ,ITA_EXCLUSIVE
       ,ITA_KEEP_HISTORY_YN
       ,ITA_QUERY
       ,ITA_DISPLAYED
       ,ITA_DISP_WIDTH
       ,ITA_INSPECTABLE
       ,ITA_CASE
       )
SELECT 'INSP','IIT_NUM_ATTRIB100','N',1,'N','NUMBER',22,null
       ,'Inspection Batch ID','','N','',null
       ,null
       ,'INSP_BATCH_ID','INSP_BATCH_ID',to_date('24-APR-12')
       ,null
       ,'Y',null
       ,null
       ,'','N','N','','Y',10,'Y','UPPER'FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM NM_INV_TYPE_ATTRIBS_ALL
                   WHERE ITA_INV_TYPE = 'INSP'AND  ITA_ATTRIB_NAME = 'IIT_NUM_ATTRIB100');
                   
Insert into NM_INV_NW_ALL
   (NIN_NW_TYPE, NIN_NIT_INV_CODE, NIN_LOC_MANDATORY, NIN_START_DATE)
 Values
   ('D', 'INSP', 'N', TO_DATE('01/01/2000 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));


                   
exec nm3inv.create_view('INSP');

exec nm3inv_api_gen.build_one('INSP');                                 

----------------------------------------------------------------------------------------
-- NM_INV_TYPE_ROLES
--
-- select * from nm3_metadata.nm_inv_type_roles
-- order by itr_inv_type
--         ,itr_hro_role
--
----------------------------------------------------------------------------------------

SET TERM ON
PROMPT nm_inv_type_roles
SET TERM OFF

INSERT INTO NM_INV_TYPE_ROLES
       (ITR_INV_TYPE
       ,ITR_HRO_ROLE
       ,ITR_MODE
       )
SELECT 
        'INSP'
       ,'NET_USER'
       ,'NORMAL' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM NM_INV_TYPE_ROLES
                   WHERE ITR_INV_TYPE = 'INSP'
                    AND  ITR_HRO_ROLE = 'NET_USER');
                    



--   HIG_PROCESS_TYPE_FREQUENCIES
--   HIG_PROCESS_TYPE_FILES
--   HIG_PROCESS_TYPE_FILE_EXT                    

----------------------------------------------------------------------------------------
-- HIG_PROCESS_TYPES
--
-- select * from mai_metadata.hig_process_types
-- order by hpt_process_type_id
--
----------------------------------------------------------------------------------------

SET TERM ON
PROMPT hig_process_types
SET TERM OFF

INSERT INTO HIG_PROCESS_TYPES
       (HPT_PROCESS_TYPE_ID
       ,HPT_NAME
       ,HPT_DESCR
       ,HPT_WHAT_TO_CALL
       ,HPT_INITIATION_MODULE
       ,HPT_INTERNAL_MODULE
       ,HPT_INTERNAL_MODULE_PARAM
       ,HPT_PROCESS_LIMIT
       ,HPT_RESTARTABLE
       ,HPT_SEE_IN_HIG2510
       ,HPT_POLLING_ENABLED
       ,HPT_POLLING_FTP_TYPE_ID
       ,HPT_AREA_TYPE
       )
SELECT 
        -5001
       ,'Inspection Schedule Generation test'
       ,'Process Used to generate inspection assets'
       ,'ha_insp.initialise;'
       ,''
       ,null
       ,null
       ,null
       ,'N'
       ,'N'
       ,'N'
       ,null
       ,null FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM HIG_PROCESS_TYPES
                   WHERE HPT_PROCESS_TYPE_ID = -5001);                    
				   
INSERT INTO HIG_PROCESS_TYPES
       (HPT_PROCESS_TYPE_ID
       ,HPT_NAME
       ,HPT_DESCR
       ,HPT_WHAT_TO_CALL
       ,HPT_INITIATION_MODULE
       ,HPT_INTERNAL_MODULE
       ,HPT_INTERNAL_MODULE_PARAM
       ,HPT_PROCESS_LIMIT
       ,HPT_RESTARTABLE
       ,HPT_SEE_IN_HIG2510
       ,HPT_POLLING_ENABLED
       ,HPT_POLLING_FTP_TYPE_ID
       ,HPT_AREA_TYPE
       )
SELECT 
        -5002
       ,'Asset Inspection Loader'
       ,'Loads Asset Inspection CSV files'
       ,'ha_insp.csv_update_processing;'
       ,''
       ,null
       ,null
       ,null
       ,'N'
       ,'Y'
       ,'N'
       ,null
       ,null FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM HIG_PROCESS_TYPES
                   WHERE HPT_PROCESS_TYPE_ID = -5002);

----------------------------------------------------------------------------------------
-- HIG_PROCESS_TYPE_ROLES
--
-- select * from mai_metadata.hig_process_type_roles
-- order by hptr_process_type_id
--         ,hptr_role
--
----------------------------------------------------------------------------------------

SET TERM ON
PROMPT hig_process_type_roles
SET TERM OFF

INSERT INTO HIG_PROCESS_TYPE_ROLES
       (HPTR_PROCESS_TYPE_ID
       ,HPTR_ROLE
       )
SELECT 
        -5001
       ,'HIG_USER' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM HIG_PROCESS_TYPE_ROLES
                   WHERE HPTR_PROCESS_TYPE_ID = -5001
                    AND  HPTR_ROLE = 'HIG_USER');
					
INSERT INTO HIG_PROCESS_TYPE_ROLES
       (HPTR_PROCESS_TYPE_ID
       ,HPTR_ROLE
       )
SELECT 
        -5002
       ,'HIG_USER' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM HIG_PROCESS_TYPE_ROLES
                   WHERE HPTR_PROCESS_TYPE_ID = -5002
                    AND  HPTR_ROLE = 'HIG_USER');					

					----------------------------------------------------------------------------------------
-- HIG_PROCESS_TYPE_FREQUENCIES
--
-- select * from mai_metadata.hig_process_type_frequencies
-- order by hpfr_process_type_id
--         ,hpfr_frequency_id
--
----------------------------------------------------------------------------------------

SET TERM ON
PROMPT hig_process_type_frequencies
SET TERM OFF

INSERT INTO HIG_PROCESS_TYPE_FREQUENCIES
       (HPFR_PROCESS_TYPE_ID
       ,HPFR_FREQUENCY_ID
       ,HPFR_SEQ
       )
SELECT 
        -5001
       ,-1
       ,1 FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM HIG_PROCESS_TYPE_FREQUENCIES
                   WHERE HPFR_PROCESS_TYPE_ID = -5001
                    AND  HPFR_FREQUENCY_ID = -1);
--
INSERT INTO HIG_PROCESS_TYPE_FREQUENCIES
       (HPFR_PROCESS_TYPE_ID
       ,HPFR_FREQUENCY_ID
       ,HPFR_SEQ
       )
SELECT 
        -5002
       ,-1
       ,1 FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM HIG_PROCESS_TYPE_FREQUENCIES
                   WHERE HPFR_PROCESS_TYPE_ID = -5002
                    AND  HPFR_FREQUENCY_ID = -1);

SET TERM ON
PROMPT hig_DIRECTORIES
SET TERM OFF

Insert into HIG_DIRECTORIES
   (HDIR_NAME, HDIR_PATH, HDIR_PROTECTED)
 select 'ASSET_INSPECTIONS_FAILED', 'E:\exor_dir\area51a\asset_inspections\failed', 'N' from dual
 where NOT EXISTS (select 1 from hig_directories where hdir_path = 'ASSET_INSPECTIONS_FAILED');

Insert into HIG_DIRECTORIES
   (HDIR_NAME, HDIR_PATH, HDIR_PROTECTED)
 select 'ASSET_INSPECTIONS_PROCESSED', 'E:\exor_dir\area51a\asset_inspections\processed', 'N' from dual
 where NOT EXISTS (select 1 from hig_directories where hdir_path = 'ASSET_INSPECTIONS_PROCESSED');

Insert into HIG_DIRECTORIES
   (HDIR_NAME, HDIR_PATH, HDIR_PROTECTED)
 select 'ASSET_INSPECTIONS_UPLOAD', 'E:\exor_dir\area51a\asset_inspections\upload', 'N' from dual
 where NOT EXISTS (select 1 from hig_directories where hdir_path = 'ASSET_INSPECTIONS_UPLOAD');
COMMIT;
				   