/*<TOAD_FILE_CHUNK>*/

delete from HIG_STANDARD_FAVOURITES where HSTF_PARENT = 'OHMS';

delete from HIG_STANDARD_FAVOURITES where HSTF_CHILD = 'OHMS';

delete from GRI_MODULES where GRM_MODULE = 'OHMS_RUN';


delete from HIG_MODULES where 
 HMO_APPLICATION = 'OHMS';

declare

l_merge_id NM_MRG_QUERY_ALL.nmq_id%type;

begin


    select nmq_id into l_merge_id from NM_MRG_QUERY_ALL where NMQ_UNIQUE = 'OHMS_EXTRACT';
    
    delete from  NM_MRG_QUERY_ALL where NMQ_ID = l_merge_id;
    
    exception
    when others then null;
    
end;
/
/*<TOAD_FILE_CHUNK>*/

DROP TABLE V_NM_OHMS_NW CASCADE CONSTRAINTS;
DROP TABLE OHMS_SUBMIT_SAMPLES;

/* ---------- JM, 2011.07.29,14:03
DROP MATERIALIZED VIEW V_NM_CURB137_OUTER_MV_NW;
DROP MATERIALIZED VIEW V_NM_NBI104_OUTER_MV_NW;
DROP MATERIALIZED VIEW V_NM_RDGM107_COUNT_MV_NW;
DROP MATERIALIZED VIEW V_NM_RDGM109_COUNT_MV_NW;
DROP MATERIALIZED VIEW V_NM_RDGM110_COUNT_MV_NW;
DROP MATERIALIZED VIEW V_NM_RDGM111_COUNT_MV_NW;
DROP MATERIALIZED VIEW V_NM_RDGM137_OUTER_MV_NW;
DROP MATERIALIZED VIEW V_NM_RDGM138_SUM_MV_NW;
DROP MATERIALIZED VIEW V_NM_RDGM139_SUM_MV_NW;

DROP MATERIALIZED VIEW V_NM_ROAD131_COUNT_MV_NW;

DROP MATERIALIZED VIEW V_NM_ROAD133_COUNT_MV_NW;

DROP MATERIALIZED VIEW V_NM_SHLD137_OUTER_MV_NW;
DROP MATERIALIZED VIEW V_NM_SPZN114_OUTER_MV_NW;
DROP MATERIALIZED VIEW V_NM_TUNL104_OUTER_MV_NW;
DROP MATERIALIZED VIEW V_NM_URBN114_OUTER_MV_NT;
---------- */

DROP TABLE HPMS_7_NETWORK_MV;
DROP TABLE v_nm_elea566_outer_mv_nt;
DROP TABLE v_nm_urbn502_outer_mv_nt;
DROP TABLE v_nm_nbi504_outer_mv_nw;
DROP TABLE v_nm_tunl504_outer_mv_nw;
DROP TABLE HPMS_TMP_7_507_RDGM;
DROP TABLE HPMS_TMP_RTE_ITEM_HWY;
DROP TABLE HPMS_TMP_RTE_7_507_RDGM;
DROP TABLE hpms_tmp_seg_7_507_rdgm;
DROP TABLE HPMS_TMP_DETAIL_7_507_RDGM;
DROP TABLE v_nm_rdgm507_count_mv_nw;
DROP TABLE v_nm_rdgm507_count_mv_nw;
DROP TABLE HPMS_TMP_7_508_RDGM;
DROP TABLE HPMS_TMP_RTE_ITEM_HWY;
DROP TABLE HPMS_TMP_RTE_7_508_RDGM;
DROP TABLE hpms_tmp_seg_7_508_rdgm;
DROP TABLE HPMS_TMP_DETAIL_7_508_RDGM;
DROP TABLE v_nm_rdgm508_min_mv_nw;
DROP TABLE HPMS_TMP_7_509_RDGM;
DROP TABLE HPMS_TMP_RTE_ITEM_HWY;
DROP TABLE HPMS_TMP_RTE_7_509_RDGM;
DROP TABLE hpms_tmp_seg_7_509_rdgm;
DROP TABLE HPMS_TMP_DETAIL_7_509_RDGM;
DROP TABLE v_nm_rdgm509_count_mv_nw;
DROP TABLE v_nm_urbn510_outer_mv_nt;
DROP TABLE v_nm_spzn514_outer_mv_nw;
DROP TABLE v_nm_urbn514_outer_mv_nt;
DROP TABLE HPMS_TMP_7_538_RDGM;
DROP TABLE HPMS_TMP_RTE_ITEM_HWY;
DROP TABLE HPMS_TMP_RTE_7_538_RDGM;
DROP TABLE hpms_tmp_seg_7_538_rdgm;
DROP TABLE HPMS_TMP_DETAIL_7_538_RDGM;
DROP TABLE v_nm_rdgm538_sum_mv_nw;
DROP TABLE HPMS_TMP_7_539_RDGM;
DROP TABLE HPMS_TMP_RTE_ITEM_HWY;
DROP TABLE HPMS_TMP_RTE_7_539_RDGM;
DROP TABLE hpms_tmp_seg_7_539_rdgm;
DROP TABLE HPMS_TMP_DETAIL_7_539_RDGM;
DROP TABLE v_nm_rdgm539_sum_mv_nw;

DROP TABLE HPMS_TMP_7_540_PRKR;
DROP TABLE HPMS_TMP_RTE_ITEM_HWY;
DROP TABLE HPMS_TMP_RTE_7_540_PRKR;
DROP TABLE hpms_tmp_seg_7_540_prkr;
DROP TABLE HPMS_TMP_DETAIL_7_540_PRKR;
DROP TABLE v_nm_prkr540_count_mv_nw;
DROP TABLE v_nm_cnty563_outer_mv_nt;
DROP TABLE v_nm_elea566_outer_mv_nt;
DROP TABLE HPMS_TMP_7_760_PRKL;
DROP TABLE HPMS_TMP_RTE_ITEM_HWY;
DROP TABLE HPMS_TMP_RTE_7_760_PRKL;
DROP TABLE hpms_tmp_seg_7_760_prkl;
DROP TABLE HPMS_TMP_DETAIL_7_760_PRKL;
DROP TABLE v_nm_prkl760_count_mv_nw;




--drop Procedure XODOT_POPULATE_OHMS_SECTIONS;  --just using the item straight form HPMS

drop package xodot_OHMS;

