/*
Insert into EXOR.NM_INV_TYPE_ATTRIBS_ALL (
 ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_DEC_PLACES, ITA_SCRN_TEXT, ITA_ID_DOMAIN,
 ITA_VALIDATE_YN, ITA_DTP_CODE, ITA_MAX, ITA_MIN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_END_DATE, ITA_QUERYABLE, ITA_UKPMS_PARAM_NO,
 ITA_UNITS, ITA_FORMAT_MASK, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_QUERY, ITA_DISPLAYED,
 ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
Values (
 'SURF', 'IIT_CHR_ATTRIB26', 'Y', 1, 'N', 'VARCHAR2', 50, null, 'PMS pavement meaning', null,
 'Y', null, null, null, 'PMS_PM', 'PMS_PM', trunc(sysdate), null, 'Y', null,
 null, null, 'N', 'N', trunc(sysdate), trunc(sysdate), 'EXOR', 'EXOR', null, 'Y',
 1, 'Y', 'UPPER');
*/

Insert into EXOR.NM_INV_TYPE_ATTRIBS_ALL (
 ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_DEC_PLACES, ITA_SCRN_TEXT, ITA_ID_DOMAIN,
 ITA_VALIDATE_YN, ITA_DTP_CODE, ITA_MAX, ITA_MIN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_END_DATE, ITA_QUERYABLE, ITA_UKPMS_PARAM_NO,
 ITA_UNITS, ITA_FORMAT_MASK, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_QUERY, ITA_DISPLAYED,
 ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
Values (
 'SURF', 'IIT_NUM_ATTRIB16', 'Y', 2, 'N', 'NUMBER', 8, null, 'PMS pavement value', 'PM_PM_PAVETYPE',
 'Y', null, null, null, 'PMS_PV', 'PMS_PV', trunc(sysdate), null, 'Y', null,
 null, null, 'N', 'N', trunc(sysdate), trunc(sysdate), 'EXOR', 'EXOR', null, 'Y',
 1, 'Y', 'UPPER');

 /*
 Insert into EXOR.NM_INV_TYPE_ATTRIBS_ALL (
 ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_DEC_PLACES, ITA_SCRN_TEXT, ITA_ID_DOMAIN,
 ITA_VALIDATE_YN, ITA_DTP_CODE, ITA_MAX, ITA_MIN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_END_DATE, ITA_QUERYABLE, ITA_UKPMS_PARAM_NO,
 ITA_UNITS, ITA_FORMAT_MASK, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_QUERY, ITA_DISPLAYED,
 ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
Values (
 'SURF', 'IIT_CHR_ATTRIB27', 'Y', 3, 'N', 'VARCHAR2', 50, null, 'BD pavement meaning', null,
 'Y', null, null, null, 'BD_PM', 'BD_PM', trunc(sysdate), null, 'Y', null,
 null, null, 'N', 'N', trunc(sysdate), trunc(sysdate), 'EXOR', 'EXOR', null, 'Y',
 1, 'Y', 'UPPER');
*/

Insert into EXOR.NM_INV_TYPE_ATTRIBS_ALL (
 ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_DEC_PLACES, ITA_SCRN_TEXT, ITA_ID_DOMAIN,
 ITA_VALIDATE_YN, ITA_DTP_CODE, ITA_MAX, ITA_MIN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_END_DATE, ITA_QUERYABLE, ITA_UKPMS_PARAM_NO,
 ITA_UNITS, ITA_FORMAT_MASK, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_QUERY, ITA_DISPLAYED,
 ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
Values (
 'SURF', 'IIT_CHR_ATTRIB26', 'Y', 4, 'N', 'VARCHAR2', 8, null, 'BD pavement value', 'KY_SURFTYPE',
 'Y', null, null, null, 'BD_PV', 'BD_PV', trunc(sysdate), null, 'Y', null,
 null, null, 'N', 'N', trunc(sysdate), trunc(sysdate), 'EXOR', 'EXOR', null, 'Y',
 1, 'Y', 'UPPER');
 
 Insert into EXOR.NM_INV_TYPE_ATTRIBS_ALL (
 ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_DEC_PLACES, ITA_SCRN_TEXT, ITA_ID_DOMAIN,
 ITA_VALIDATE_YN, ITA_DTP_CODE, ITA_MAX, ITA_MIN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_END_DATE, ITA_QUERYABLE, ITA_UKPMS_PARAM_NO,
 ITA_UNITS, ITA_FORMAT_MASK, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_QUERY, ITA_DISPLAYED,
 ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
Values (
 'SURF', 'IIT_NUM_ATTRIB18', 'Y', 5, 'N', 'NUMBER', 8, null, 'SURF Code', 'SURF_PAVE_TYPE',
 'Y', null, null, null, 'SURF_CODE', 'SURF_CODE', trunc(sysdate), null, 'Y', null,
 null, null, 'N', 'N', trunc(sysdate), trunc(sysdate), 'EXOR', 'EXOR', null, 'Y',
 1, 'Y', 'UPPER');
 
 /*
 Insert into EXOR.NM_INV_TYPE_ATTRIBS_ALL (
 ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_DEC_PLACES, ITA_SCRN_TEXT, ITA_ID_DOMAIN,
 ITA_VALIDATE_YN, ITA_DTP_CODE, ITA_MAX, ITA_MIN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_END_DATE, ITA_QUERYABLE, ITA_UKPMS_PARAM_NO,
 ITA_UNITS, ITA_FORMAT_MASK, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_QUERY, ITA_DISPLAYED,
 ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
Values (
 'SURF', 'IIT_CHR_ATTRIB28', 'Y', 6, 'N', 'VARCHAR2', 50, null, 'SURF pavement meaning', null,
 'Y', null, null, null, 'SURF_PM', 'SURF_PM', trunc(sysdate), null, 'Y', null,
 null, null, 'N', 'N', trunc(sysdate), trunc(sysdate), 'EXOR', 'EXOR', null, 'Y',
 1, 'Y', 'UPPER');
 */
 
  Insert into EXOR.NM_INV_TYPE_ATTRIBS_ALL (
 ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_DEC_PLACES, ITA_SCRN_TEXT, ITA_ID_DOMAIN,
 ITA_VALIDATE_YN, ITA_DTP_CODE, ITA_MAX, ITA_MIN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_END_DATE, ITA_QUERYABLE, ITA_UKPMS_PARAM_NO,
 ITA_UNITS, ITA_FORMAT_MASK, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_QUERY, ITA_DISPLAYED,
 ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
Values (
 'SURF', 'IIT_CHR_ATTRIB29', 'Y', 7, 'N', 'VARCHAR2', 50, null, 'SURF Source', null,
 'Y', null, null, null, 'SURF_SOURCE', 'SURF_SOURCE', trunc(sysdate), null, 'Y', null,
 null, null, 'N', 'N', trunc(sysdate), trunc(sysdate), 'EXOR', 'EXOR', null, 'Y',
 1, 'Y', 'UPPER');