'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Oracle.DataAccess.Client
Imports Oracle.DataAccess.Types
Imports System
Imports System.Xml.Schema
Imports System.Xml.Serialization


Public Class XODOT_SIGNS_TASK_LIST
    Inherits [Object]
    Implements INullable, IOracleCustomType, IXmlSerializable
    
    Private m_IsNull As Boolean
    
    Private m_XODOT_SIGNS_TASK_LIST_ROW() As XODOT_SIGNS_TASK_LIST_ROW
    
    Public Sub New()
        MyBase.New
        'TODO : Add code to initialise the object
    End Sub
    
    Public Sub New(ByVal str As String)
        MyBase.New
        'TODO : Add code to initialise the object based on the given string 
    End Sub
    
    Public Overridable ReadOnly Property IsNull() As Boolean Implements INullable.IsNull
        Get
            Return Me.m_IsNull
        End Get
    End Property
    
    Public Shared ReadOnly Property Null() As XODOT_SIGNS_TASK_LIST
        Get
            Dim obj As XODOT_SIGNS_TASK_LIST = New XODOT_SIGNS_TASK_LIST()
            obj.m_IsNull = true
            Return obj
        End Get
    End Property
    
    <OracleArrayMappingAttribute()>  _
    Public Overridable Property Value() As XODOT_SIGNS_TASK_LIST_ROW()
        Get
            Return Me.m_XODOT_SIGNS_TASK_LIST_ROW
        End Get
        Set
            Me.m_XODOT_SIGNS_TASK_LIST_ROW = value
        End Set
    End Property
    
    Public Overridable Sub FromCustomObject(ByVal con As Oracle.DataAccess.Client.OracleConnection, ByVal pUdt As System.IntPtr) Implements IOracleCustomType.FromCustomObject
        OracleUdt.SetValue(con, pUdt, 0, Me.m_XODOT_SIGNS_TASK_LIST_ROW)
    End Sub
    
    Public Overridable Sub ToCustomObject(ByVal con As Oracle.DataAccess.Client.OracleConnection, ByVal pUdt As System.IntPtr) Implements IOracleCustomType.ToCustomObject
        Me.m_XODOT_SIGNS_TASK_LIST_ROW = CType(OracleUdt.GetValue(con, pUdt, 0),XODOT_SIGNS_TASK_LIST_ROW())
    End Sub
    
    Public Overridable Sub ReadXml(ByVal reader As System.Xml.XmlReader) Implements IXmlSerializable.ReadXml
        'TODO : Read Serialized Xml Data
    End Sub
    
    Public Overridable Sub WriteXml(ByVal writer As System.Xml.XmlWriter) Implements IXmlSerializable.WriteXml
        'TODO : Serialize object to xml data
    End Sub
    
    Public Overridable Function GetSchema() As XmlSchema Implements IXmlSerializable.GetSchema
        'TODO : Implement GetSchema
        Return Nothing
    End Function
    
    Public Overrides Function ToString() As String
        'TODO : Return a string that represents the current object
        Return ""
    End Function
    
    Public Shared Function Parse(ByVal str As String) As XODOT_SIGNS_TASK_LIST
        'TODO : Add code needed to parse the string and get the object represented by the string
        Return New XODOT_SIGNS_TASK_LIST()
    End Function
End Class

'Factory to create an object for the above class
<OracleCustomTypeMappingAttribute("TRANSINFO.XODOT_SIGNS_TASK_LIST")>  _
Public Class XODOT_SIGNS_TASK_LISTFactory
    Inherits [Object]
    Implements IOracleCustomTypeFactory, IOracleArrayTypeFactory
    
    Public Overridable Function CreateObject() As IOracleCustomType Implements IOracleCustomTypeFactory.CreateObject
        Dim obj As XODOT_SIGNS_TASK_LIST = New XODOT_SIGNS_TASK_LIST()
        Return obj
    End Function
    
    Public Overridable Function CreateArray(ByVal length As Integer) As System.Array Implements IOracleArrayTypeFactory.CreateArray
        Dim collElem((length) - 1) As XODOT_SIGNS_TASK_LIST_ROW
        Return collElem
    End Function
    
    Public Overridable Function CreateStatusArray(ByVal length As Integer) As System.Array Implements IOracleArrayTypeFactory.CreateStatusArray
        Return Nothing
    End Function
End Class
