'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Oracle.DataAccess.Client
Imports Oracle.DataAccess.Types
Imports System
Imports System.Xml.Schema
Imports System.Xml.Serialization


Public Class XODOT_SIGNS_TASK_LIST_ROW
    Inherits [Object]
    Implements INullable, IOracleCustomType, IXmlSerializable
    
    Private m_IsNull As Boolean
    
    Private m_CNT As Decimal
    
    Private m_CNTIsNull As Boolean
    
    Private m_ASSET As String
    
    Public Sub New()
        MyBase.New
        'TODO : Add code to initialise the object
        Me.m_CNTIsNull = true
    End Sub
    
    Public Sub New(ByVal str As String)
        MyBase.New
        'TODO : Add code to initialise the object based on the given string 
    End Sub
    
    Public Overridable ReadOnly Property IsNull() As Boolean Implements INullable.IsNull
        Get
            Return Me.m_IsNull
        End Get
    End Property
    
    Public Shared ReadOnly Property Null() As XODOT_SIGNS_TASK_LIST_ROW
        Get
            Dim obj As XODOT_SIGNS_TASK_LIST_ROW = New XODOT_SIGNS_TASK_LIST_ROW()
            obj.m_IsNull = true
            Return obj
        End Get
    End Property
    
    <OracleObjectMappingAttribute("CNT")>  _
    Public Property CNT() As Decimal
        Get
            Return Me.m_CNT
        End Get
        Set
            Me.m_CNT = value
        End Set
    End Property
    
    Public Property CNTIsNull() As Boolean
        Get
            Return Me.m_CNTIsNull
        End Get
        Set
            Me.m_CNTIsNull = value
        End Set
    End Property
    
    <OracleObjectMappingAttribute("ASSET")>  _
    Public Property ASSET() As String
        Get
            Return Me.m_ASSET
        End Get
        Set
            Me.m_ASSET = value
        End Set
    End Property
    
    Public Overridable Sub FromCustomObject(ByVal con As Oracle.DataAccess.Client.OracleConnection, ByVal pUdt As System.IntPtr) Implements IOracleCustomType.FromCustomObject
        If (CNTIsNull = false) Then
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "CNT", Me.CNT)
        End If
        Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "ASSET", Me.ASSET)
    End Sub
    
    Public Overridable Sub ToCustomObject(ByVal con As Oracle.DataAccess.Client.OracleConnection, ByVal pUdt As System.IntPtr) Implements IOracleCustomType.ToCustomObject
        Me.CNTIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "CNT")
        If (CNTIsNull = false) Then
            Me.CNT = CType(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "CNT"),Decimal)
        End If
        Me.ASSET = CType(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "ASSET"),String)
    End Sub
    
    Public Overridable Sub ReadXml(ByVal reader As System.Xml.XmlReader) Implements IXmlSerializable.ReadXml
        'TODO : Read Serialized Xml Data
    End Sub
    
    Public Overridable Sub WriteXml(ByVal writer As System.Xml.XmlWriter) Implements IXmlSerializable.WriteXml
        'TODO : Serialize object to xml data
    End Sub
    
    Public Overridable Function GetSchema() As XmlSchema Implements IXmlSerializable.GetSchema
        'TODO : Implement GetSchema
        Return Nothing
    End Function
    
    Public Overrides Function ToString() As String
        'TODO : Return a string that represents the current object
        Return ""
    End Function
    
    Public Shared Function Parse(ByVal str As String) As XODOT_SIGNS_TASK_LIST_ROW
        'TODO : Add code needed to parse the string and get the object represented by the string
        Return New XODOT_SIGNS_TASK_LIST_ROW()
    End Function
End Class

'Factory to create an object for the above class
<OracleCustomTypeMappingAttribute("TRANSINFO.XODOT_SIGNS_TASK_LIST_ROW")>  _
Public Class XODOT_SIGNS_TASK_LIST_ROWFactory
    Inherits [Object]
    Implements IOracleCustomTypeFactory
    
    Public Overridable Function CreateObject() As IOracleCustomType Implements IOracleCustomTypeFactory.CreateObject
        Dim obj As XODOT_SIGNS_TASK_LIST_ROW = New XODOT_SIGNS_TASK_LIST_ROW()
        Return obj
    End Function
End Class
