'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports Oracle.DataAccess.Client
Imports Oracle.DataAccess.Types
Imports System
Imports System.Xml.Schema
Imports System.Xml.Serialization


Public Class XODOT_SIGNS_ASSET_OP
    Inherits [Object]
    Implements INullable, IOracleCustomType, IXmlSerializable
    
    Private m_IsNull As Boolean
    
    Private m_NE_ID As Decimal
    
    Private m_NE_IDIsNull As Boolean
    
    Private m_ERR_MSG As String
    
    Private m_ERR_NUM As Decimal
    
    Private m_ERR_NUMIsNull As Boolean
    
    Public Sub New()
        MyBase.New
        'TODO : Add code to initialise the object
        Me.m_NE_IDIsNull = true
        Me.m_ERR_NUMIsNull = true
    End Sub
    
    Public Sub New(ByVal str As String)
        MyBase.New
        'TODO : Add code to initialise the object based on the given string 
    End Sub
    
    Public Overridable ReadOnly Property IsNull() As Boolean Implements INullable.IsNull
        Get
            Return Me.m_IsNull
        End Get
    End Property
    
    Public Shared ReadOnly Property Null() As XODOT_SIGNS_ASSET_OP
        Get
            Dim obj As XODOT_SIGNS_ASSET_OP = New XODOT_SIGNS_ASSET_OP()
            obj.m_IsNull = true
            Return obj
        End Get
    End Property
    
    <OracleObjectMappingAttribute("NE_ID")>  _
    Public Property NE_ID() As Decimal
        Get
            Return Me.m_NE_ID
        End Get
        Set
            Me.m_NE_ID = value
        End Set
    End Property
    
    Public Property NE_IDIsNull() As Boolean
        Get
            Return Me.m_NE_IDIsNull
        End Get
        Set
            Me.m_NE_IDIsNull = value
        End Set
    End Property
    
    <OracleObjectMappingAttribute("ERR_MSG")>  _
    Public Property ERR_MSG() As String
        Get
            Return Me.m_ERR_MSG
        End Get
        Set
            Me.m_ERR_MSG = value
        End Set
    End Property
    
    <OracleObjectMappingAttribute("ERR_NUM")>  _
    Public Property ERR_NUM() As Decimal
        Get
            Return Me.m_ERR_NUM
        End Get
        Set
            Me.m_ERR_NUM = value
        End Set
    End Property
    
    Public Property ERR_NUMIsNull() As Boolean
        Get
            Return Me.m_ERR_NUMIsNull
        End Get
        Set
            Me.m_ERR_NUMIsNull = value
        End Set
    End Property
    
    Public Overridable Sub FromCustomObject(ByVal con As Oracle.DataAccess.Client.OracleConnection, ByVal pUdt As System.IntPtr) Implements IOracleCustomType.FromCustomObject
        If (NE_IDIsNull = false) Then
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "NE_ID", Me.NE_ID)
        End If
        Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "ERR_MSG", Me.ERR_MSG)
        If (ERR_NUMIsNull = false) Then
            Oracle.DataAccess.Types.OracleUdt.SetValue(con, pUdt, "ERR_NUM", Me.ERR_NUM)
        End If
    End Sub
    
    Public Overridable Sub ToCustomObject(ByVal con As Oracle.DataAccess.Client.OracleConnection, ByVal pUdt As System.IntPtr) Implements IOracleCustomType.ToCustomObject
        Me.NE_IDIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "NE_ID")
        If (NE_IDIsNull = false) Then
            Me.NE_ID = CType(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "NE_ID"),Decimal)
        End If
        Me.ERR_MSG = CType(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "ERR_MSG"),String)
        Me.ERR_NUMIsNull = Oracle.DataAccess.Types.OracleUdt.IsDBNull(con, pUdt, "ERR_NUM")
        If (ERR_NUMIsNull = false) Then
            Me.ERR_NUM = CType(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "ERR_NUM"),Decimal)
        End If
    End Sub
    
    Public Overridable Sub ReadXml(ByVal reader As System.Xml.XmlReader) Implements IXmlSerializable.ReadXml
        'TODO : Read Serialized Xml Data
    End Sub
    
    Public Overridable Sub WriteXml(ByVal writer As System.Xml.XmlWriter) Implements IXmlSerializable.WriteXml
        'TODO : Serialize object to xml data
    End Sub
    
    Public Overridable Function GetSchema() As XmlSchema Implements IXmlSerializable.GetSchema
        'TODO : Implement GetSchema
        Return Nothing
    End Function
    
    Public Overrides Function ToString() As String
        'TODO : Return a string that represents the current object
        Return ""
    End Function
    
    Public Shared Function Parse(ByVal str As String) As XODOT_SIGNS_ASSET_OP
        'TODO : Add code needed to parse the string and get the object represented by the string
        Return New XODOT_SIGNS_ASSET_OP()
    End Function
End Class

'Factory to create an object for the above class
<OracleCustomTypeMappingAttribute("TRANSINFO.XODOT_SIGNS_ASSET_OP")>  _
Public Class XODOT_SIGNS_ASSET_OPFactory
    Inherits [Object]
    Implements IOracleCustomTypeFactory
    
    Public Overridable Function CreateObject() As IOracleCustomType Implements IOracleCustomTypeFactory.CreateObject
        Dim obj As XODOT_SIGNS_ASSET_OP = New XODOT_SIGNS_ASSET_OP()
        Return obj
    End Function
End Class
