SET DEFINE OFF;

INSERT INTO NM_THEMES_ALL (NTH_THEME_ID,
                           NTH_THEME_NAME,
                           NTH_TABLE_NAME,
                           NTH_WHERE,
                           NTH_PK_COLUMN,
                           NTH_LABEL_COLUMN,
                           NTH_RSE_TABLE_NAME,
                           NTH_RSE_FK_COLUMN,
                           NTH_ST_CHAIN_COLUMN,
                           NTH_FEATURE_TABLE,
                           NTH_FEATURE_PK_COLUMN,
                           NTH_FEATURE_SHAPE_COLUMN,
                           NTH_HPR_PRODUCT,
                           NTH_LOCATION_UPDATABLE,
                           NTH_THEME_TYPE,
                           NTH_DEPENDENCY,
                           NTH_STORAGE,
                           NTH_UPDATE_ON_EDIT,
                           NTH_USE_HISTORY,
                           NTH_SEQUENCE_NAME,
                           NTH_SNAP_TO_THEME,
                           NTH_LREF_MANDATORY,
                           NTH_TOLERANCE,
                           NTH_TOL_UNITS,
                           NTH_DYNAMIC_THEME)
    SELECT  173,
            'DEFECTS',
            'V_MAI_DEFECTS',
            'DEF_ST_CHAIN IS NOT NULL ',
            'DEFECT_ID',
            'DEFECT_ID',
            'NM_ELEMENTS',
            'DEFECT_ROAD_ID',
            'DEF_ST_CHAIN',
            'MAI_DEFECTS_LR_SDO',
            'DEF_DEFECT_ID',
            'GEOLOC',
            'MAI',
            'Y',
            'SDO',
            'I',
            'S',
            'I',
            'N',
            'NTH_173_SEQ',
            'S',
            'N',
            10,
            1,
            'N'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_THEMES_ALL
                                        WHERE  NTH_THEME_NAME = 'DEFECTS'
                                      );

INSERT INTO NM_INV_TYPES (NIT_INV_TYPE,
                          NIT_PNT_OR_CONT,
                          NIT_X_SECT_ALLOW_FLAG,
                          NIT_ELEC_DRAIN_CARR,
                          NIT_CONTIGUOUS,
                          NIT_REPLACEABLE,
                          NIT_EXCLUSIVE,
                          NIT_CATEGORY,
                          NIT_DESCR,
                          NIT_LINEAR,
                          NIT_USE_XY,
                          NIT_MULTIPLE_ALLOWED,
                          NIT_END_LOC_ONLY,
                          NIT_SCREEN_SEQ,
                          NIT_START_DATE,
                          NIT_SHORT_DESCR,
                          NIT_FLEX_ITEM_FLAG,
                          NIT_TABLE_NAME,
                          NIT_LR_NE_COLUMN_NAME,
                          NIT_LR_ST_CHAIN,
                          NIT_LR_END_CHAIN,
                          NIT_ADMIN_TYPE,
                          NIT_TOP,
                          NIT_FOREIGN_PK_COLUMN,
                          NIT_UPDATE_ALLOWED,
                          NIT_DATE_CREATED,
                          NIT_DATE_MODIFIED,
                          NIT_MODIFIED_BY,
                          NIT_CREATED_BY,
                          NIT_NOTES)
    SELECT  'DEF',
            'P',
            'N',
            'C',
            'N',
            'Y',
            'N',
            'F',
            'Defects',
            'N',
            'Y',
            'Y',
            'N',
            10,
            TO_DATE ('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
            'V_MAI_DEFECTS',
            'N',
            'V_MAI_DEFECTS',
            'DEFECT_NE_ID',
            'DEFECT_BEGIN_MP',
            'DEFECT_BEGIN_MP',
            'WARK',
            'N',
            'DEFECT_ID',
            'Y',
            TO_DATE ('07/02/2008 11:26:29', 'MM/DD/YYYY HH24:MI:SS'),
            TO_DATE ('11/09/2009 16:40:01', 'MM/DD/YYYY HH24:MI:SS'),
            'WORCS',
            'HIGHWAYS',
            'V_MAI_DEFECTS - Foreign Table asset type'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_INV_TYPES
                                        WHERE  NIT_INV_TYPE = 'DEF'
                                      );

INSERT INTO NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE,
                                 ITA_ATTRIB_NAME,
                                 ITA_DYNAMIC_ATTRIB,
                                 ITA_DISP_SEQ_NO,
                                 ITA_MANDATORY_YN,
                                 ITA_FORMAT,
                                 ITA_FLD_LENGTH,
                                 ITA_DEC_PLACES,
                                 ITA_SCRN_TEXT,
                                 ITA_VALIDATE_YN,
                                 ITA_VIEW_ATTRI,
                                 ITA_VIEW_COL_NAME,
                                 ITA_START_DATE,
                                 ITA_QUERYABLE,
                                 ITA_EXCLUSIVE,
                                 ITA_KEEP_HISTORY_YN,
                                 ITA_DATE_CREATED,
                                 ITA_DATE_MODIFIED,
                                 ITA_MODIFIED_BY,
                                 ITA_CREATED_BY,
                                 ITA_DISPLAYED,
                                 ITA_DISP_WIDTH,
                                 ITA_INSPECTABLE,
                                 ITA_CASE)
    SELECT  'DEF',
            'DEFECT_ID',
            'N',
            1,
            'N',
            'NUMBER',
            8,
            0,
            'Defect Id',
            'N',
            'DEFECT_ID',
            'DEFECT_ID',
            TO_DATE ('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
            'Y',
            'N',
            'N',
            TO_DATE ('07/02/2008 11:26:29', 'MM/DD/YYYY HH24:MI:SS'),
            TO_DATE ('10/07/2009 15:44:13', 'MM/DD/YYYY HH24:MI:SS'),
            'WORCS',
            'HIGHWAYS',
            'Y',
            8,
            'Y',
            'UPPER'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_INV_TYPE_ATTRIBS
                                        WHERE  ITA_ATTRIB_NAME = 'DEFECT_ID'
                                      );

INSERT INTO NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE,
                                 ITA_ATTRIB_NAME,
                                 ITA_DYNAMIC_ATTRIB,
                                 ITA_DISP_SEQ_NO,
                                 ITA_MANDATORY_YN,
                                 ITA_FORMAT,
                                 ITA_FLD_LENGTH,
                                 ITA_DEC_PLACES,
                                 ITA_SCRN_TEXT,
                                 ITA_VALIDATE_YN,
                                 ITA_VIEW_ATTRI,
                                 ITA_VIEW_COL_NAME,
                                 ITA_START_DATE,
                                 ITA_QUERYABLE,
                                 ITA_EXCLUSIVE,
                                 ITA_KEEP_HISTORY_YN,
                                 ITA_DATE_CREATED,
                                 ITA_DATE_MODIFIED,
                                 ITA_MODIFIED_BY,
                                 ITA_CREATED_BY,
                                 ITA_DISPLAYED,
                                 ITA_DISP_WIDTH,
                                 ITA_INSPECTABLE,
                                 ITA_CASE)
    SELECT 'DEF',
            'DEFECT_ROAD_ID',
            'N',
            2,
            'N',
            'NUMBER',
            8,
            0,
            ' Road Id',
            'N',
            'DEFECT_ROAD_ID',
            'DEFECT_ROAD_ID',
            TO_DATE ('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
            'Y',
            'N',
            'N',
            TO_DATE ('07/02/2008 11:26:29', 'MM/DD/YYYY HH24:MI:SS'),
            TO_DATE ('09/23/2009 10:10:27', 'MM/DD/YYYY HH24:MI:SS'),
            'WORCS',
            'HIGHWAYS',
            'Y',
            8,
            'Y',
            'UPPER'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_INV_TYPE_ATTRIBS
                                        WHERE  ITA_ATTRIB_NAME = 'DEFECT_ROAD_ID'
                                      );

INSERT INTO NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE,
                                 ITA_ATTRIB_NAME,
                                 ITA_DYNAMIC_ATTRIB,
                                 ITA_DISP_SEQ_NO,
                                 ITA_MANDATORY_YN,
                                 ITA_FORMAT,
                                 ITA_FLD_LENGTH,
                                 ITA_SCRN_TEXT,
                                 ITA_VALIDATE_YN,
                                 ITA_VIEW_ATTRI,
                                 ITA_VIEW_COL_NAME,
                                 ITA_START_DATE,
                                 ITA_QUERYABLE,
                                 ITA_EXCLUSIVE,
                                 ITA_KEEP_HISTORY_YN,
                                 ITA_DATE_CREATED,
                                 ITA_DATE_MODIFIED,
                                 ITA_MODIFIED_BY,
                                 ITA_CREATED_BY,
                                 ITA_DISPLAYED,
                                 ITA_DISP_WIDTH,
                                 ITA_INSPECTABLE,
                                 ITA_CASE)
    SELECT 'DEF',
            'DEFECT_ROAD_NAME',
            'N',
            3,
            'N',
            'VARCHAR2',
            30,
            ' Road Name',
            'N',
            'DEFECT_ROAD_NAME',
            'DEFECT_ROAD_NAME',
            TO_DATE ('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
            'Y',
            'N',
            'N',
            TO_DATE ('07/02/2008 11:26:29', 'MM/DD/YYYY HH24:MI:SS'),
            TO_DATE ('10/07/2009 16:35:24', 'MM/DD/YYYY HH24:MI:SS'),
            'WORCS',
            'HIGHWAYS',
            'Y',
            20,
            'Y',
            'MIXED'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_INV_TYPE_ATTRIBS
                                        WHERE  ITA_ATTRIB_NAME = 'DEFECT_ROAD_NAME'
                                      );

INSERT INTO NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE,
                                 ITA_ATTRIB_NAME,
                                 ITA_DYNAMIC_ATTRIB,
                                 ITA_DISP_SEQ_NO,
                                 ITA_MANDATORY_YN,
                                 ITA_FORMAT,
                                 ITA_FLD_LENGTH,
                                 ITA_SCRN_TEXT,
                                 ITA_VALIDATE_YN,
                                 ITA_VIEW_ATTRI,
                                 ITA_VIEW_COL_NAME,
                                 ITA_START_DATE,
                                 ITA_QUERYABLE,
                                 ITA_EXCLUSIVE,
                                 ITA_KEEP_HISTORY_YN,
                                 ITA_DATE_CREATED,
                                 ITA_DATE_MODIFIED,
                                 ITA_MODIFIED_BY,
                                 ITA_CREATED_BY,
                                 ITA_DISPLAYED,
                                 ITA_DISP_WIDTH,
                                 ITA_INSPECTABLE,
                                 ITA_CASE)
    SELECT  'DEF',
            'DEFECT_ROAD_DESCRIPTION',
            'N',
            4,
            'N',
            'VARCHAR2',
            240,
            'Section Description',
            'N',
            'DEFECT_ROAD_DESCRIPTION',
            'DEFECT_ROAD_DESCRIPTION',
            TO_DATE ('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
            'Y',
            'N',
            'N',
            TO_DATE ('07/02/2008 11:26:29', 'MM/DD/YYYY HH24:MI:SS'),
            TO_DATE ('09/23/2009 10:10:27', 'MM/DD/YYYY HH24:MI:SS'),
            'WORCS',
            'HIGHWAYS',
            'Y',
            20,
            'Y',
            'UPPER'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_INV_TYPE_ATTRIBS
                                        WHERE  ITA_ATTRIB_NAME = 'DEFECT_ROAD_DESCRIPTION'
                                      );

INSERT INTO NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE,
                                 ITA_ATTRIB_NAME,
                                 ITA_DYNAMIC_ATTRIB,
                                 ITA_DISP_SEQ_NO,
                                 ITA_MANDATORY_YN,
                                 ITA_FORMAT,
                                 ITA_FLD_LENGTH,
                                 ITA_DEC_PLACES,
                                 ITA_SCRN_TEXT,
                                 ITA_VALIDATE_YN,
                                 ITA_VIEW_ATTRI,
                                 ITA_VIEW_COL_NAME,
                                 ITA_START_DATE,
                                 ITA_QUERYABLE,
                                 ITA_EXCLUSIVE,
                                 ITA_KEEP_HISTORY_YN,
                                 ITA_DATE_CREATED,
                                 ITA_DATE_MODIFIED,
                                 ITA_MODIFIED_BY,
                                 ITA_CREATED_BY,
                                 ITA_DISPLAYED,
                                 ITA_DISP_WIDTH,
                                 ITA_INSPECTABLE,
                                 ITA_CASE)
    SELECT 'DEF',
            'DEFECT_START_CHAIN',
            'N',
            16,
            'N',
            'NUMBER',
            6,
            0,
            ' Start Chain',
            'N',
            'DEFECT_START_CHAIN',
            'DEFECT_START_CHAIN',
            TO_DATE ('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
            'N',
            'N',
            'N',
            TO_DATE ('07/02/2008 11:26:29', 'MM/DD/YYYY HH24:MI:SS'),
            TO_DATE ('09/23/2009 10:10:27', 'MM/DD/YYYY HH24:MI:SS'),
            'WORCS',
            'HIGHWAYS',
            'N',
            8,
            'Y',
            'UPPER'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_INV_TYPE_ATTRIBS
                                        WHERE  ITA_ATTRIB_NAME = 'DEFECT_START_CHAIN'
                                      );

INSERT INTO NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE,
                                 ITA_ATTRIB_NAME,
                                 ITA_DYNAMIC_ATTRIB,
                                 ITA_DISP_SEQ_NO,
                                 ITA_MANDATORY_YN,
                                 ITA_FORMAT,
                                 ITA_FLD_LENGTH,
                                 ITA_DEC_PLACES,
                                 ITA_SCRN_TEXT,
                                 ITA_VALIDATE_YN,
                                 ITA_VIEW_ATTRI,
                                 ITA_VIEW_COL_NAME,
                                 ITA_START_DATE,
                                 ITA_QUERYABLE,
                                 ITA_EXCLUSIVE,
                                 ITA_KEEP_HISTORY_YN,
                                 ITA_DATE_CREATED,
                                 ITA_DATE_MODIFIED,
                                 ITA_MODIFIED_BY,
                                 ITA_CREATED_BY,
                                 ITA_DISPLAYED,
                                 ITA_DISP_WIDTH,
                                 ITA_INSPECTABLE,
                                 ITA_CASE)
    SELECT 'DEF',
            'DEFECT_ARE_REPORT_ID',
            'N',
            16,
            'N',
            'NUMBER',
            8,
            0,
            ' Are Report Id',
            'N',
            'DEFECT_ARE_REPORT_ID',
            'DEFECT_ARE_REPORT_ID',
            TO_DATE ('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
            'N',
            'N',
            'N',
            TO_DATE ('07/02/2008 11:26:29', 'MM/DD/YYYY HH24:MI:SS'),
            TO_DATE ('09/23/2009 10:10:27', 'MM/DD/YYYY HH24:MI:SS'),
            'WORCS',
            'HIGHWAYS',
            'N',
            8,
            'Y',
            'UPPER'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_INV_TYPE_ATTRIBS
                                        WHERE  ITA_ATTRIB_NAME = 'DEFECT_ARE_REPORT_ID'
                                      );

INSERT INTO NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE,
                                 ITA_ATTRIB_NAME,
                                 ITA_DYNAMIC_ATTRIB,
                                 ITA_DISP_SEQ_NO,
                                 ITA_MANDATORY_YN,
                                 ITA_FORMAT,
                                 ITA_FLD_LENGTH,
                                 ITA_SCRN_TEXT,
                                 ITA_ID_DOMAIN,
                                 ITA_VALIDATE_YN,
                                 ITA_VIEW_ATTRI,
                                 ITA_VIEW_COL_NAME,
                                 ITA_START_DATE,
                                 ITA_QUERYABLE,
                                 ITA_EXCLUSIVE,
                                 ITA_KEEP_HISTORY_YN,
                                 ITA_DATE_CREATED,
                                 ITA_DATE_MODIFIED,
                                 ITA_MODIFIED_BY,
                                 ITA_CREATED_BY,
                                 ITA_DISPLAYED,
                                 ITA_DISP_WIDTH,
                                 ITA_INSPECTABLE,
                                 ITA_CASE)
    SELECT 'DEF',
            'DEFECT_SISS_ID',
            'N',
            16,
            'N',
            'VARCHAR2',
            3,
            ' Siss Id',
            'DEF_DEFECT_SISS_ID_DOM',
            'N',
            'DEFECT_SISS_ID',
            'DEFECT_SISS_ID',
            TO_DATE ('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
            'N',
            'N',
            'N',
            TO_DATE ('07/02/2008 11:26:29', 'MM/DD/YYYY HH24:MI:SS'),
            TO_DATE ('09/23/2009 10:10:27', 'MM/DD/YYYY HH24:MI:SS'),
            'WORCS',
            'HIGHWAYS',
            'N',
            20,
            'Y',
            'UPPER'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_INV_TYPE_ATTRIBS
                                        WHERE  ITA_ATTRIB_NAME = 'DEFECT_SISS_ID'
                                      );

INSERT INTO NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE,
                                 ITA_ATTRIB_NAME,
                                 ITA_DYNAMIC_ATTRIB,
                                 ITA_DISP_SEQ_NO,
                                 ITA_MANDATORY_YN,
                                 ITA_FORMAT,
                                 ITA_FLD_LENGTH,
                                 ITA_SCRN_TEXT,
                                 ITA_VALIDATE_YN,
                                 ITA_VIEW_ATTRI,
                                 ITA_VIEW_COL_NAME,
                                 ITA_START_DATE,
                                 ITA_QUERYABLE,
                                 ITA_EXCLUSIVE,
                                 ITA_KEEP_HISTORY_YN,
                                 ITA_DATE_CREATED,
                                 ITA_DATE_MODIFIED,
                                 ITA_MODIFIED_BY,
                                 ITA_CREATED_BY,
                                 ITA_DISPLAYED,
                                 ITA_DISP_WIDTH,
                                 ITA_INSPECTABLE,
                                 ITA_CASE)
    SELECT  'DEF',
            'DEFECT_WORKS_ORDER_NO',
            'N',
            8,
            'N',
            'VARCHAR2',
            16,
            ' Works Order No',
            'N',
            'DEFECT_WORKS_ORDER_NO',
            'DEFECT_WORKS_ORDER_NO',
            TO_DATE ('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
            'Y',
            'N',
            'N',
            TO_DATE ('07/02/2008 11:26:29', 'MM/DD/YYYY HH24:MI:SS'),
            TO_DATE ('09/23/2009 10:10:27', 'MM/DD/YYYY HH24:MI:SS'),
            'WORCS',
            'HIGHWAYS',
            'Y',
            20,
            'Y',
            'UPPER'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_INV_TYPE_ATTRIBS
                                        WHERE  ITA_ATTRIB_NAME = 'DEFECT_WORKS_ORDER_NO'
                                      );
            
INSERT INTO NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE,
                                 ITA_ATTRIB_NAME,
                                 ITA_DYNAMIC_ATTRIB,
                                 ITA_DISP_SEQ_NO,
                                 ITA_MANDATORY_YN,
                                 ITA_FORMAT,
                                 ITA_FLD_LENGTH,
                                 ITA_SCRN_TEXT,
                                 ITA_VALIDATE_YN,
                                 ITA_VIEW_ATTRI,
                                 ITA_VIEW_COL_NAME,
                                 ITA_START_DATE,
                                 ITA_QUERYABLE,
                                 ITA_EXCLUSIVE,
                                 ITA_KEEP_HISTORY_YN,
                                 ITA_DATE_CREATED,
                                 ITA_DATE_MODIFIED,
                                 ITA_MODIFIED_BY,
                                 ITA_CREATED_BY,
                                 ITA_DISPLAYED,
                                 ITA_DISP_WIDTH,
                                 ITA_INSPECTABLE,
                                 ITA_CASE)
    SELECT  'DEF',
            'DEFECT_CREATED_DATE',
            'N',
            9,
            'N',
            'DATE',
            8,
            ' Created Date',
            'N',
            'DEFECT_CREATED_DATE',
            'DEFECT_CREATED_DATE',
            TO_DATE ('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
            'Y',
            'N',
            'N',
            TO_DATE ('07/02/2008 11:26:29', 'MM/DD/YYYY HH24:MI:SS'),
            TO_DATE ('09/23/2009 10:10:27', 'MM/DD/YYYY HH24:MI:SS'),
            'WORCS',
            'HIGHWAYS',
            'Y',
            11,
            'Y',
            'UPPER'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_INV_TYPE_ATTRIBS
                                        WHERE  ITA_ATTRIB_NAME = 'DEFECT_CREATED_DATE'
                                      );

INSERT INTO NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE,
                                 ITA_ATTRIB_NAME,
                                 ITA_DYNAMIC_ATTRIB,
                                 ITA_DISP_SEQ_NO,
                                 ITA_MANDATORY_YN,
                                 ITA_FORMAT,
                                 ITA_FLD_LENGTH,
                                 ITA_SCRN_TEXT,
                                 ITA_VALIDATE_YN,
                                 ITA_VIEW_ATTRI,
                                 ITA_VIEW_COL_NAME,
                                 ITA_START_DATE,
                                 ITA_QUERYABLE,
                                 ITA_EXCLUSIVE,
                                 ITA_KEEP_HISTORY_YN,
                                 ITA_DATE_CREATED,
                                 ITA_DATE_MODIFIED,
                                 ITA_MODIFIED_BY,
                                 ITA_CREATED_BY,
                                 ITA_DISPLAYED,
                                 ITA_DISP_WIDTH,
                                 ITA_INSPECTABLE,
                                 ITA_CASE)
    SELECT 'DEF',
            'DEFECT_INSPECTED_DATE',
            'N',
            10,
            'N',
            'DATE',
            7,
            ' Inspected Date',
            'N',
            'DEFECT_INSPECTED_DATE',
            'DEFECT_INSPECTED_DATE',
            TO_DATE ('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
            'Y',
            'N',
            'N',
            TO_DATE ('07/02/2008 11:26:29', 'MM/DD/YYYY HH24:MI:SS'),
            TO_DATE ('09/23/2009 10:10:27', 'MM/DD/YYYY HH24:MI:SS'),
            'WORCS',
            'HIGHWAYS',
            'Y',
            11,
            'Y',
            'UPPER'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_INV_TYPE_ATTRIBS
                                        WHERE  ITA_ATTRIB_NAME = 'DEFECT_INSPECTED_DATE'
                                      );

INSERT INTO NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE,
                                 ITA_ATTRIB_NAME,
                                 ITA_DYNAMIC_ATTRIB,
                                 ITA_DISP_SEQ_NO,
                                 ITA_MANDATORY_YN,
                                 ITA_FORMAT,
                                 ITA_FLD_LENGTH,
                                 ITA_SCRN_TEXT,
                                 ITA_VALIDATE_YN,
                                 ITA_VIEW_ATTRI,
                                 ITA_VIEW_COL_NAME,
                                 ITA_START_DATE,
                                 ITA_QUERYABLE,
                                 ITA_EXCLUSIVE,
                                 ITA_KEEP_HISTORY_YN,
                                 ITA_DATE_CREATED,
                                 ITA_DATE_MODIFIED,
                                 ITA_MODIFIED_BY,
                                 ITA_CREATED_BY,
                                 ITA_DISPLAYED,
                                 ITA_DISP_WIDTH,
                                 ITA_INSPECTABLE,
                                 ITA_CASE)
    SELECT  'DEF',
            'DEFECT_INSPECTED_TIME',
            'N',
            11,
            'N',
            'VARCHAR2',
            81,
            ' Inspected Time',
            'N',
            'DEFECT_INSPECTED_TIME',
            'DEFECT_INSPECTED_TIME',
            TO_DATE ('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
            'Y',
            'N',
            'N',
            TO_DATE ('07/02/2008 11:26:29', 'MM/DD/YYYY HH24:MI:SS'),
            TO_DATE ('09/23/2009 10:10:27', 'MM/DD/YYYY HH24:MI:SS'),
            'WORCS',
            'HIGHWAYS',
            'Y',
            20,
            'Y',
            'UPPER'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_INV_TYPE_ATTRIBS
                                        WHERE  ITA_ATTRIB_NAME = 'DEFECT_INSPECTED_TIME'
                                      );

INSERT INTO NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE,
                                 ITA_ATTRIB_NAME,
                                 ITA_DYNAMIC_ATTRIB,
                                 ITA_DISP_SEQ_NO,
                                 ITA_MANDATORY_YN,
                                 ITA_FORMAT,
                                 ITA_FLD_LENGTH,
                                 ITA_SCRN_TEXT,
                                 ITA_VALIDATE_YN,
                                 ITA_VIEW_ATTRI,
                                 ITA_VIEW_COL_NAME,
                                 ITA_START_DATE,
                                 ITA_QUERYABLE,
                                 ITA_EXCLUSIVE,
                                 ITA_KEEP_HISTORY_YN,
                                 ITA_DATE_CREATED,
                                 ITA_DATE_MODIFIED,
                                 ITA_MODIFIED_BY,
                                 ITA_CREATED_BY,
                                 ITA_DISPLAYED,
                                 ITA_DISP_WIDTH,
                                 ITA_INSPECTABLE,
                                 ITA_CASE)
    SELECT  'DEF',
            'DEFECT_CODE',
            'N',
            5,
            'N',
            'VARCHAR2',
            4,
            'Defect Type',
            'N',
            'DEFECT_CODE',
            'DEFECT_CODE',
            TO_DATE ('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
            'Y',
            'N',
            'N',
            TO_DATE ('07/02/2008 11:26:29', 'MM/DD/YYYY HH24:MI:SS'),
            TO_DATE ('09/23/2009 10:10:27', 'MM/DD/YYYY HH24:MI:SS'),
            'WORCS',
            'HIGHWAYS',
            'Y',
            20,
            'Y',
            'UPPER'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_INV_TYPE_ATTRIBS
                                        WHERE  ITA_ATTRIB_NAME = 'DEFECT_CODE'
                                      );

INSERT INTO NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE,
                                 ITA_ATTRIB_NAME,
                                 ITA_DYNAMIC_ATTRIB,
                                 ITA_DISP_SEQ_NO,
                                 ITA_MANDATORY_YN,
                                 ITA_FORMAT,
                                 ITA_FLD_LENGTH,
                                 ITA_SCRN_TEXT,
                                 ITA_ID_DOMAIN,
                                 ITA_VALIDATE_YN,
                                 ITA_VIEW_ATTRI,
                                 ITA_VIEW_COL_NAME,
                                 ITA_START_DATE,
                                 ITA_QUERYABLE,
                                 ITA_EXCLUSIVE,
                                 ITA_KEEP_HISTORY_YN,
                                 ITA_DATE_CREATED,
                                 ITA_DATE_MODIFIED,
                                 ITA_MODIFIED_BY,
                                 ITA_CREATED_BY,
                                 ITA_DISPLAYED,
                                 ITA_DISP_WIDTH,
                                 ITA_INSPECTABLE,
                                 ITA_CASE)
     SELECT 'DEF',
            'DEFECT_PRIORITY',
            'N',
            6,
            'N',
            'VARCHAR2',
            4,
            ' Priority',
            'DEF_DEFECT_PRIORITY_DOM',
            'N',
            'DEFECT_PRIORITY',
            'DEFECT_PRIORITY',
            TO_DATE ('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
            'Y',
            'N',
            'N',
            TO_DATE ('07/02/2008 11:26:29', 'MM/DD/YYYY HH24:MI:SS'),
            TO_DATE ('09/23/2009 10:10:27', 'MM/DD/YYYY HH24:MI:SS'),
            'WORCS',
            'HIGHWAYS',
            'Y',
            20,
            'Y',
            'UPPER'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_INV_TYPE_ATTRIBS
                                        WHERE  ITA_ATTRIB_NAME = 'DEFECT_PRIORITY'
                                      );

INSERT INTO NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE,
                                 ITA_ATTRIB_NAME,
                                 ITA_DYNAMIC_ATTRIB,
                                 ITA_DISP_SEQ_NO,
                                 ITA_MANDATORY_YN,
                                 ITA_FORMAT,
                                 ITA_FLD_LENGTH,
                                 ITA_SCRN_TEXT,
                                 ITA_ID_DOMAIN,
                                 ITA_VALIDATE_YN,
                                 ITA_VIEW_ATTRI,
                                 ITA_VIEW_COL_NAME,
                                 ITA_START_DATE,
                                 ITA_QUERYABLE,
                                 ITA_EXCLUSIVE,
                                 ITA_KEEP_HISTORY_YN,
                                 ITA_DATE_CREATED,
                                 ITA_DATE_MODIFIED,
                                 ITA_MODIFIED_BY,
                                 ITA_CREATED_BY,
                                 ITA_DISPLAYED,
                                 ITA_DISP_WIDTH,
                                 ITA_INSPECTABLE,
                                 ITA_CASE)
  SELECT    'DEF',
            'DEFECT_STATUS_CODE',
            'N',
            7,
            'N',
            'VARCHAR2',
            10,
            ' Status',
            'DEF_DEFECT_STATUS_CODE',
            'N',
            'DEFECT_STATUS_CODE',
            'DEFECT_STATUS_CODE',
            TO_DATE ('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
            'Y',
            'N',
            'N',
            TO_DATE ('07/02/2008 11:26:29', 'MM/DD/YYYY HH24:MI:SS'),
            TO_DATE ('09/23/2009 10:10:27', 'MM/DD/YYYY HH24:MI:SS'),
            'WORCS',
            'HIGHWAYS',
            'Y',
            20,
            'Y',
            'UPPER'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_INV_TYPE_ATTRIBS
                                        WHERE  ITA_ATTRIB_NAME = 'DEFECT_STATUS_CODE'
                                      );

INSERT INTO NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE,
                                 ITA_ATTRIB_NAME,
                                 ITA_DYNAMIC_ATTRIB,
                                 ITA_DISP_SEQ_NO,
                                 ITA_MANDATORY_YN,
                                 ITA_FORMAT,
                                 ITA_FLD_LENGTH,
                                 ITA_SCRN_TEXT,
                                 ITA_ID_DOMAIN,
                                 ITA_VALIDATE_YN,
                                 ITA_VIEW_ATTRI,
                                 ITA_VIEW_COL_NAME,
                                 ITA_START_DATE,
                                 ITA_QUERYABLE,
                                 ITA_EXCLUSIVE,
                                 ITA_KEEP_HISTORY_YN,
                                 ITA_DATE_CREATED,
                                 ITA_DATE_MODIFIED,
                                 ITA_MODIFIED_BY,
                                 ITA_CREATED_BY,
                                 ITA_DISPLAYED,
                                 ITA_DISP_WIDTH,
                                 ITA_INSPECTABLE,
                                 ITA_CASE)
    SELECT  'DEF',
            'DEFECT_ACTIVITY',
            'N',
            15,
            'N',
            'VARCHAR2',
            2,
            ' Activity',
            'DEF_DEFECT_ACTIVITY_DOM',
            'N',
            'DEFECT_ACTIVITY',
            'DEFECT_ACTIVITY',
            TO_DATE ('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
            'Y',
            'N',
            'N',
            TO_DATE ('07/02/2008 11:26:29', 'MM/DD/YYYY HH24:MI:SS'),
            TO_DATE ('09/23/2009 10:10:27', 'MM/DD/YYYY HH24:MI:SS'),
            'WORCS',
            'HIGHWAYS',
            'Y',
            20,
            'Y',
            'UPPER'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_INV_TYPE_ATTRIBS
                                        WHERE  ITA_ATTRIB_NAME = 'DEFECT_ACTIVITY'
                                      );

INSERT INTO NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE,
                                 ITA_ATTRIB_NAME,
                                 ITA_DYNAMIC_ATTRIB,
                                 ITA_DISP_SEQ_NO,
                                 ITA_MANDATORY_YN,
                                 ITA_FORMAT,
                                 ITA_FLD_LENGTH,
                                 ITA_SCRN_TEXT,
                                 ITA_VALIDATE_YN,
                                 ITA_VIEW_ATTRI,
                                 ITA_VIEW_COL_NAME,
                                 ITA_START_DATE,
                                 ITA_QUERYABLE,
                                 ITA_EXCLUSIVE,
                                 ITA_KEEP_HISTORY_YN,
                                 ITA_DATE_CREATED,
                                 ITA_DATE_MODIFIED,
                                 ITA_MODIFIED_BY,
                                 ITA_CREATED_BY,
                                 ITA_DISPLAYED,
                                 ITA_DISP_WIDTH,
                                 ITA_INSPECTABLE,
                                 ITA_CASE)
    SELECT  'DEF',
            'DEFECT_LOCATION',
            'N',
            16,
            'N',
            'VARCHAR2',
            40,
            ' Location',
            'N',
            'DEFECT_LOCATION',
            'DEFECT_LOCATION',
            TO_DATE ('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
            'Y',
            'N',
            'N',
            TO_DATE ('07/02/2008 11:26:29', 'MM/DD/YYYY HH24:MI:SS'),
            TO_DATE ('10/15/2009 08:34:25', 'MM/DD/YYYY HH24:MI:SS'),
            'WORCS',
            'HIGHWAYS',
            'Y',
            20,
            'Y',
            'UPPER'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_INV_TYPE_ATTRIBS
                                        WHERE  ITA_ATTRIB_NAME = 'DEFECT_LOCATION'
                                      );

INSERT INTO NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE,
                                 ITA_ATTRIB_NAME,
                                 ITA_DYNAMIC_ATTRIB,
                                 ITA_DISP_SEQ_NO,
                                 ITA_MANDATORY_YN,
                                 ITA_FORMAT,
                                 ITA_FLD_LENGTH,
                                 ITA_SCRN_TEXT,
                                 ITA_VALIDATE_YN,
                                 ITA_VIEW_ATTRI,
                                 ITA_VIEW_COL_NAME,
                                 ITA_START_DATE,
                                 ITA_QUERYABLE,
                                 ITA_EXCLUSIVE,
                                 ITA_KEEP_HISTORY_YN,
                                 ITA_DATE_CREATED,
                                 ITA_DATE_MODIFIED,
                                 ITA_MODIFIED_BY,
                                 ITA_CREATED_BY,
                                 ITA_DISPLAYED,
                                 ITA_DISP_WIDTH,
                                 ITA_INSPECTABLE,
                                 ITA_CASE)
    SELECT  'DEF',
            'DEFECT_DESCRIPTION',
            'N',
            17,
            'N',
            'VARCHAR2',
            240,
            ' Description',
            'N',
            'DEFECT_DESCRIPTION',
            'DEFECT_DESCRIPTION',
            TO_DATE ('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
            'Y',
            'N',
            'N',
            TO_DATE ('07/02/2008 11:26:29', 'MM/DD/YYYY HH24:MI:SS'),
            TO_DATE ('09/23/2009 10:10:27', 'MM/DD/YYYY HH24:MI:SS'),
            'WORCS',
            'HIGHWAYS',
            'Y',
            20,
            'Y',
            'UPPER'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_INV_TYPE_ATTRIBS
                                        WHERE  ITA_ATTRIB_NAME = 'DEFECT_DESCRIPTION'
                                      );

INSERT INTO NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE,
                                 ITA_ATTRIB_NAME,
                                 ITA_DYNAMIC_ATTRIB,
                                 ITA_DISP_SEQ_NO,
                                 ITA_MANDATORY_YN,
                                 ITA_FORMAT,
                                 ITA_FLD_LENGTH,
                                 ITA_SCRN_TEXT,
                                 ITA_ID_DOMAIN,
                                 ITA_VALIDATE_YN,
                                 ITA_VIEW_ATTRI,
                                 ITA_VIEW_COL_NAME,
                                 ITA_START_DATE,
                                 ITA_QUERYABLE,
                                 ITA_EXCLUSIVE,
                                 ITA_KEEP_HISTORY_YN,
                                 ITA_DATE_CREATED,
                                 ITA_DATE_MODIFIED,
                                 ITA_MODIFIED_BY,
                                 ITA_CREATED_BY,
                                 ITA_DISPLAYED,
                                 ITA_DISP_WIDTH,
                                 ITA_INSPECTABLE,
                                 ITA_CASE)
    SELECT  'DEF',
            'DEFECT_ASSET_TYPE',
            'N',
            18,
            'N',
            'VARCHAR2',
            2,
            ' Asset Type',
            'DEF_DEFECT_ASSET_TYPE_DOM',
            'N',
            'DEFECT_ASSET_TYPE',
            'DEFECT_ASSET_TYPE',
            TO_DATE ('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
            'Y',
            'N',
            'N',
            TO_DATE ('07/02/2008 11:26:29', 'MM/DD/YYYY HH24:MI:SS'),
            TO_DATE ('09/23/2009 10:10:27', 'MM/DD/YYYY HH24:MI:SS'),
            'WORCS',
            'HIGHWAYS',
            'Y',
            20,
            'Y',
            'UPPER'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_INV_TYPE_ATTRIBS
                                        WHERE  ITA_ATTRIB_NAME = 'DEFECT_ASSET_TYPE'
                                      );

INSERT INTO NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE,
                                 ITA_ATTRIB_NAME,
                                 ITA_DYNAMIC_ATTRIB,
                                 ITA_DISP_SEQ_NO,
                                 ITA_MANDATORY_YN,
                                 ITA_FORMAT,
                                 ITA_FLD_LENGTH,
                                 ITA_DEC_PLACES,
                                 ITA_SCRN_TEXT,
                                 ITA_VALIDATE_YN,
                                 ITA_VIEW_ATTRI,
                                 ITA_VIEW_COL_NAME,
                                 ITA_START_DATE,
                                 ITA_QUERYABLE,
                                 ITA_EXCLUSIVE,
                                 ITA_KEEP_HISTORY_YN,
                                 ITA_DATE_CREATED,
                                 ITA_DATE_MODIFIED,
                                 ITA_MODIFIED_BY,
                                 ITA_CREATED_BY,
                                 ITA_DISPLAYED,
                                 ITA_DISP_WIDTH,
                                 ITA_INSPECTABLE,
                                 ITA_CASE)
    SELECT  'DEF',
            'DEFECT_ASSET_ID',
            'N',
            19,
            'N',
            'NUMBER',
            8,
            0,
            ' Asset Id',
            'N',
            'DEFECT_ASSET_ID',
            'DEFECT_ASSET_ID',
            TO_DATE ('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
            'Y',
            'N',
            'N',
            TO_DATE ('07/02/2008 11:26:29', 'MM/DD/YYYY HH24:MI:SS'),
            TO_DATE ('09/23/2009 10:10:27', 'MM/DD/YYYY HH24:MI:SS'),
            'WORCS',
            'HIGHWAYS',
            'Y',
            8,
            'Y',
            'UPPER'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_INV_TYPE_ATTRIBS
                                        WHERE  ITA_ATTRIB_NAME = 'DEFECT_ASSET_ID'
                                      );

INSERT INTO NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE,
                                 ITA_ATTRIB_NAME,
                                 ITA_DYNAMIC_ATTRIB,
                                 ITA_DISP_SEQ_NO,
                                 ITA_MANDATORY_YN,
                                 ITA_FORMAT,
                                 ITA_FLD_LENGTH,
                                 ITA_SCRN_TEXT,
                                 ITA_ID_DOMAIN,
                                 ITA_VALIDATE_YN,
                                 ITA_VIEW_ATTRI,
                                 ITA_VIEW_COL_NAME,
                                 ITA_START_DATE,
                                 ITA_QUERYABLE,
                                 ITA_EXCLUSIVE,
                                 ITA_KEEP_HISTORY_YN,
                                 ITA_DATE_CREATED,
                                 ITA_DATE_MODIFIED,
                                 ITA_MODIFIED_BY,
                                 ITA_CREATED_BY,
                                 ITA_DISPLAYED,
                                 ITA_DISP_WIDTH,
                                 ITA_INSPECTABLE,
                                 ITA_CASE)
    SELECT  'DEF',
            'DEFECT_INITIATION_TYPE',
            'N',
            20,
            'N',
            'VARCHAR2',
            3,
            ' Initiation Type',
            'DEF_DEFECT_INIT_TYPE_DOM',
            'N',
            'DEFECT_INITIATION_TYPE',
            'DEFECT_INITIATION_TYPE',
            TO_DATE ('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
            'Y',
            'N',
            'N',
            TO_DATE ('07/02/2008 11:26:29', 'MM/DD/YYYY HH24:MI:SS'),
            TO_DATE ('09/23/2009 10:10:27', 'MM/DD/YYYY HH24:MI:SS'),
            'WORCS',
            'HIGHWAYS',
            'Y',
            20,
            'Y',
            'UPPER'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_INV_TYPE_ATTRIBS
                                        WHERE  ITA_ATTRIB_NAME = 'DEFECT_INITIATION_TYPE'
                                      );

INSERT INTO NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE,
                                 ITA_ATTRIB_NAME,
                                 ITA_DYNAMIC_ATTRIB,
                                 ITA_DISP_SEQ_NO,
                                 ITA_MANDATORY_YN,
                                 ITA_FORMAT,
                                 ITA_FLD_LENGTH,
                                 ITA_SCRN_TEXT,
                                 ITA_ID_DOMAIN,
                                 ITA_VALIDATE_YN,
                                 ITA_VIEW_ATTRI,
                                 ITA_VIEW_COL_NAME,
                                 ITA_START_DATE,
                                 ITA_QUERYABLE,
                                 ITA_EXCLUSIVE,
                                 ITA_KEEP_HISTORY_YN,
                                 ITA_DATE_CREATED,
                                 ITA_DATE_MODIFIED,
                                 ITA_MODIFIED_BY,
                                 ITA_CREATED_BY,
                                 ITA_DISPLAYED,
                                 ITA_DISP_WIDTH,
                                 ITA_INSPECTABLE,
                                 ITA_CASE)
    SELECT  'DEF',
            'DEFECT_INSPECTOR',
            'N',
            21,
            'N',
            'VARCHAR2',
            30,
            ' Inspector',
            'DEF_DEFECT_INSPECTOR_DOM',
            'N',
            'DEFECT_INSPECTOR',
            'DEFECT_INSPECTOR',
            TO_DATE ('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
            'Y',
            'N',
            'N',
            TO_DATE ('07/02/2008 11:26:29', 'MM/DD/YYYY HH24:MI:SS'),
            TO_DATE ('09/23/2009 10:10:27', 'MM/DD/YYYY HH24:MI:SS'),
            'WORCS',
            'HIGHWAYS',
            'Y',
            20,
            'Y',
            'UPPER'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_INV_TYPE_ATTRIBS
                                        WHERE  ITA_ATTRIB_NAME = 'DEFECT_INSPECTOR'
                                      );

INSERT INTO NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE,
                                 ITA_ATTRIB_NAME,
                                 ITA_DYNAMIC_ATTRIB,
                                 ITA_DISP_SEQ_NO,
                                 ITA_MANDATORY_YN,
                                 ITA_FORMAT,
                                 ITA_FLD_LENGTH,
                                 ITA_SCRN_TEXT,
                                 ITA_VALIDATE_YN,
                                 ITA_VIEW_ATTRI,
                                 ITA_VIEW_COL_NAME,
                                 ITA_START_DATE,
                                 ITA_QUERYABLE,
                                 ITA_EXCLUSIVE,
                                 ITA_KEEP_HISTORY_YN,
                                 ITA_DATE_CREATED,
                                 ITA_DATE_MODIFIED,
                                 ITA_MODIFIED_BY,
                                 ITA_CREATED_BY,
                                 ITA_DISPLAYED,
                                 ITA_DISP_WIDTH,
                                 ITA_INSPECTABLE,
                                 ITA_CASE)
    SELECT  'DEF',
            'DEFECT_X_SECTION',
            'N',
            22,
            'N',
            'VARCHAR2',
            1,
            ' X Section',
            'N',
            'DEFECT_X_SECTION',
            'DEFECT_X_SECTION',
            TO_DATE ('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
            'Y',
            'N',
            'N',
            TO_DATE ('07/02/2008 11:26:29', 'MM/DD/YYYY HH24:MI:SS'),
            TO_DATE ('09/23/2009 10:10:27', 'MM/DD/YYYY HH24:MI:SS'),
            'WORCS',
            'HIGHWAYS',
            'Y',
            20,
            'Y',
            'UPPER'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_INV_TYPE_ATTRIBS
                                        WHERE  ITA_ATTRIB_NAME = 'DEFECT_X_SECTION'
                                      );

INSERT INTO NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE,
                                 ITA_ATTRIB_NAME,
                                 ITA_DYNAMIC_ATTRIB,
                                 ITA_DISP_SEQ_NO,
                                 ITA_MANDATORY_YN,
                                 ITA_FORMAT,
                                 ITA_FLD_LENGTH,
                                 ITA_SCRN_TEXT,
                                 ITA_ID_DOMAIN,
                                 ITA_VALIDATE_YN,
                                 ITA_VIEW_ATTRI,
                                 ITA_VIEW_COL_NAME,
                                 ITA_START_DATE,
                                 ITA_QUERYABLE,
                                 ITA_EXCLUSIVE,
                                 ITA_KEEP_HISTORY_YN,
                                 ITA_DATE_CREATED,
                                 ITA_DATE_MODIFIED,
                                 ITA_MODIFIED_BY,
                                 ITA_CREATED_BY,
                                 ITA_DISPLAYED,
                                 ITA_DISP_WIDTH,
                                 ITA_INSPECTABLE,
                                 ITA_CASE)
    SELECT  'DEF',
            'DEFECT_NOTIFY_ORG',
            'N',
            23,
            'N',
            'VARCHAR2',
            40,
            ' Notify Org',
            'DEF_DEFECT_NOTIFY_DOM',
            'N',
            'DEFECT_NOTIFY_ORG',
            'DEFECT_NOTIFY_ORG',
            TO_DATE ('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
            'Y',
            'N',
            'N',
            TO_DATE ('07/02/2008 11:26:29', 'MM/DD/YYYY HH24:MI:SS'),
            TO_DATE ('09/23/2009 10:10:27', 'MM/DD/YYYY HH24:MI:SS'),
            'WORCS',
            'HIGHWAYS',
            'Y',
            20,
            'Y',
            'UPPER'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_INV_TYPE_ATTRIBS
                                        WHERE  ITA_ATTRIB_NAME = 'DEFECT_NOTIFY_ORG'
                                      );

INSERT INTO NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE,
                                 ITA_ATTRIB_NAME,
                                 ITA_DYNAMIC_ATTRIB,
                                 ITA_DISP_SEQ_NO,
                                 ITA_MANDATORY_YN,
                                 ITA_FORMAT,
                                 ITA_FLD_LENGTH,
                                 ITA_SCRN_TEXT,
                                 ITA_ID_DOMAIN,
                                 ITA_VALIDATE_YN,
                                 ITA_VIEW_ATTRI,
                                 ITA_VIEW_COL_NAME,
                                 ITA_START_DATE,
                                 ITA_QUERYABLE,
                                 ITA_EXCLUSIVE,
                                 ITA_KEEP_HISTORY_YN,
                                 ITA_DATE_CREATED,
                                 ITA_DATE_MODIFIED,
                                 ITA_MODIFIED_BY,
                                 ITA_CREATED_BY,
                                 ITA_DISPLAYED,
                                 ITA_DISP_WIDTH,
                                 ITA_INSPECTABLE,
                                 ITA_CASE)
    SELECT  'DEF',
            'DEFECT_RECHARGE_ORG',
            'N',
            24,
            'N',
            'VARCHAR2',
            40,
            ' Recharge Org',
            'DEF_DEFECT_RECHARGE_DOM',
            'N',
            'DEFECT_RECHARGE_ORG',
            'DEFECT_RECHARGE_ORG',
            TO_DATE ('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
            'Y',
            'N',
            'N',
            TO_DATE ('07/02/2008 11:26:29', 'MM/DD/YYYY HH24:MI:SS'),
            TO_DATE ('09/23/2009 10:10:27', 'MM/DD/YYYY HH24:MI:SS'),
            'WORCS',
            'HIGHWAYS',
            'Y',
            20,
            'Y',
            'UPPER'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_INV_TYPE_ATTRIBS
                                        WHERE  ITA_ATTRIB_NAME = 'DEFECT_RECHARGE_ORG'
                                      );

INSERT INTO NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE,
                                 ITA_ATTRIB_NAME,
                                 ITA_DYNAMIC_ATTRIB,
                                 ITA_DISP_SEQ_NO,
                                 ITA_MANDATORY_YN,
                                 ITA_FORMAT,
                                 ITA_FLD_LENGTH,
                                 ITA_DEC_PLACES,
                                 ITA_SCRN_TEXT,
                                 ITA_VALIDATE_YN,
                                 ITA_VIEW_ATTRI,
                                 ITA_VIEW_COL_NAME,
                                 ITA_START_DATE,
                                 ITA_QUERYABLE,
                                 ITA_EXCLUSIVE,
                                 ITA_KEEP_HISTORY_YN,
                                 ITA_DATE_CREATED,
                                 ITA_DATE_MODIFIED,
                                 ITA_MODIFIED_BY,
                                 ITA_CREATED_BY,
                                 ITA_DISPLAYED,
                                 ITA_DISP_WIDTH,
                                 ITA_INSPECTABLE,
                                 ITA_CASE)
    SELECT  'DEF',
            'DEFECT_TMA_CODE',
            'N',
            25,
            'N',
            'VARCHAR2',
            16,
            0,
            'Defect TMA Code',
            'N',
            'DEFECT_TMA_CODE',
            'DEFECT_TMA_CODE',
            TO_DATE ('01/01/1900 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
            'Y',
            'N',
            'N',
            TO_DATE ('11/06/2009 11:46:48', 'MM/DD/YYYY HH24:MI:SS'),
            TO_DATE ('11/09/2009 16:54:07', 'MM/DD/YYYY HH24:MI:SS'),
            'WORCS',
            'WORCS',
            'Y',
            16,
            'Y',
            'UPPER'
            FROM dual
            WHERE NOT EXISTS( Select 1
                                        FROM   NM_INV_TYPE_ATTRIBS
                                        WHERE  ITA_ATTRIB_NAME = 'DEFECT_TMA_CODE'
                                      );

COMMIT;

