
DECLARE
   name_array dbms_sql.varchar2_table;
   i_count  number;
BEGIN
   name_array(1) := 'xnm_inv_items_all';   
 
   --
   FOR i IN name_array.FIRST .. name_array.LAST
   LOOP
	select count(*) into i_count from user_objects where object_name = upper(name_array(i)) and object_type = 'TABLE';
		if i_count = 1 then
			execute immediate 'drop table ' || name_array(i);
		end if;
	select count(*) into i_count from user_objects where object_name = upper(name_array(i)) and object_type = 'VIEW';
		if i_count = 1 then
			execute immediate 'drop view ' || name_array(i);	
		end if;
	select count(*) into i_count from user_objects where object_name = upper(name_array(i)) and object_type = 'SEQUENCE';
		if i_count = 1 then
			execute immediate 'drop sequence ' || name_array(i);	
		end if;
   END LOOP;
END;
/

CREATE TABLE xNM_INV_ITEMS_ALL
(
  IIT_NE_ID                  NUMBER(9) ,         
  IIT_INV_TYPE               VARCHAR2(4 BYTE) ,  
  IIT_PRIMARY_KEY            VARCHAR2(50 BYTE)  ,
  IIT_START_DATE             DATE          ,     
  IIT_DATE_CREATED           DATE       ,        
  IIT_DATE_MODIFIED          DATE            ,   
  IIT_CREATED_BY             VARCHAR2(30 BYTE)  ,
  IIT_MODIFIED_BY            VARCHAR2(30 BYTE)  ,
  IIT_ADMIN_UNIT             NUMBER(9)         , 
  IIT_DESCR                  VARCHAR2(40 BYTE),
  IIT_END_DATE               DATE,
  IIT_FOREIGN_KEY            VARCHAR2(50 BYTE),
  IIT_LOCATED_BY             NUMBER(9),
  IIT_POSITION               NUMBER,
  IIT_X_COORD                NUMBER,
  IIT_Y_COORD                NUMBER,
  IIT_NUM_ATTRIB16           NUMBER,
  IIT_NUM_ATTRIB17           NUMBER,
  IIT_NUM_ATTRIB18           NUMBER,
  IIT_NUM_ATTRIB19           NUMBER,
  IIT_NUM_ATTRIB20           NUMBER,
  IIT_NUM_ATTRIB21           NUMBER,
  IIT_NUM_ATTRIB22           NUMBER,
  IIT_NUM_ATTRIB23           NUMBER,
  IIT_NUM_ATTRIB24           NUMBER,
  IIT_NUM_ATTRIB25           NUMBER,
  IIT_CHR_ATTRIB26           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB27           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB28           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB29           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB30           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB31           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB32           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB33           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB34           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB35           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB36           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB37           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB38           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB39           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB40           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB41           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB42           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB43           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB44           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB45           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB46           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB47           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB48           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB49           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB50           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB51           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB52           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB53           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB54           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB55           VARCHAR2(50 BYTE),
  IIT_CHR_ATTRIB56           VARCHAR2(200 BYTE),
  IIT_CHR_ATTRIB57           VARCHAR2(200 BYTE),
  IIT_CHR_ATTRIB58           VARCHAR2(200 BYTE),
  IIT_CHR_ATTRIB59           VARCHAR2(200 BYTE),
  IIT_CHR_ATTRIB60           VARCHAR2(200 BYTE),
  IIT_CHR_ATTRIB61           VARCHAR2(200 BYTE),
  IIT_CHR_ATTRIB62           VARCHAR2(200 BYTE),
  IIT_CHR_ATTRIB63           VARCHAR2(200 BYTE),
  IIT_CHR_ATTRIB64           VARCHAR2(200 BYTE),
  IIT_CHR_ATTRIB65           VARCHAR2(200 BYTE),
  IIT_CHR_ATTRIB66           VARCHAR2(500 BYTE),
  IIT_CHR_ATTRIB67           VARCHAR2(500 BYTE),
  IIT_CHR_ATTRIB68           VARCHAR2(500 BYTE),
  IIT_CHR_ATTRIB69           VARCHAR2(500 BYTE),
  IIT_CHR_ATTRIB70           VARCHAR2(500 BYTE),
  IIT_CHR_ATTRIB71           VARCHAR2(500 BYTE),
  IIT_CHR_ATTRIB72           VARCHAR2(500 BYTE),
  IIT_CHR_ATTRIB73           VARCHAR2(500 BYTE),
  IIT_CHR_ATTRIB74           VARCHAR2(500 BYTE),
  IIT_CHR_ATTRIB75           VARCHAR2(500 BYTE),
  IIT_NUM_ATTRIB76           NUMBER,
  IIT_NUM_ATTRIB77           NUMBER,
  IIT_NUM_ATTRIB78           NUMBER,
  IIT_NUM_ATTRIB79           NUMBER,
  IIT_NUM_ATTRIB80           NUMBER,
  IIT_NUM_ATTRIB81           NUMBER,
  IIT_NUM_ATTRIB82           NUMBER,
  IIT_NUM_ATTRIB83           NUMBER,
  IIT_NUM_ATTRIB84           NUMBER,
  IIT_NUM_ATTRIB85           NUMBER,
  IIT_DATE_ATTRIB86          DATE,
  IIT_DATE_ATTRIB87          DATE,
  IIT_DATE_ATTRIB88          DATE,
  IIT_DATE_ATTRIB89          DATE,
  IIT_DATE_ATTRIB90          DATE,
  IIT_DATE_ATTRIB91          DATE,
  IIT_DATE_ATTRIB92          DATE,
  IIT_DATE_ATTRIB93          DATE,
  IIT_DATE_ATTRIB94          DATE,
  IIT_DATE_ATTRIB95          DATE,
  IIT_ANGLE                  NUMBER(6,2),
  IIT_ANGLE_TXT              VARCHAR2(20 BYTE),
  IIT_CLASS                  VARCHAR2(2 BYTE),
  IIT_CLASS_TXT              VARCHAR2(20 BYTE),
  IIT_COLOUR                 VARCHAR2(2 BYTE),
  IIT_COLOUR_TXT             VARCHAR2(20 BYTE),
  IIT_COORD_FLAG             VARCHAR2(1 BYTE),
  IIT_DESCRIPTION            VARCHAR2(40 BYTE),
  IIT_DIAGRAM                VARCHAR2(6 BYTE),
  IIT_DISTANCE               NUMBER(7,2),
  IIT_END_CHAIN              NUMBER(6),
  IIT_GAP                    NUMBER(6,2),
  IIT_HEIGHT                 NUMBER(6,2),
  IIT_HEIGHT_2               NUMBER(6,2),
  IIT_ID_CODE                VARCHAR2(8 BYTE),
  IIT_INSTAL_DATE            DATE,
  IIT_INVENT_DATE            DATE,
  IIT_INV_OWNERSHIP          VARCHAR2(4 BYTE),
  IIT_ITEMCODE               VARCHAR2(8 BYTE),
  IIT_LCO_LAMP_CONFIG_ID     NUMBER(3),
  IIT_LENGTH                 NUMBER,
  IIT_MATERIAL               VARCHAR2(30 BYTE),
  IIT_MATERIAL_TXT           VARCHAR2(20 BYTE),
  IIT_METHOD                 VARCHAR2(2 BYTE),
  IIT_METHOD_TXT             VARCHAR2(20 BYTE),
  IIT_NOTE                   VARCHAR2(40 BYTE),
  IIT_NO_OF_UNITS            NUMBER(3),
  IIT_OPTIONS                VARCHAR2(2 BYTE),
  IIT_OPTIONS_TXT            VARCHAR2(20 BYTE),
  IIT_OUN_ORG_ID_ELEC_BOARD  NUMBER(8),
  IIT_OWNER                  VARCHAR2(4 BYTE),
  IIT_OWNER_TXT              VARCHAR2(20 BYTE),
  IIT_PEO_INVENT_BY_ID       NUMBER(8),
  IIT_PHOTO                  VARCHAR2(6 BYTE),
  IIT_POWER                  NUMBER(6),
  IIT_PROV_FLAG              VARCHAR2(1 BYTE),
  IIT_REV_BY                 VARCHAR2(20 BYTE),
  IIT_REV_DATE               DATE,
  IIT_TYPE                   VARCHAR2(2 BYTE),
  IIT_TYPE_TXT               VARCHAR2(20 BYTE),
  IIT_WIDTH                  NUMBER(6,2),
  IIT_XTRA_CHAR_1            VARCHAR2(20 BYTE),
  IIT_XTRA_DATE_1            DATE,
  IIT_XTRA_DOMAIN_1          VARCHAR2(2 BYTE),
  IIT_XTRA_DOMAIN_TXT_1      VARCHAR2(20 BYTE),
  IIT_XTRA_NUMBER_1          NUMBER(10,2),
  IIT_X_SECT                 VARCHAR2(4 BYTE),
  IIT_DET_XSP                VARCHAR2(4 BYTE),
  IIT_OFFSET                 NUMBER,
  IIT_X                      NUMBER,
  IIT_Y                      NUMBER,
  IIT_Z                      NUMBER,
  IIT_NUM_ATTRIB96           NUMBER,
  IIT_NUM_ATTRIB97           NUMBER,
  IIT_NUM_ATTRIB98           NUMBER,
  IIT_NUM_ATTRIB99           NUMBER,
  IIT_NUM_ATTRIB100          NUMBER,
  IIT_NUM_ATTRIB101          NUMBER,
  IIT_NUM_ATTRIB102          NUMBER,
  IIT_NUM_ATTRIB103          NUMBER,
  IIT_NUM_ATTRIB104          NUMBER,
  IIT_NUM_ATTRIB105          NUMBER,
  IIT_NUM_ATTRIB106          NUMBER,
  IIT_NUM_ATTRIB107          NUMBER,
  IIT_NUM_ATTRIB108          NUMBER,
  IIT_NUM_ATTRIB109          NUMBER,
  IIT_NUM_ATTRIB110          NUMBER,
  IIT_NUM_ATTRIB111          NUMBER,
  IIT_NUM_ATTRIB112          NUMBER,
  IIT_NUM_ATTRIB113          NUMBER,
  IIT_NUM_ATTRIB114          NUMBER,
  IIT_NUM_ATTRIB115          NUMBER
)
;