SET DEFINE OFF;
Insert into NM_LOAD_DESTINATIONS
   (NLD_ID, NLD_TABLE_NAME, NLD_TABLE_SHORT_NAME, NLD_INSERT_PROC, NLD_VALIDATION_PROC)
 Values
   (NLD_ID_SEQ.nextval, 'X_RMS_RSD_CSV_HOLDING', 'XRSD', 'X_RMS_RSD_CSV_PACK.P_INSERT', 'X_RMS_RSD_CSV_PACK.P_VALIDATE');
COMMIT;
