SET DEFINE OFF;
MERGE INTO NM_ERRORS A USING
 (SELECT
  'RWI' as NER_APPL,
  1 as NER_ID,
  NULL as NER_HER_NO,
  'Accomplishment Mandatory Column is null' as NER_DESCR,
  NULL as NER_CAUSE
  FROM DUAL) B
ON (A.NER_ID = B.NER_ID and A.NER_APPL = B.NER_APPL)
WHEN NOT MATCHED THEN 
INSERT (
  NER_APPL, NER_ID, NER_HER_NO, NER_DESCR, NER_CAUSE)
VALUES (
  B.NER_APPL, B.NER_ID, B.NER_HER_NO, B.NER_DESCR, B.NER_CAUSE)
WHEN MATCHED THEN
UPDATE SET 
  A.NER_HER_NO = B.NER_HER_NO,
  A.NER_DESCR = B.NER_DESCR,
  A.NER_CAUSE = B.NER_CAUSE;

MERGE INTO NM_ERRORS A USING
 (SELECT
  'RWI' as NER_APPL,
  2 as NER_ID,
  NULL as NER_HER_NO,
  'Defect Mandatory Column is null' as NER_DESCR,
  NULL as NER_CAUSE
  FROM DUAL) B
ON (A.NER_ID = B.NER_ID and A.NER_APPL = B.NER_APPL)
WHEN NOT MATCHED THEN 
INSERT (
  NER_APPL, NER_ID, NER_HER_NO, NER_DESCR, NER_CAUSE)
VALUES (
  B.NER_APPL, B.NER_ID, B.NER_HER_NO, B.NER_DESCR, B.NER_CAUSE)
WHEN MATCHED THEN
UPDATE SET 
  A.NER_HER_NO = B.NER_HER_NO,
  A.NER_DESCR = B.NER_DESCR,
  A.NER_CAUSE = B.NER_CAUSE;

MERGE INTO NM_ERRORS A USING
 (SELECT
  'RWI' as NER_APPL,
  3 as NER_ID,
  NULL as NER_HER_NO,
  'Incident Mandatory Column is null' as NER_DESCR,
  NULL as NER_CAUSE
  FROM DUAL) B
ON (A.NER_ID = B.NER_ID and A.NER_APPL = B.NER_APPL)
WHEN NOT MATCHED THEN 
INSERT (
  NER_APPL, NER_ID, NER_HER_NO, NER_DESCR, NER_CAUSE)
VALUES (
  B.NER_APPL, B.NER_ID, B.NER_HER_NO, B.NER_DESCR, B.NER_CAUSE)
WHEN MATCHED THEN
UPDATE SET 
  A.NER_HER_NO = B.NER_HER_NO,
  A.NER_DESCR = B.NER_DESCR,
  A.NER_CAUSE = B.NER_CAUSE;

MERGE INTO NM_ERRORS A USING
 (SELECT
  'RWI' as NER_APPL,
  4 as NER_ID,
  NULL as NER_HER_NO,
  'Inspection Mandatory Column is null' as NER_DESCR,
  NULL as NER_CAUSE
  FROM DUAL) B
ON (A.NER_ID = B.NER_ID and A.NER_APPL = B.NER_APPL)
WHEN NOT MATCHED THEN 
INSERT (
  NER_APPL, NER_ID, NER_HER_NO, NER_DESCR, NER_CAUSE)
VALUES (
  B.NER_APPL, B.NER_ID, B.NER_HER_NO, B.NER_DESCR, B.NER_CAUSE)
WHEN MATCHED THEN
UPDATE SET 
  A.NER_HER_NO = B.NER_HER_NO,
  A.NER_DESCR = B.NER_DESCR,
  A.NER_CAUSE = B.NER_CAUSE;

MERGE INTO NM_ERRORS A USING
 (SELECT
  'RWI' as NER_APPL,
  5 as NER_ID,
  NULL as NER_HER_NO,
  'Request Mandatory Column is null' as NER_DESCR,
  NULL as NER_CAUSE
  FROM DUAL) B
ON (A.NER_ID = B.NER_ID and A.NER_APPL = B.NER_APPL)
WHEN NOT MATCHED THEN 
INSERT (
  NER_APPL, NER_ID, NER_HER_NO, NER_DESCR, NER_CAUSE)
VALUES (
  B.NER_APPL, B.NER_ID, B.NER_HER_NO, B.NER_DESCR, B.NER_CAUSE)
WHEN MATCHED THEN
UPDATE SET 
  A.NER_HER_NO = B.NER_HER_NO,
  A.NER_DESCR = B.NER_DESCR,
  A.NER_CAUSE = B.NER_CAUSE;

MERGE INTO NM_ERRORS A USING
 (SELECT
  'RWI' as NER_APPL,
  6 as NER_ID,
  NULL as NER_HER_NO,
  'Unable to Find The Location for the Point Asset: ' as NER_DESCR,
  NULL as NER_CAUSE
  FROM DUAL) B
ON (A.NER_ID = B.NER_ID and A.NER_APPL = B.NER_APPL)
WHEN NOT MATCHED THEN 
INSERT (
  NER_APPL, NER_ID, NER_HER_NO, NER_DESCR, NER_CAUSE)
VALUES (
  B.NER_APPL, B.NER_ID, B.NER_HER_NO, B.NER_DESCR, B.NER_CAUSE)
WHEN MATCHED THEN
UPDATE SET 
  A.NER_HER_NO = B.NER_HER_NO,
  A.NER_DESCR = B.NER_DESCR,
  A.NER_CAUSE = B.NER_CAUSE;

COMMIT;
