Create table X_RMS_RSD_CSV_HOLDING
(
	Vendor_Code						Varchar2(4)
,	Reference_id					Number(8)
,	Road_Number						Varchar2(125)
,	Asset_type_code					Varchar2(5)
,	Key_ID							Number		
,	Asset_description				Varchar2(125)
,	Road_Maintenance_Segment		Varchar2(30)
,	Date_of_creation				Date
,	Time_of_creation				Varchar2(5)
,	Longitude						Number		
,	Latitude						Number		
,	LGA								Varchar2(50)
,	Accomplishment_Number			Varchar2(30)
,	Accomplishment_ID				number(8)
,	Accomplishment_Date				Date
,	Activity						Number		
,	Activity_Name					Varchar2(255)
,	Activity_Type					Varchar2(30)
,	Quantity_Accomplished			Number		
,	Unit_Of_Measure_RSAM			Varchar2(30)
,	Second_Quantity					Number		
,	Second_Unit_of_Measure_RSAM			Varchar2(30)
,	Accomplishment_Comments			Varchar2(255)
,	Time_Work						Number		
,	Completed						Varchar2(1)
,	Defect_Number					Varchar2(12)
,	Defect_ID						number(8)
,	Date_Raised						Date
,	Time_Raised						Varchar2(5)
,	Cause_Of_Defect					Varchar2(30)
,	Reoccurring_Defect				Varchar2(1)
,	Defect_Type						Varchar2(50)
,	Position_within_Location		Number		
,	Defect_Completion_Date			Date
,	Defect_Completion_Time			Varchar2(5)
,	Estimated_Quantity_for_repair	Number		
,	Unit_of_Measure_RSDE			Varchar2(30)
,	Estimated_Second_Quantity		Number		
,	Second_Unit_of_Measure			Varchar2(30)
,	Defect_Comments					Varchar2(255)
,	Incident_ID						Number(8)
,	Incident_Type					Varchar2(30)
,	Date_Call_Received				Date
,	Time_Call_Received				Varchar2(5)
,	Incident_Description			Varchar2(255)
,	Advice_Received_From			Varchar2(50)
,	Condition_At_Time_Of_Incident	Varchar2(50)
,	Action_Required					Varchar2(50)
,	Damage_To_Property				Varchar2(30)
,	Incident_Completion_Date		Date
,	Incident_Completion_Time		Varchar2(5)
,	Inspection_Number				Varchar2(30)
,	Inspection_ID					Number		
,	Inspection_Type					Varchar2(30)
,	Target_Date						Date
,	Target_Time						Varchar2(5)
,	Inspection_Completion_Date		Date
,	Inspection_Completion_Time		Varchar2(5)
,	Inspection_Comments				Varchar2(255)
,	Request_ID						Number(8)
,	Request_Type					Varchar2(30)
,	Request_Date_Received			Date
,	Request_Time_Received			Varchar2(5)
,	Request_Number					Varchar2(30)
,	Request_Completion_Date			Date
,	Request_Completion_Time			Varchar2(5)
,	Request_Comments				Varchar2(255)
);