'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class strings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Sign_Broker.strings", GetType(strings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to contact your systems administrator. .
        '''</summary>
        Friend Shared ReadOnly Property CONTACT_ADMIN() As String
            Get
                Return ResourceManager.GetString("CONTACT_ADMIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There is an issue retrieving data from an existing configuration file.  This error could occur if the file was copied form a different computer.  Please check the values, test and resave the data..
        '''</summary>
        Friend Shared ReadOnly Property ERROR_CONFIG_SCREEN_DATA_LOAD() As String
            Get
                Return ResourceManager.GetString("ERROR_CONFIG_SCREEN_DATA_LOAD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to completely load from the configuration file.
        '''</summary>
        Friend Shared ReadOnly Property ERROR_CONFIG_SCREEN_DATA_LOAD_TITLE() As String
            Get
                Return ResourceManager.GetString("ERROR_CONFIG_SCREEN_DATA_LOAD_TITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Below are the technical details for the issue: .
        '''</summary>
        Friend Shared ReadOnly Property ERROR_DETAILS() As String
            Get
                Return ResourceManager.GetString("ERROR_DETAILS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please close the program and try again.  If the issue persists then contact a systems administrator..
        '''</summary>
        Friend Shared ReadOnly Property ERROR_MAIN_CONFIG_DATA_LOAD() As String
            Get
                Return ResourceManager.GetString("ERROR_MAIN_CONFIG_DATA_LOAD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to completely load from the configuration file.
        '''</summary>
        Friend Shared ReadOnly Property ERROR_MAIN_CONFIG_DATA_LOAD_TITLE() As String
            Get
                Return ResourceManager.GetString("ERROR_MAIN_CONFIG_DATA_LOAD_TITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Network communications was interrupted or lost to the TransInfo Database.
        '''Please ensure that you have network access and then try again.  
        '''If the issue persists then contact a system administrator..
        '''</summary>
        Friend Shared ReadOnly Property ERROR_ORA_03113() As String
            Get
                Return ResourceManager.GetString("ERROR_ORA_03113", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A TransInfo System Administrator is most likely preforming system maintenance and the broker cannot continue.   Please wait a few minutes and try again.
        '''If the issue persists then contact a system administrator..
        '''</summary>
        Friend Shared ReadOnly Property ERROR_ORA_04068() As String
            Get
                Return ResourceManager.GetString("ERROR_ORA_04068", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Database Configuration File could not be found.  Please .
        '''</summary>
        Friend Shared ReadOnly Property ERROR_ORA_CONFIG() As String
            Get
                Return ResourceManager.GetString("ERROR_ORA_CONFIG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The ora_connect.xml  file needs to be created by the broker Systems Administrator..
        '''</summary>
        Friend Shared ReadOnly Property ERROR_ORA_CONFIG_EX() As String
            Get
                Return ResourceManager.GetString("ERROR_ORA_CONFIG_EX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  highway &lt;H&gt; at milepoint &lt;M&gt; .
        '''</summary>
        Friend Shared ReadOnly Property ERROR_SFA_LOCATION() As String
            Get
                Return ResourceManager.GetString("ERROR_SFA_LOCATION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The installation on &lt;LOC&gt; contains an error preventing synchronization. Please review the record for possible issues or contact the Sign Asset Database Administrator..
        '''</summary>
        Friend Shared ReadOnly Property ERROR_SFA_LOG_UNHANDLED() As String
            Get
                Return ResourceManager.GetString("ERROR_SFA_LOG_UNHANDLED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SFA Access Databases Not Found or producing errors.
        '''Please verify you can open the sign_client.mdb with out errors and then retry the sign_broker. 
        '''If this error continues then .
        '''</summary>
        Friend Shared ReadOnly Property ERROR_SFA_NOT_FOUND() As String
            Get
                Return ResourceManager.GetString("ERROR_SFA_NOT_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The SFA MDB paths in the configuration file need to be checked or the sign_client.mdb is producing errors when opening..
        '''</summary>
        Friend Shared ReadOnly Property ERROR_SFA_NOT_FOUND_EX() As String
            Get
                Return ResourceManager.GetString("ERROR_SFA_NOT_FOUND_EX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SFA Access Database Internal Error.
        '''</summary>
        Friend Shared ReadOnly Property ERROR_SFA_NOT_INI() As String
            Get
                Return ResourceManager.GetString("ERROR_SFA_NOT_INI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please ensure the signs field app can be run, then try the broker again.  .
        '''</summary>
        Friend Shared ReadOnly Property ERROR_SFA_NOT_INI_EX() As String
            Get
                Return ResourceManager.GetString("ERROR_SFA_NOT_INI_EX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An acceptable Broker Version Number could not be found in the SFA database.  
        '''•Please Close the Broker.  
        '''•Then ensure that you have a network connection to the ODOT network. 
        '''•Once you have confirmed the network connection, please restart the Broker from the shortcut provided by your systems administrator. 
        ''' If the issue persists, then .
        '''</summary>
        Friend Shared ReadOnly Property ERROR_SFA_VERSION_NOT_FOUND() As String
            Get
                Return ResourceManager.GetString("ERROR_SFA_VERSION_NOT_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version Control Mismatch..
        '''</summary>
        Friend Shared ReadOnly Property ERROR_SFA_VERSION_NOT_FOUND_EX() As String
            Get
                Return ResourceManager.GetString("ERROR_SFA_VERSION_NOT_FOUND_EX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An Issue occured with the Oracle Database Please  .
        '''</summary>
        Friend Shared ReadOnly Property ERROR_TI_API() As String
            Get
                Return ResourceManager.GetString("ERROR_TI_API", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to xodot_signs_api.get_version is generating an error.   Please have a TransInfo administrator verify the state of the xodot_signs_api package..
        '''</summary>
        Friend Shared ReadOnly Property ERROR_TI_API_EX() As String
            Get
                Return ResourceManager.GetString("ERROR_TI_API_EX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Item that is attempting to sync from TI to SFA  has items that are not synced in the Edit Table.  Please Fix any Errors relating to this Item in the SFA to TI sync and try again..
        '''</summary>
        Friend Shared ReadOnly Property ERROR_TI_TO_SFA_WITH_EDIT_ITEM_IN_SFA() As String
            Get
                Return ResourceManager.GetString("ERROR_TI_TO_SFA_WITH_EDIT_ITEM_IN_SFA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unexpected Issue, please have your System Administrator check the TRANSINFO Database Error log..
        '''</summary>
        Friend Shared ReadOnly Property ERROR_UNEXPECTED() As String
            Get
                Return ResourceManager.GetString("ERROR_UNEXPECTED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sync Process Complete.
        '''</summary>
        Friend Shared ReadOnly Property INFO_SYNC_COMPLETED() As String
            Get
                Return ResourceManager.GetString("INFO_SYNC_COMPLETED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TI to SFA Lookup Lists.
        '''</summary>
        Friend Shared ReadOnly Property TASK_LOV() As String
            Get
                Return ResourceManager.GetString("TASK_LOV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Populating the Task List.
        '''</summary>
        Friend Shared ReadOnly Property TASK_POPULATING_TASKS() As String
            Get
                Return ResourceManager.GetString("TASK_POPULATING_TASKS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SFA Changes to Sync to TI.
        '''</summary>
        Friend Shared ReadOnly Property TASK_SFA_ITEMS() As String
            Get
                Return ResourceManager.GetString("TASK_SFA_ITEMS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TI to SFA Install Items to Sync.
        '''</summary>
        Friend Shared ReadOnly Property TASK_TI_ITEMS() As String
            Get
                Return ResourceManager.GetString("TASK_TI_ITEMS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The user name used to log into TransInfo does not have rights to access the Signs Data.  Please .
        '''</summary>
        Friend Shared ReadOnly Property TI_BAD_USER() As String
            Get
                Return ResourceManager.GetString("TI_BAD_USER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to connect to TransInfo, Please check your network connection and try again.  If the issue continues then .
        '''</summary>
        Friend Shared ReadOnly Property TI_CONNECT_ERROR() As String
            Get
                Return ResourceManager.GetString("TI_CONNECT_ERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attempting to connect to TransInfo.  Please Wait..
        '''</summary>
        Friend Shared ReadOnly Property TI_CONNECTING() As String
            Get
                Return ResourceManager.GetString("TI_CONNECTING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An unhandled fatal issue occurred, please .
        '''</summary>
        Friend Shared ReadOnly Property UNHANDLED() As String
            Get
                Return ResourceManager.GetString("UNHANDLED", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
