/* ---------- JM, 2011.07.25,13:54
OHMS, HPMS INSERT Script
---------- */

set sqlblanklines on

-- Insert Views
	@V_NM_SECW.vw

-- Modify HPMS Table (will not affect HPMS functionality	
	ALTER TABLE HPMS_COLUMN	ADD HCL_SEQ_NAME VARCHAR2(30);


-- HPMS_CATALOG
	INSERT INTO HPMS_CATALOG (hc_id, hc_name, hc_include)
		VALUES (4,'OHMS','Y');



-- HPMS_TABLE
	INSERT INTO HPMS_TABLE (ht_id, ht_hc_id, ht_name, ht_include, ht_hl_id)
		VALUES (7,4,'OHMS_SUBMIT_SECTIONS','Y',1);



-- HPMS_Column
	
	Insert into HPMS_COLUMN ("HCL_ID",HCL_HT_ID,HCL_NAME,HCL_LOCATION_COL,HCL_TYPE,HCL_SIZE,HCL_SEQ_NAME) 
		values (501,7,'YEAR_RECORD','N','NUMBER','4',null);
	Insert into HPMS_COLUMN ("HCL_ID",HCL_HT_ID,HCL_NAME,HCL_LOCATION_COL,HCL_TYPE,HCL_SIZE,HCL_SEQ_NAME) 
		values (502,7,'STATE_CODE','N','NUMBER','2',null);
	Insert into HPMS_COLUMN ("HCL_ID",HCL_HT_ID,HCL_NAME,HCL_LOCATION_COL,HCL_TYPE,HCL_SIZE,HCL_SEQ_NAME) 
		values (503,7,'ROUTE_ID','Y','VARCHAR2','32',null);
	Insert into HPMS_COLUMN ("HCL_ID",HCL_HT_ID,HCL_NAME,HCL_LOCATION_COL,HCL_TYPE,HCL_SIZE,HCL_SEQ_NAME) 
		values (504,7,'BEGIN_POINT','Y','NUMBER','8,3',null);
	Insert into HPMS_COLUMN ("HCL_ID",HCL_HT_ID,HCL_NAME,HCL_LOCATION_COL,HCL_TYPE,HCL_SIZE,HCL_SEQ_NAME) 
		values (505,7,'END_POINT','Y','NUMBER','8,3',null);
	Insert into HPMS_COLUMN ("HCL_ID",HCL_HT_ID,HCL_NAME,HCL_LOCATION_COL,HCL_TYPE,HCL_SIZE,HCL_SEQ_NAME) 
		values (506,7,'DATA_ITEM','N','VARCHAR2','25',null);
	Insert into HPMS_COLUMN ("HCL_ID",HCL_HT_ID,HCL_NAME,HCL_LOCATION_COL,HCL_TYPE,HCL_SIZE,HCL_SEQ_NAME) 
		values (507,7,'SECTION_LENGTH','Y','NUMBER','8,3',null);
	Insert into HPMS_COLUMN ("HCL_ID",HCL_HT_ID,HCL_NAME,HCL_LOCATION_COL,HCL_TYPE,HCL_SIZE,HCL_SEQ_NAME) 
		values (508,7,'VALUE_NUMERIC','N','NUMBER',null,null);
	Insert into HPMS_COLUMN ("HCL_ID",HCL_HT_ID,HCL_NAME,HCL_LOCATION_COL,HCL_TYPE,HCL_SIZE,HCL_SEQ_NAME) 
		values (509,7,'VALUE_TEXT','N','VARCHAR2','50',null);
	Insert into HPMS_COLUMN ("HCL_ID",HCL_HT_ID,HCL_NAME,HCL_LOCATION_COL,HCL_TYPE,HCL_SIZE,HCL_SEQ_NAME) 
		values (510,7,'VALUE_DATE','N','DATE',null,null);
	Insert into HPMS_COLUMN ("HCL_ID",HCL_HT_ID,HCL_NAME,HCL_LOCATION_COL,HCL_TYPE,HCL_SIZE,HCL_SEQ_NAME) 
		values (511,7,'COMMENTS','N','VARCHAR2','50',null);



-- HPMS_MAPPING
REM INSERTING into HPMS_MAPPING
Insert into HPMS_MAPPING (HM_ID,HM_HCL_ID,HM_HDI_ID,HM_ITEM,HM_ITEM_VALUE,HM_ITEM_ATTRIBUTE,HM_ITEM_WHERE,HM_ITEM_FUNCTION,HM_XSP,HM_ITEM_TYPE,HM_ITEM_FORMULA,HM_JOIN_TYPE,HM_OUTPUT,HM_ROLLUP,HM_CURSOR_PROCESS) values (5352,501,null,null,'DATA_YEAR()',null,null,'CUSTOM',null,'FUNCTION',null,'I',null,null,null);
Insert into HPMS_MAPPING (HM_ID,HM_HCL_ID,HM_HDI_ID,HM_ITEM,HM_ITEM_VALUE,HM_ITEM_ATTRIBUTE,HM_ITEM_WHERE,HM_ITEM_FUNCTION,HM_XSP,HM_ITEM_TYPE,HM_ITEM_FORMULA,HM_JOIN_TYPE,HM_OUTPUT,HM_ROLLUP,HM_CURSOR_PROCESS) values (5353,502,null,null,'GET_STATE_CODE()',null,null,'CUSTOM',null,'FUNCTION',null,'I',null,null,null);
Insert into HPMS_MAPPING (HM_ID,HM_HCL_ID,HM_HDI_ID,HM_ITEM,HM_ITEM_VALUE,HM_ITEM_ATTRIBUTE,HM_ITEM_WHERE,HM_ITEM_FUNCTION,HM_XSP,HM_ITEM_TYPE,HM_ITEM_FORMULA,HM_JOIN_TYPE,HM_OUTPUT,HM_ROLLUP,HM_CURSOR_PROCESS) values (5354,503,null,'HWY','NE_UNIQUE','NE_UNIQUE',null,'VALUE',null,'GROUP',null,'I',null,null,null);
Insert into HPMS_MAPPING (HM_ID,HM_HCL_ID,HM_HDI_ID,HM_ITEM,HM_ITEM_VALUE,HM_ITEM_ATTRIBUTE,HM_ITEM_WHERE,HM_ITEM_FUNCTION,HM_XSP,HM_ITEM_TYPE,HM_ITEM_FORMULA,HM_JOIN_TYPE,HM_OUTPUT,HM_ROLLUP,HM_CURSOR_PROCESS) values (5355,504,null,'HWY','NM_SLK',null,null,'VALUE',null,'GROUP',null,'I',null,null,null);
Insert into HPMS_MAPPING (HM_ID,HM_HCL_ID,HM_HDI_ID,HM_ITEM,HM_ITEM_VALUE,HM_ITEM_ATTRIBUTE,HM_ITEM_WHERE,HM_ITEM_FUNCTION,HM_XSP,HM_ITEM_TYPE,HM_ITEM_FORMULA,HM_JOIN_TYPE,HM_OUTPUT,HM_ROLLUP,HM_CURSOR_PROCESS) values (5356,505,null,'HWY','NM_END_SLK',null,null,'VALUE',null,'GROUP',null,'I',null,null,null);

Insert into HPMS_MAPPING (HM_ID,HM_HCL_ID,HM_HDI_ID,HM_ITEM,HM_ITEM_VALUE,HM_ITEM_ATTRIBUTE,HM_ITEM_WHERE,HM_ITEM_FUNCTION,HM_XSP,HM_ITEM_TYPE,HM_ITEM_FORMULA,HM_JOIN_TYPE,HM_OUTPUT,HM_ROLLUP,HM_CURSOR_PROCESS) values (5359,507,null,'HWY','NM_END_SLK-NM_SLK',null,null,'CONSTANT',null,'FORMULA',null,'I',null,null,null);


Insert into HPMS_MAPPING (HM_ID,HM_HCL_ID,HM_HDI_ID,HM_ITEM,HM_ITEM_VALUE,HM_ITEM_ATTRIBUTE,HM_ITEM_WHERE,HM_ITEM_FUNCTION,HM_XSP,HM_ITEM_TYPE,HM_ITEM_FORMULA,HM_JOIN_TYPE,HM_OUTPUT,HM_ROLLUP,HM_CURSOR_PROCESS) values (5364,506,504,null,'Structure_Type',null,null,'CONSTANT',null,'TEXT',null,'A',null,null,'N');
Insert into HPMS_MAPPING (HM_ID,HM_HCL_ID,HM_HDI_ID,HM_ITEM,HM_ITEM_VALUE,HM_ITEM_ATTRIBUTE,HM_ITEM_WHERE,HM_ITEM_FUNCTION,HM_XSP,HM_ITEM_TYPE,HM_ITEM_FORMULA,HM_JOIN_TYPE,HM_OUTPUT,HM_ROLLUP,HM_CURSOR_PROCESS) values (5365,508,504,'NBI','STRUC_ID',null,null,'OUTERJOIN_DATA',null,'ASSET','CASE
  WHEN TUNL_STRUC_ID IS NOT NULL THEN  2
  WHEN NBI_STRUC_ID IS NOT NULL THEN  1
 ELSE
  NULL
 END
','A','Y',null,'N');
Insert into HPMS_MAPPING (HM_ID,HM_HCL_ID,HM_HDI_ID,HM_ITEM,HM_ITEM_VALUE,HM_ITEM_ATTRIBUTE,HM_ITEM_WHERE,HM_ITEM_FUNCTION,HM_XSP,HM_ITEM_TYPE,HM_ITEM_FORMULA,HM_JOIN_TYPE,HM_OUTPUT,HM_ROLLUP,HM_CURSOR_PROCESS) values (5522,508,504,'TUNL','STRUC_ID',null,null,'OUTERJOIN_DATA',null,'ASSET',null,'A',null,null,'N');







Insert into HPMS_MAPPING (HM_ID,HM_HCL_ID,HM_HDI_ID,HM_ITEM,HM_ITEM_VALUE,HM_ITEM_ATTRIBUTE,HM_ITEM_WHERE,HM_ITEM_FUNCTION,HM_XSP,HM_ITEM_TYPE,HM_ITEM_FORMULA,HM_JOIN_TYPE,HM_OUTPUT,HM_ROLLUP,HM_CURSOR_PROCESS) values (7155,506,568,null,'HPMS_SAMPLE_ID',null,null,'CONSTANT',null,'TEXT',null,'A',null,null,null);
Insert into HPMS_MAPPING (HM_ID,HM_HCL_ID,HM_HDI_ID,HM_ITEM,HM_ITEM_VALUE,HM_ITEM_ATTRIBUTE,HM_ITEM_WHERE,HM_ITEM_FUNCTION,HM_XSP,HM_ITEM_TYPE,HM_ITEM_FORMULA,HM_JOIN_TYPE,HM_OUTPUT,HM_ROLLUP,HM_CURSOR_PROCESS) values (7156,508,568,'HPMS','SAMP_ID',null,null,'VALUE',null,'ASSET',null,'I','Y',null,'Y');


			
			
-- HPMS_PROCEDURE
	INSERT INTO HPMS_PROCEDURE(hp_id, hp_ht_id, hp_procedure, hp_db_table_name, hp_mview_creates, hp_table_creates)
		VALUES (6, 7, ' ', 'OHMS_SUBMIT_SECTIONS', ' ' , ' ');
commit;




-- Add the table from prcedures so that the Validate command will work

declare
    i integer;
    sname varchar(50);


BEGIN  --  Done to remove error meessage

sname := 'OHMS_SUBMIT_SECTIONS';


    select COUNT(*) into I from USER_TABLES where TABLE_NAME = SNAME;
    if i <> 0 then
        execute immediate 'drop table ' || sname ;
    end if;
END;

/

CREATE TABLE OHMS_SUBMIT_SECTIONS
    (YEAR_RECORD NUMBER(4)
    ,STATE_CODE NUMBER(2)
    ,ROUTE_ID VARCHAR2(32)
    ,BEGIN_POINT NUMBER(8,3)
    ,END_POINT NUMBER(8,3)
    ,DATA_ITEM VARCHAR2(25)
    ,SECTION_LENGTH NUMBER(8,3)
    ,VALUE_NUMERIC NUMBER
    ,VALUE_TEXT VARCHAR2(50)
    ,VALUE_DATE DATE
    ,COMMENTS VARCHAR2(50)
    );


		
-- Installing Modified HPMS Procedure
@xna_ohms.pkh
@xna_ohms.pkb

Set echo on

-- this command can take awhile to complete
exec xna_ohms.table_validate(7);

Set echo off

