undefine log_extension
col      log_extension new_value log_extension noprint
set term off
select  TO_CHAR(sysdate,'YYYY.MM.DD_HH24MISS')||'.LOG' log_extension from dual
/
set term on

define logfile1='install_log_&log_extension'
spool &logfile1

--
SET TERM ON
PROMPT *** RUNNING: WOWT003-X_WO_TFL_WORK_TRAY_IM511003_FULL.sql ***
SET TERM OFF
--
SET FEEDBACK ON
START WOWT003-X_WO_TFL_WORK_TRAY_IM511003_FULL.sql
SET FEEDBACK OFF
--
--
SET TERM ON
PROMPT *** RUNNING: WOWT003-X_WO_TFL_WORK_TRAY_IM511003_ALL_nobud.sql ***
SET TERM OFF
--
SET FEEDBACK ON
START WOWT003-X_WO_TFL_WORK_TRAY_IM511003_ALL_nobud.sql
SET FEEDBACK OFF
--
--
SET TERM ON
PROMPT *** RUNNING: WOWT003-X_WO_TFL_WORK_TRAY_IM511003_ALL.sql ***
SET TERM OFF
--
SET FEEDBACK ON
START WOWT003-X_WO_TFL_WORK_TRAY_IM511003_ALL.sql
SET FEEDBACK OFF
--
--
SET TERM ON
PROMPT *** RUNNING: WOWT001-X_WO_TFL_WORK_TRAY_IM511001.sql ***
SET TERM OFF
--
SET FEEDBACK ON
START WOWT001-X_WO_TFL_WORK_TRAY_IM511001.sql
SET FEEDBACK OFF
--
--
SET TERM ON
PROMPT *** RUNNING: WOWT001-X_WO_TFL_WORK_TRAY_IM511001_nobud.sql ***
SET TERM OFF
--
SET FEEDBACK ON
START WOWT001-X_WO_TFL_WORK_TRAY_IM511001_nobud.sql
SET FEEDBACK OFF
--
--


SPOOL OFF