--
-- im_user_pods
--
delete im_user_pods;

SET DEFINE OFF;
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (330, 'NICKISHEPHERD', 1, 1);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (333, 'NICKISHEPHERD', 1, 2);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (330, 'COOKJ', 1, 1);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (333, 'COOKJ', 1, 2);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (330, 'HIGHWAYS', 8, 1);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (331, 'LOHACNE1', 8, 1);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (333, 'LOHACNE1', 8, 2);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (333, 'HIGHWAYS', 8, 2);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (331, 'HIGHWAYS', 8, 3);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (332, 'HIGHWAYS', 8, 4);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (330, 'LOHACNE1', 8, 3);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (332, 'LOHACNE1', 8, 4);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (334, 'LOHACNE1', 8, 5);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (335, 'LOHACNE1', 8, 6);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (23, 'LOHACNE1', 1, 1);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (460, 'LOHACNE1', 1, 2);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (489, 'LOHACNE1', 1, 3);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (490, 'LOHACNE1', 1, 4);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (331, 'LOHACNE1', 1, 5);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (44, 'LOHACNE1', 1, 6);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (489, 'LOHACNE1', 1, 7);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (490, 'LOHACNE1', 1, 8);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (460, 'LOHACNE1', 1, 9);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (330, 'LOHACNE1', 1, 10);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (333, 'LOHACNE1', 1, 11);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (335, 'LOHACNE1', 1, 12);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (332, 'LOHACNE1', 1, 13);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (334, 'LOHACNE1', 1, 14);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (23, 'HIGHWAYS', 16, 1);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (330, 'GSTEWARD', 1, 1);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (333, 'GSTEWARD', 1, 2);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (334, 'GSTEWARD', 1, 3);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (460, 'GSTEWARD', 1, 4);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (490, 'CRIMINALER', 1, 1);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (330, 'DAVIDSONAL', 1, 1);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (331, 'LOHACNW1', 8, 1);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (333, 'OLIVERGA', 1, 1);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (331, 'LOHACS1', 8, 1);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (23, 'LOHACS1', 8, 2);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (44, 'LOHACS1', 8, 3);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (489, 'LOHACS1', 8, 4);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (490, 'LOHACS1', 8, 5);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (460, 'LOHACS1', 8, 6);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (335, 'LOHACS1', 8, 7);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (335, 'LOHACNW1', 8, 2);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (330, 'LOHACS1', 8, 8);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (333, 'LOHACS1', 8, 9);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (332, 'LOHACS1', 8, 10);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (334, 'LOHACS1', 8, 11);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (330, 'LOHACNW1', 8, 3);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (333, 'LOHACNW1', 8, 4);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (332, 'LOHACNW1', 8, 5);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (334, 'LOHACNW1', 8, 6);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (489, 'LOHACNW1', 8, 7);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (490, 'LOHACNW1', 8, 8);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (460, 'LOHACNW1', 8, 9);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (23, 'LOHACNW1', 8, 10);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (44, 'LOHACNW1', 8, 11);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (332, 'HIGHWAYS', 1, 1);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (331, 'LOHACC1', 8, 1);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (335, 'LOHACC1', 8, 2);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (330, 'LOHACC1', 8, 3);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (333, 'LOHACC1', 8, 4);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (332, 'LOHACC1', 8, 5);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (334, 'LOHACC1', 8, 6);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (489, 'LOHACC1', 8, 7);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (490, 'LOHACC1', 8, 8);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (460, 'LOHACC1', 8, 9);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (23, 'LOHACC1', 8, 10);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (44, 'LOHACC1', 8, 11);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (334, 'HIGHWAYS', 1, 2);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (489, 'HIGHWAYS', 1, 3);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (490, 'HIGHWAYS', 1, 4);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (460, 'HIGHWAYS', 1, 5);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (335, 'HIGHWAYS', 1, 6);
Insert into IM_USER_PODS
   (IUP_IP_ID, IUP_HUS_USERNAME, IUP_IT_ID, IUP_POD_POSITION)
 Values
   (44, 'HIGHWAYS', 1, 7);
COMMIT;
