--
-----------------------------------------------------------------------------
--
--   PVCS Identifiers :-
--
--       pvcsid           : $Header:   //vm_latest/archives/customer/Virgin/VirginMediaAddressLayer2Update/CreateAL2MetaModel.sql-arc   1.0   Dec 18 2012 12:21:26   Ian.Turnbull  $
--       Module Name      : $Workfile:   CreateAL2MetaModel.sql  $
--       Date into PVCS   : $Date:   Dec 18 2012 12:21:26  $
--       Date fetched Out : $Modtime:   Dec 18 2012 11:55:00  $
--       PVCS Version     : $Revision:   1.0  $
--
--
--   Author : %USERNAME%
--
-----------------------------------------------------------------------------
--	Copyright (c) exor corporation ltd, 2012
-----------------------------------------------------------------------------
--
Insert into NM_INV_TYPES
   (NIT_INV_TYPE, NIT_PNT_OR_CONT, NIT_X_SECT_ALLOW_FLAG, NIT_ELEC_DRAIN_CARR, NIT_CONTIGUOUS,
    NIT_REPLACEABLE, NIT_EXCLUSIVE, NIT_CATEGORY, NIT_DESCR, NIT_LINEAR, 
    NIT_USE_XY, NIT_MULTIPLE_ALLOWED, NIT_END_LOC_ONLY, 
    NIT_START_DATE, NIT_FLEX_ITEM_FLAG, NIT_TABLE_NAME, NIT_ADMIN_TYPE, NIT_TOP, 
    NIT_FOREIGN_PK_COLUMN, NIT_UPDATE_ALLOWED, NIT_DATE_CREATED, NIT_DATE_MODIFIED, NIT_MODIFIED_BY, NIT_CREATED_BY)
 Values
   ('AL2', 'P', 'N', 'C', 'N', 
    'N', 'N', 'F', 'AddressLayer 2', 'N', 
    'N', 'N', 'N',  
    TO_DATE('01/01/1970 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'N', 'X_VM_V_ADDRESSLAYER2_SDO', 
    'EXOR', 'N', 'OBJECTID', 'Y', TO_DATE('07/22/2010 18:47:49', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('07/22/2010 18:47:49', 'MM/DD/YYYY HH24:MI:SS'), USER,USER)
/


Insert into NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, ITA_DISP_WIDTH)
 Values
   ('AL2', 'ADDRESS', 'N', 1, 'N', 
    'VARCHAR2', 200, 'Address', 
    'N', 'ADDRESS', 
    'ADDRESS', TO_DATE('01/01/1970 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 
    'N', 'N', TO_DATE('07/22/2010 18:48:40', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('07/22/2010 18:48:40', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 10)
/


Insert into NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, ITA_DISP_WIDTH)
 Values
   ('AL2', 'ADMINISTRATIVE_AREA', 'N', 7, 'N', 
    'VARCHAR2', 100, 'Administrative Area', 
    'N', 'ADMINISTRATIVE_AREA', 
    'ADMINISTRATIVE_AREA', TO_DATE('01/01/1970 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 
    'N', 'N', TO_DATE('07/22/2010 18:53:06', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('07/22/2010 18:53:06', 'MM/DD/YYYY HH24:MI:SS'),USER, USER, 'Y', 10)
/


Insert into NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, ITA_DISP_WIDTH)
 Values
   ('AL2', 'LOCALITY', 'N', 3, 'N', 
    'VARCHAR2', 80, 'Locality', 
    'N', 'LOCALITY', 
    'LOCALITY', TO_DATE('01/01/1970 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 
    'N', 'N', TO_DATE('07/22/2010 18:50:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('07/22/2010 18:50:00', 'MM/DD/YYYY HH24:MI:SS'),USER, USER, 'Y', 10)
/


Insert into NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, ITA_DISP_WIDTH)
 Values
   ('AL2', 'POST_CODE', 'N', 6, 'N', 
    'VARCHAR2', 8, 'Post Code', 
    'N', 'POSTCODE', 
    'POSTCODE', TO_DATE('01/01/1970 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 
    'N', 'N', TO_DATE('07/22/2010 18:52:13', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('07/22/2010 18:52:13', 'MM/DD/YYYY HH24:MI:SS'),USER, USER, 'Y', 10)
/


Insert into NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, ITA_DISP_WIDTH)
 Values
   ('AL2', 'POST_TOWN', 'N', 5, 'N', 
    'VARCHAR2', 30, 'Post Town', 
    'N', 'POST_TOWN', 
    'POST_TOWN', TO_DATE('01/01/1970 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 
    'N', 'N', TO_DATE('07/22/2010 18:51:26', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('07/22/2010 18:51:26', 'MM/DD/YYYY HH24:MI:SS'),USER, USER, 'Y', 10)
/


Insert into NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, ITA_DISP_WIDTH)
 Values
   ('AL2', 'STREET', 'N', 2, 'N', 
    'VARCHAR2', 80, 'Street', 
    'N', 'STREET', 
    'STREET', TO_DATE('01/01/1970 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 
    'N', 'N', TO_DATE('07/22/2010 18:49:17', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('07/22/2010 18:49:17', 'MM/DD/YYYY HH24:MI:SS'),USER, USER, 'Y', 10)
/


Insert into NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, ITA_DISP_WIDTH)
 Values
   ('AL2', 'TOWN', 'N', 4, 'N', 
    'VARCHAR2', 60, 'Town', 
    'N', 'TOWN', 
    'TOWN', TO_DATE('01/01/1970 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 
    'N', 'N', TO_DATE('07/22/2010 18:50:47', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('07/22/2010 18:50:47', 'MM/DD/YYYY HH24:MI:SS'),USER, USER, 'Y', 10)
/


Insert into NM_INV_TYPE_ROLES
   (ITR_INV_TYPE, ITR_HRO_ROLE, ITR_MODE)
 Values
   ('AL2', 'HIG_USER', 'READONLY')


insert into nm_inv_themes (NITH_NIT_ID,NITH_NTH_THEME_ID)
select 'AL2', nth_theme_id 
from nm_themes_all
where nth_feature_table =  'X_VM_V_ADDRESSLAYER2_SDO'


select * from nm_inv_themes where NITH_NIT_ID = '