REM Copyright (c) Exor Corporation Ltd, 2004
REM @(#)uniclass_upg.sql	1.1 07/20/04

insert into HIG_MODULES (
HMO_MODULE
,HMO_TITLE
,HMO_FILENAME
,HMO_MODULE_TYPE
,HMO_FASTPATH_OPTS
,HMO_FASTPATH_INVALID
,HMO_USE_GRI
,HMO_APPLICATION
,HMO_MENU
) select
'UNICLASS'
,'Uniclass Interface Outgoing'
,'uniclass.sql'
,'SQL'
,''
,'N'
,'Y'
,'MAI'
,''
from dual
where not exists (
 select 'not exists'
 from HIG_MODULES
where HMO_MODULE = 'UNICLASS'
)
/
INSERT INTO GRI_MODULES ( GRM_MODULE, GRM_MODULE_TYPE, GRM_MODULE_PATH, GRM_FILE_TYPE, GRM_TAG_FLAG,
GRM_TAG_TABLE, GRM_TAG_COLUMN, GRM_TAG_WHERE, GRM_LINESIZE, GRM_PAGESIZE ) VALUES ( 
'UNICLASS', 'SQL', '$PROD_HOME/bin', 'lis', 'N', NULL, NULL, NULL, 132, 66)
/
INSERT INTO GRI_MODULE_PARAMS ( GMP_MODULE, GMP_PARAM, GMP_SEQ, GMP_PARAM_DESCR, GMP_MANDATORY,
GMP_NO_ALLOWED, GMP_WHERE, GMP_TAG_RESTRICTION, GMP_TAG_WHERE, GMP_DEFAULT_TABLE,
GMP_DEFAULT_COLUMN, GMP_DEFAULT_WHERE, GMP_VISIBLE, GMP_GAZETTEER, GMP_LOV, GMP_VAL_GLOBAL,
GMP_WILDCARD, GMP_HINT_TEXT ) VALUES ( 
'UNICLASS', 'TEXT', 2, 'File path', 'N', 1, NULL, 'N', NULL, 'HIG_USER_OPTIONS', 'HUO_VALUE'
, 'HUO_ID = ''INTERPATH'' AND HUO_HUS_USER_ID = (SELECT MAX(HUS_USER_ID) FROM HIG_USERS WHERE HUS_USERNAME = USER)'
, 'Y', 'N', 'N', NULL, 'N', 'The location the file is to be created. NOTE: Must be referenced in INIT.ORA')
/
INSERT INTO GRI_MODULE_PARAMS ( GMP_MODULE, GMP_PARAM, GMP_SEQ, GMP_PARAM_DESCR, GMP_MANDATORY,
GMP_NO_ALLOWED, GMP_WHERE, GMP_TAG_RESTRICTION, GMP_TAG_WHERE, GMP_DEFAULT_TABLE,
GMP_DEFAULT_COLUMN, GMP_DEFAULT_WHERE, GMP_VISIBLE, GMP_GAZETTEER, GMP_LOV, GMP_VAL_GLOBAL,
GMP_WILDCARD, GMP_HINT_TEXT ) VALUES ( 
'UNICLASS', 'CONTRACTOR_ID', 1, 'Contractor Id', 'Y', 1, 'OUN_ORG_UNIT_TYPE=''CO'''
, 'N', NULL, NULL, NULL, NULL, 'Y', 'N', 'Y', NULL, 'N', 'Contractor Identifier')
/
insert into HIG_MODULE_ROLES (
HMR_MODULE
,HMR_ROLE
,HMR_MODE
) select
'UNICLASS'
,'MAI_ADMIN'
,'NORMAL'
from dual
where not exists (
 select 'not exists'
 from HIG_MODULE_ROLES
where HMR_MODULE = 'UNICLASS'
 and HMR_ROLE = 'MAI_ADMIN'
)
/
COMMIT
/
