

Insert into NM_MRG_NIT_DERIVATION
   (NMND_NIT_INV_TYPE, NMND_NMQ_ID, NMND_LAST_REFRESH_DATE, NMND_REFRESH_INTERVAL_DAYS, NMND_LAST_REBUILD_DATE, 
    NMND_REBUILD_INTERVAL_DAYS, NMND_MAINTAIN_HISTORY, NMND_NMU_ID_ADMIN, NMND_WHERE_CLAUSE, NMND_DATE_CREATED, 
    NMND_DATE_MODIFIED, NMND_MODIFIED_BY, NMND_CREATED_BY, nmnd_nt_type, NMND_NGT_GROUP_TYPE)
 Values
   ('SURF', 
   (select nmq_id from nm_mrg_query
   where nmq_unique = 'MQ_SURF'),
   SYSDATE, 7, to_date(SYSDATE), 
    1, 'N', 2058, null, to_date(SYSDATE), 
    to_date(SYSDATE), 'EXOR', 'EXOR', 'RT', 'RT');
---------------------------------------------------------------

--PMS_PM

insert into NM_MRG_ITA_DERIVATION (
NMID_ITA_INV_TYPE, NMID_ITA_ATTRIB_NAME, NMID_SEQ_NO, NMID_DERIVATION)
Values
   ('SURF', 'IIT_CHR_ATTRIB27', 1, 'MRG.BD_NE_ADMIN_UNIT');
   


insert into NM_MRG_ITA_DERIVATION (
NMID_ITA_INV_TYPE, NMID_ITA_ATTRIB_NAME, NMID_SEQ_NO, NMID_DERIVATION)
Values
   ('SURF', 'IIT_CHR_ATTRIB26', 2, 'x_surf_lookup_bd(MRG.PM_C1_PM_PAVETYPE, MRG.NMS_NE_ID_FIRST)');
   
/*
insert into NM_MRG_ITA_DERIVATION (
NMID_ITA_INV_TYPE, NMID_ITA_ATTRIB_NAME, NMID_SEQ_NO, NMID_DERIVATION)
Values
   ('SURF', 'IIT_CHR_ATTRIB26', 3, 'x_surf_lookup(''PMS'',MRG.PM_C1_PM_PAVETYPE)');
*/

insert into NM_MRG_ITA_DERIVATION (
NMID_ITA_INV_TYPE, NMID_ITA_ATTRIB_NAME, NMID_SEQ_NO, NMID_DERIVATION)
Values
   ('SURF', 'IIT_NUM_ATTRIB16', 4, 'MRG.PM_C1_PM_PAVETYPE');
   

insert into NM_MRG_ITA_DERIVATION (
NMID_ITA_INV_TYPE, NMID_ITA_ATTRIB_NAME, NMID_SEQ_NO, NMID_DERIVATION)
Values
   ('SURF', 'IIT_NUM_ATTRIB18', 5, 'x_surf_lookup_n(MRG.PM_C1_PM_PAVETYPE, MRG.NMS_NE_ID_FIRST)');

/*   
insert into NM_MRG_ITA_DERIVATION (
NMID_ITA_INV_TYPE, NMID_ITA_ATTRIB_NAME, NMID_SEQ_NO, NMID_DERIVATION)
Values
   ('SURF', 'IIT_CHR_ATTRIB28', 6, 'x_surf_lookup_v(MRG.PM_C1_PM_PAVETYPE, MRG.BD_SURFACE_TYPE)');
  
*/  

insert into NM_MRG_ITA_DERIVATION (
NMID_ITA_INV_TYPE, NMID_ITA_ATTRIB_NAME, NMID_SEQ_NO, NMID_DERIVATION)
Values
   ('SURF', 'IIT_ADMIN_UNIT', 7, 'MRG.PM_C1_ADMIN_UNIT');
   
------------------------------------------------------------------


INSERT INTO NM_MRG_NIT_DERIVATION_NW (
NMNDN_NMND_NIT_INV_TYPE, NMNDN_NT_TYPE, NMNDN_DATE_CREATED, NMNDN_DATE_MODIFIED, NMNDN_MODIFIED_BY, NMNDN_CREATED_BY)
VALUES
  ('SURF', 'RT', TO_DATE(sysdate), TO_DATE(sysdate), 'EXOR', 'EXOR');

COMMIT;
