SET DEFINE OFF;
MERGE INTO HIGHWAYS.NM_THEMES_ALL A USING
 (SELECT
  2462 as NTH_THEME_ID,
  'IM_NETWORK' as NTH_THEME_NAME,
  'NM_ELEMENTS' as NTH_TABLE_NAME,
  NULL as NTH_WHERE,
  'NE_ID' as NTH_PK_COLUMN,
  'NE_UNIQUE' as NTH_LABEL_COLUMN,
  'NM_ELEMENTS' as NTH_RSE_TABLE_NAME,
  'NE_ID' as NTH_RSE_FK_COLUMN,
  NULL as NTH_ST_CHAIN_COLUMN,
  NULL as NTH_END_CHAIN_COLUMN,
  NULL as NTH_X_COLUMN,
  NULL as NTH_Y_COLUMN,
  NULL as NTH_OFFSET_FIELD,
  'ROAD_NETWORK_SDO' as NTH_FEATURE_TABLE,
  'ROAD_NETWORK_SDO_ID' as NTH_FEATURE_PK_COLUMN,
  'ROAD_NETWORK_SDO_ID' as NTH_FEATURE_FK_COLUMN,
  NULL as NTH_XSP_COLUMN,
  'SHAPE' as NTH_FEATURE_SHAPE_COLUMN,
  'NET' as NTH_HPR_PRODUCT,
  'N' as NTH_LOCATION_UPDATABLE,
  'SDO' as NTH_THEME_TYPE,
  'I' as NTH_DEPENDENCY,
  'S' as NTH_STORAGE,
  'N' as NTH_UPDATE_ON_EDIT,
  'N' as NTH_USE_HISTORY,
  NULL as NTH_START_DATE_COLUMN,
  NULL as NTH_END_DATE_COLUMN,
  1982 as NTH_BASE_TABLE_THEME,
  NULL as NTH_SEQUENCE_NAME,
  'N' as NTH_SNAP_TO_THEME,
  'N' as NTH_LREF_MANDATORY,
  20 as NTH_TOLERANCE,
  1 as NTH_TOL_UNITS,
  'N' as NTH_DYNAMIC_THEME
  FROM DUAL) B
ON (A.NTH_THEME_ID = B.NTH_THEME_ID)
WHEN NOT MATCHED THEN 
INSERT (
  NTH_THEME_ID, NTH_THEME_NAME, NTH_TABLE_NAME, NTH_WHERE, NTH_PK_COLUMN, 
  NTH_LABEL_COLUMN, NTH_RSE_TABLE_NAME, NTH_RSE_FK_COLUMN, NTH_ST_CHAIN_COLUMN, NTH_END_CHAIN_COLUMN, 
  NTH_X_COLUMN, NTH_Y_COLUMN, NTH_OFFSET_FIELD, NTH_FEATURE_TABLE, NTH_FEATURE_PK_COLUMN, 
  NTH_FEATURE_FK_COLUMN, NTH_XSP_COLUMN, NTH_FEATURE_SHAPE_COLUMN, NTH_HPR_PRODUCT, NTH_LOCATION_UPDATABLE, 
  NTH_THEME_TYPE, NTH_DEPENDENCY, NTH_STORAGE, NTH_UPDATE_ON_EDIT, NTH_USE_HISTORY, 
  NTH_START_DATE_COLUMN, NTH_END_DATE_COLUMN, NTH_BASE_TABLE_THEME, NTH_SEQUENCE_NAME, NTH_SNAP_TO_THEME, 
  NTH_LREF_MANDATORY, NTH_TOLERANCE, NTH_TOL_UNITS, NTH_DYNAMIC_THEME)
VALUES (
  NTH_THEME_ID_SEQ.nextval, B.NTH_THEME_NAME, B.NTH_TABLE_NAME, B.NTH_WHERE, B.NTH_PK_COLUMN, 
  B.NTH_LABEL_COLUMN, B.NTH_RSE_TABLE_NAME, B.NTH_RSE_FK_COLUMN, B.NTH_ST_CHAIN_COLUMN, B.NTH_END_CHAIN_COLUMN, 
  B.NTH_X_COLUMN, B.NTH_Y_COLUMN, B.NTH_OFFSET_FIELD, B.NTH_FEATURE_TABLE, B.NTH_FEATURE_PK_COLUMN, 
  B.NTH_FEATURE_FK_COLUMN, B.NTH_XSP_COLUMN, B.NTH_FEATURE_SHAPE_COLUMN, B.NTH_HPR_PRODUCT, B.NTH_LOCATION_UPDATABLE, 
  B.NTH_THEME_TYPE, B.NTH_DEPENDENCY, B.NTH_STORAGE, B.NTH_UPDATE_ON_EDIT, B.NTH_USE_HISTORY, 
  B.NTH_START_DATE_COLUMN, B.NTH_END_DATE_COLUMN, B.NTH_BASE_TABLE_THEME, B.NTH_SEQUENCE_NAME, B.NTH_SNAP_TO_THEME, 
  B.NTH_LREF_MANDATORY, B.NTH_TOLERANCE, B.NTH_TOL_UNITS, B.NTH_DYNAMIC_THEME)
WHEN MATCHED THEN
UPDATE SET 
  A.NTH_THEME_NAME = B.NTH_THEME_NAME,
  A.NTH_TABLE_NAME = B.NTH_TABLE_NAME,
  A.NTH_WHERE = B.NTH_WHERE,
  A.NTH_PK_COLUMN = B.NTH_PK_COLUMN,
  A.NTH_LABEL_COLUMN = B.NTH_LABEL_COLUMN,
  A.NTH_RSE_TABLE_NAME = B.NTH_RSE_TABLE_NAME,
  A.NTH_RSE_FK_COLUMN = B.NTH_RSE_FK_COLUMN,
  A.NTH_ST_CHAIN_COLUMN = B.NTH_ST_CHAIN_COLUMN,
  A.NTH_END_CHAIN_COLUMN = B.NTH_END_CHAIN_COLUMN,
  A.NTH_X_COLUMN = B.NTH_X_COLUMN,
  A.NTH_Y_COLUMN = B.NTH_Y_COLUMN,
  A.NTH_OFFSET_FIELD = B.NTH_OFFSET_FIELD,
  A.NTH_FEATURE_TABLE = B.NTH_FEATURE_TABLE,
  A.NTH_FEATURE_PK_COLUMN = B.NTH_FEATURE_PK_COLUMN,
  A.NTH_FEATURE_FK_COLUMN = B.NTH_FEATURE_FK_COLUMN,
  A.NTH_XSP_COLUMN = B.NTH_XSP_COLUMN,
  A.NTH_FEATURE_SHAPE_COLUMN = B.NTH_FEATURE_SHAPE_COLUMN,
  A.NTH_HPR_PRODUCT = B.NTH_HPR_PRODUCT,
  A.NTH_LOCATION_UPDATABLE = B.NTH_LOCATION_UPDATABLE,
  A.NTH_THEME_TYPE = B.NTH_THEME_TYPE,
  A.NTH_DEPENDENCY = B.NTH_DEPENDENCY,
  A.NTH_STORAGE = B.NTH_STORAGE,
  A.NTH_UPDATE_ON_EDIT = B.NTH_UPDATE_ON_EDIT,
  A.NTH_USE_HISTORY = B.NTH_USE_HISTORY,
  A.NTH_START_DATE_COLUMN = B.NTH_START_DATE_COLUMN,
  A.NTH_END_DATE_COLUMN = B.NTH_END_DATE_COLUMN,
  A.NTH_BASE_TABLE_THEME = B.NTH_BASE_TABLE_THEME,
  A.NTH_SEQUENCE_NAME = B.NTH_SEQUENCE_NAME,
  A.NTH_SNAP_TO_THEME = B.NTH_SNAP_TO_THEME,
  A.NTH_LREF_MANDATORY = B.NTH_LREF_MANDATORY,
  A.NTH_TOLERANCE = B.NTH_TOLERANCE,
  A.NTH_TOL_UNITS = B.NTH_TOL_UNITS,
  A.NTH_DYNAMIC_THEME = B.NTH_DYNAMIC_THEME;

COMMIT;


declare

i_theme_id number;
i_count number;

begin

 select NTH_THEME_ID  into i_theme_id from nm_themes_all where nth_theme_name = 'IM_NETWORK';
 select count(*) into i_count from nm_nw_themes where nnth_nth_theme_id = i_theme_id;
 
 if i_count = 0 then
    Insert into HIGHWAYS.NM_NW_THEMES  (NNTH_NLT_ID, NNTH_NTH_THEME_ID) Values   (21, i_theme_id);
    commit;
 end if;

end;
/
