SET DEFINE OFF;
Insert into EXOR.NM_INV_TYPES
   (NIT_INV_TYPE, NIT_PNT_OR_CONT, NIT_X_SECT_ALLOW_FLAG, NIT_ELEC_DRAIN_CARR, NIT_CONTIGUOUS, 
    NIT_REPLACEABLE, NIT_EXCLUSIVE, NIT_CATEGORY, NIT_DESCR, NIT_LINEAR, 
    NIT_USE_XY, NIT_MULTIPLE_ALLOWED, NIT_END_LOC_ONLY, NIT_VIEW_NAME, NIT_START_DATE, 
    NIT_FLEX_ITEM_FLAG, NIT_ADMIN_TYPE, NIT_TOP, NIT_UPDATE_ALLOWED, NIT_DATE_CREATED, 
    NIT_DATE_MODIFIED, NIT_MODIFIED_BY, NIT_CREATED_BY)
 Values
   ('METP', 'P', 'N', 'C', 'N', 
    'N', 'N', 'I', 'Parent Asset to store meta-data about other assets', 'N', 
    'N', 'N', 'N', 'V_NM_METP', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'N', 'INV', 'Y', 'Y', TO_DATE('05/31/2013 22:31:12', 'MM/DD/YYYY HH24:MI:SS'), 
    TO_DATE('05/31/2013 22:31:12', 'MM/DD/YYYY HH24:MI:SS'), 'EXOR', 'EXOR');
COMMIT;

Insert Into NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE) Values ('METP', 'IIT_CHR_ATTRIB26', 'Y', 1, 'N', 'VARCHAR2', 5, 'TYPE', 'Y', 'TYPE', 'TYPE', to_date(sysdate), 'Y', 'N', 'N', to_date(sysdate), to_date(sysdate), 'EXOR', 'EXOR', 'Y', 5, 'Y', 'UPPER');
Insert Into NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE) Values ('METP', 'IIT_CHR_ATTRIB27', 'Y', 2, 'N', 'VARCHAR2', 50, 'ASSET NAME', 'Y', 'ASSET NAME', 'ASSET_NAME', to_date(sysdate), 'Y', 'N', 'N', to_date(sysdate), to_date(sysdate), 'EXOR', 'EXOR', 'Y', 50, 'Y', 'UPPER');
Insert Into NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE) Values ('METP', 'IIT_CHR_ATTRIB28', 'Y', 3, 'N', 'VARCHAR2', 20, 'OWNER', 'Y', 'OWNER', 'OWNER', to_date(sysdate), 'Y', 'N', 'N', to_date(sysdate), to_date(sysdate), 'EXOR', 'EXOR', 'Y', 20, 'Y', 'UPPER');
Insert Into NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE) Values ('METP', 'IIT_CHR_ATTRIB29', 'Y', 4, 'N', 'VARCHAR2', 20, 'CUSTODIAN', 'Y', 'CUSTODIAN', 'CUSTODIAN', to_date(sysdate), 'Y', 'N', 'N', to_date(sysdate), to_date(sysdate), 'EXOR', 'EXOR', 'Y', 20, 'Y', 'UPPER');
Insert Into NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE) Values ('METP', 'IIT_CHR_ATTRIB30', 'Y', 5, 'N', 'VARCHAR2', 50, 'ROADWAY EXTENT', 'Y', 'ROADWAY EXTENT', 'ROADWAY_EXTENT', to_date(sysdate), 'Y', 'N', 'N', to_date(sysdate), to_date(sysdate), 'EXOR', 'EXOR', 'Y', 50, 'Y', 'UPPER');
Insert Into NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE) Values ('METP', 'IIT_CHR_ATTRIB31', 'Y', 6, 'N', 'VARCHAR2', 1, 'UPDATE CYCLE', 'Y', 'UPDATE CYCLE', 'UPDATE_CYCLE', to_date(sysdate), 'Y', 'N', 'N', to_date(sysdate), to_date(sysdate), 'EXOR', 'EXOR', 'Y', 1, 'Y', 'UPPER');
Insert Into NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE) Values ('METP', 'IIT_CHR_ATTRIB66', 'Y', 7, 'N', 'VARCHAR2', 255, 'UPDATE COMMENT', 'Y', 'UPDATE COMMENT', 'UPDATE_COMMENT', to_date(sysdate), 'Y', 'N', 'N', to_date(sysdate), to_date(sysdate), 'EXOR', 'EXOR', 'Y', 255, 'Y', 'UPPER');
Insert Into NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE) Values ('METP', 'IIT_CHR_ATTRIB32', 'Y', 8, 'N', 'VARCHAR2', 20, 'ASSETS TO REVIEW', 'Y', 'ASSETS TO REVIEW', 'ASSETS_TO_REVIEW', to_date(sysdate), 'Y', 'N', 'N', to_date(sysdate), to_date(sysdate), 'EXOR', 'EXOR', 'Y', 20, 'Y', 'UPPER');
Insert Into NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE) Values ('METP', 'IIT_CHR_ATTRIB33', 'Y', 9, 'N', 'VARCHAR2', 50, 'AFFECTED PROGRAMS', 'Y', 'AFFECTED PROGRAMS', 'AFFECTED_PROGRAMS', to_date(sysdate), 'Y', 'N', 'N', to_date(sysdate), to_date(sysdate), 'EXOR', 'EXOR', 'Y', 50, 'Y', 'UPPER');
Insert Into NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE) Values ('METP', 'IIT_CHR_ATTRIB34', 'Y', 10, 'N', 'VARCHAR2', 5, 'REPORT LEVEL', 'Y', 'REPORT LEVEL', 'REPORT_LEVEL', to_date(sysdate), 'Y', 'N', 'N', to_date(sysdate), to_date(sysdate), 'EXOR', 'EXOR', 'Y', 5, 'Y', 'UPPER');
Insert Into NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE) Values ('METP', 'IIT_CHR_ATTRIB35', 'Y', 11, 'N', 'VARCHAR2', 50, 'DOCUMENTATION', 'Y', 'DOCUMENTATION', 'DOCUMENTATION', to_date(sysdate), 'Y', 'N', 'N', to_date(sysdate), to_date(sysdate), 'EXOR', 'EXOR', 'Y', 50, 'Y', 'UPPER');


INSERT INTO NM_INV_TYPE_ROLES values
('METP', 'INV_ALL', 'NORMAL');
INSERT INTO NM_INV_TYPE_ROLES values
('METP', 'INV_READONLY', 'READONLY');

COMMIT;





Insert into EXOR.NM_INV_TYPES
   (NIT_INV_TYPE, NIT_PNT_OR_CONT, NIT_X_SECT_ALLOW_FLAG, NIT_ELEC_DRAIN_CARR, NIT_CONTIGUOUS, 
    NIT_REPLACEABLE, NIT_EXCLUSIVE, NIT_CATEGORY, NIT_DESCR, NIT_LINEAR, 
    NIT_USE_XY, NIT_MULTIPLE_ALLOWED, NIT_END_LOC_ONLY, NIT_VIEW_NAME, NIT_START_DATE, 
    NIT_FLEX_ITEM_FLAG, NIT_ADMIN_TYPE, NIT_TOP, NIT_UPDATE_ALLOWED, NIT_DATE_CREATED, 
    NIT_DATE_MODIFIED, NIT_MODIFIED_BY, NIT_CREATED_BY)
 Values
   ('METC', 'P', 'N', 'C', 'N', 
    'N', 'N', 'I', 'Parent Asset to store meta-data about other assets', 'N', 
    'N', 'N', 'N', 'V_NM_METC', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    'N', 'INV', 'N', 'Y', trunc(sysdate), 
     trunc(sysdate), 'EXOR', 'EXOR');
COMMIT;


Insert into EXOR.NM_INV_TYPE_GROUPINGS_ALL
   (ITG_INV_TYPE, ITG_PARENT_INV_TYPE, ITG_MANDATORY, ITG_RELATION, ITG_START_DATE, 
    ITG_DATE_CREATED, ITG_DATE_MODIFIED, ITG_MODIFIED_BY, ITG_CREATED_BY)
 Values
   ('METC', 'METP', 'N', 'NONE', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 
    TO_DATE('05/31/2013 22:48:06', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/31/2013 22:48:06', 'MM/DD/YYYY HH24:MI:SS'), 'EXOR', 'EXOR');
COMMIT;

Insert Into NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE) Values ('METC', 'IIT_CHR_ATTRIB26', 'Y', 1, 'N', 'VARCHAR2', 5, 'TYPE', 'Y', 'TYPE', 'TYPE', to_date(sysdate), 'Y', 'N', 'N', to_date(sysdate), to_date(sysdate), 'EXOR', 'EXOR', 'Y', 5, 'Y', 'UPPER');
Insert Into NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE) Values ('METC', 'IIT_CHR_ATTRIB27', 'Y', 2, 'N', 'VARCHAR2', 50, 'ATTRIBUTE', 'Y', 'ATTRIBUTE', 'ATTRIBUTE', to_date(sysdate), 'Y', 'N', 'N', to_date(sysdate), to_date(sysdate), 'EXOR', 'EXOR', 'Y', 50, 'Y', 'UPPER');
Insert Into NM_INV_TYPE_ATTRIBS (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE) Values ('METC', 'IIT_CHR_ATTRIB28', 'Y', 3, 'N', 'VARCHAR2', 20, 'ACCESS GROUP', 'Y', 'ACCESS_GROUP', 'ACCESS_GROUP', to_date(sysdate), 'Y', 'N', 'N', to_date(sysdate), to_date(sysdate), 'EXOR', 'EXOR', 'Y', 20, 'Y', 'UPPER');

commit;

INSERT INTO NM_INV_TYPE_ROLES values
('METC', 'INV_ALL', 'NORMAL');
INSERT INTO NM_INV_TYPE_ROLES values
('METC', 'INV_READONLY', 'READONLY');

COMMIT;


exec nm3inv.create_view ('METP', false);
exec nm3inv.create_view ('METC', false);
