Drop MATERIALIZED VIEW XCTDOT_PROJ_FT_V_SDO ;

CREATE MATERIALIZED VIEW ATLAS.XCTDOT_PROJ_FT_V_SDO 
TABLESPACE ATLAS
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
REFRESH FORCE
START WITH TO_DATE('01-02-2014','dd-mm-yyyy')
NEXT TRUNC (SYSDATE + 1)   + 0 / 24 
WITH PRIMARY KEY
AS
select * from XCTDOT_PROJ_FT_V_SDO_TMP
;



CREATE INDEX ATLAS.XCTDOT_PROJ_FT_V_SDO_SPIDX ON ATLAS.XCTDOT_PROJ_FT_V_SDO
(GEOLOC)
INDEXTYPE IS MDSYS.SPATIAL_INDEX
PARAMETERS('sdo_indx_dims=2')
NOPARALLEL;


CREATE UNIQUE INDEX ATLAS.XCTDOT_PROJ_FT_V_SDO_UK ON ATLAS.XCTDOT_PROJ_FT_V_SDO
(OBJECTID)
LOGGING
TABLESPACE ATLAS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


