Drop MATERIALIZED VIEW ATLAS.XCTDOT_PW_PROJ_MV ;

CREATE MATERIALIZED VIEW ATLAS.XCTDOT_PW_PROJ_MV 
TABLESPACE ATLAS
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
REFRESH FORCE
START WITH TO_DATE('01-02-2014','dd-mm-yyyy')
NEXT TRUNC (SYSDATE + 1)   + 0 / 24 
WITH PRIMARY KEY
AS
SELECT 
	"PROJECTTYPEID" 												PROJECTTYPEID,
	CAST ("PROJECT_Project_Number" 				AS VARCHAR2 (25))	PROJ_PROJECT_NUMBER,
	CAST ("PROJECT_Project_Description" 		AS VARCHAR2 (255))	PROJECT_DESCRIPTION,
	CAST ("PROJECT_Digitally_Signed" 			AS VARCHAR2 (255))	DIGITALLY_SIGNED,
	CAST ("PROJECT_Town_Number" 				AS VARCHAR2 (255))	TOWN_NUMBER,
	CAST ("PROJECT_Routes" 						AS VARCHAR2 (255))	ROUTES,
	CAST ("PROJECT_Bridge_Number"				AS VARCHAR2 (15))	BRIDGE_NUMBER,
	CAST ("PROJECT_Project_Type" 				AS VARCHAR2 (25))	PROJECT_TYPE,
	CAST ("Project_Phase" 						AS VARCHAR2 (35))	PROJECT_PHASE,
	CAST ("PROJECT_Project_Current_Phase" 		AS VARCHAR2 (35))	CURRENT_PHASE,
	CAST ("PROJECT_Consultant_Designed_" 		AS VARCHAR2 (255))	CONSULTANT_DESIGNED,
	CAST ("PROJECT_FHWA_Oversight" 				AS VARCHAR2 (255))	FHWA_OVERSIGHT,
	"PROJECT_Percent_Design_Complet" 								PERCENT_DESIGN_COMPLETE,
	CAST ("PROJECT_CTDOT_Project_Manager" 		AS VARCHAR2 (50))	CTDOT_PROJECT_MANAGER,
	CAST ("PROJECT_CTDOT_Project_Engineer" 		AS VARCHAR2 (50))	CTDOT_PROJECT_ENGINEER,
	"PROJECT_Constr_FDP" 											CONSTR_FDP,
	"PROJECT_Constr_DCD" 											CONSTR_DCD,
	"PROJECT_Constr_ADV" 											CONSTR_ADV,
	"PROJECT_CON_CCD" 												CON_CCD,
	"PROJECT_ROW_AUTH" 												ROW_AUTH,
	CAST ("PROJECT_Contractor" 					AS VARCHAR2 (255))	CONTRACTOR,
	CAST ("PROJECT_DISTRICT" 					AS VARCHAR2 (255))	DISTRICT,
	"PROJECT_Construction_Percent_C" 								CONSTR_PERCENT_COMPLETE,
	CAST ("PROJECT_Cons_Project_Manager" 		AS VARCHAR2 (255))	CONSTR_PROJECT_MANAGER,
	CAST ("PROJECT_Cons_Project_Inspector" 		AS VARCHAR2 (255))	CONSTR_PROJECT_INSPECTOR,
	"PROJECT_Constr_Completed" 										CONSTR_COMPLETED,
	CAST ("PROJECT_Remarks" 					AS VARCHAR2 (255))	REMARKS,
	CAST ("PROJECT_Final_Cost" 					AS VARCHAR2 (255))	FINAL_COST,
	CAST ("PROJECT_General_Description" 		AS VARCHAR2 (255))	GENERAL_DESCRIPTION,
	CAST ("PROJECT_SIGNAL_SYSTEM_NO" 			AS VARCHAR2 (255))	SIGNAL_SYSTEM_NO,
	CAST ("PROJECT_Design__Consultant_Eng" 		AS VARCHAR2 (255))	DESIGN_CONSULTING_ENG,
	CAST ("PROJECT_Financial__PE_Cost_Est" 		AS VARCHAR2 (255))	FIN_PE_COST_EST,
	CAST ("PROJECT_Finacial__Construction" 		AS VARCHAR2 (255))	FINANCIAL_CONSTRUCTION,
	CAST ("PROJECT_Construction__As_Built" 		AS VARCHAR2 (255))	CONSTRUCTION_AS_BUILT,
	CAST ("PROJECT_ASSETS__Bridge_Numbers" 		AS VARCHAR2 (255))	ASSETS_BRIDGE_NUMBERS,
	CAST ("PROJECT_Assets__Towns" 				AS VARCHAR2 (255))	ASSETS_TOWNS,
	CAST ("PROJECT_General__Program_Numbe" 		AS VARCHAR2 (25))	PROGRAM_NUMBER,
	CAST ("PROJECT_test" 						AS VARCHAR2 (255))	TEST,
	CAST ("PROJECT_GENERAL__Project_Numbe" 		AS VARCHAR2 (255))	GEN_PROJECT_NUMBER,
	CAST ("PROJECT_GENERAL__Project_Numb1" 		AS VARCHAR2 (75))	GEN_PROJ_NUM1,
	CAST ("PROJECT_Financial__Initial_Con" 		AS VARCHAR2 (255))	FIN_INITIAL_CON,
	CAST ("PROJECT_Finacial__Revised_Cont" 		AS VARCHAR2 (255))	FIN_REVISED_CONT,
	CAST ("PROJECT_Financial__Revised_Con" 		as number)			FIN_REVISED_CON,
	CAST ("PROJECT_Financial__Final_Cost_" 		as number)			FIN_FINAL_COST,
	CAST ("PROJECT_Financial__Original_Co" 		as number)			FIN_ORIGINAL_COST,
	CAST ("test1" 								AS VARCHAR2 (420))	TEST1,
	CAST ("PROJECT_test_2" 						AS VARCHAR2 (1020))	TEST2,
	CAST ("PROJECT_ASSETS_Test3" 				AS VARCHAR2 (255))	TEST3,
	CAST ("PROJECT_GENERAL__CADD_Standard" 		AS VARCHAR2 (255))	GEN_CADD_STANDARD,
	CAST ("PROJECT_ASSETS__Signal_System_" 		AS VARCHAR2 (1020))	ASSETS_SIGNAL_SYSTEM,
	CAST ("PROJECT_ASSETS__Bridge_No" 			AS VARCHAR2 (1020))	ASSETS_BRIDGE_NO,
	CAST ("PROJECT_ASSETS__Bridge_Nos_in_" 		AS VARCHAR2 (1020))	ASSETS_BRIDGE_NOS_IN,
	CAST ("PROJECT_ASSETS__Sign_Structure" 		AS VARCHAR2 (255))	ASSETS_SIGN_STRUCTURE
  FROM dbo.i_ctdot_transportation_project@TO_CT_PW.BENTLEYHOSTING.COM
  --where rownum <10
  ;


