SET DEFINE OFF;
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'PROJECTTYPEID', 'N', 1, 'N', 
    'NUMBER', 10, 'PROJECT_TYPE_ID', 'N', 'PROJECT_TYPE_ID', 
    'PROJECT_TYPE_ID', TO_DATE('02/05/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('02/05/2014 16:46:46', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('02/05/2014 16:46:46', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    5, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'PROJ_NAME', 'N', 2, 'N', 
    'VARCHAR2', 63, 'Project Number', 'N', 'PROJ_PROJECT_NUMBER', 
    'PROJ_PROJECT_NUMBER', TO_DATE('02/05/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('02/05/2014 16:46:47', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('04/16/2014 18:25:50', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    50, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'GEN_DESCRIPTION', 'N', 7, 'N', 
    'VARCHAR2', 500, 'Gen - General Description', 'N', 'PROJECT_DESCRIPTION', 
    'PROJECT_DESCRIPTION', TO_DATE('02/05/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('02/05/2014 16:46:47', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:24:11', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    20, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'LOC_TOWNS', 'N', 13, 'N', 
    'VARCHAR2', 500, 'Loc - Towns', 'N', 'TOWN_NUMBER', 
    'TOWN_NUMBER', TO_DATE('02/05/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('02/05/2014 16:46:48', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:28:48', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    50, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'GEN_PROGRAM_NUMBE', 'N', 4, 'N', 
    'VARCHAR2', 25, 'Gen - Program Number', 'N', 'PROG_NUM', 
    'PROG_NUM', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 15:35:46', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:20:54', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    10, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'FHWA_OVERSIGHT', 'N', 8, 'N', 
    'VARCHAR2', 200, 'Gen - FHW  Project Oversight', 'N', 'FED_PROJ_OVERSIGHT', 
    'FED_PROJ_OVERSIGHT', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 15:43:27', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:24:58', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    10, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'PROJ_CURRENT_PHASE', 'N', 10, 'N', 
    'VARCHAR2', 35, 'Gen - Project Current Phase', 'N', 'PROJ_CURR_PHASE', 
    'PROJ_CURR_PHASE', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 15:44:47', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:26:57', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    10, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'GEN_PROJECT_SCOPE_CODE', 'N', 11, 'N', 
    'VARCHAR2', 25, 'Gen - Project Scope Code', 'N', 'PROJ_SCOPE_CODE', 
    'PROJ_SCOPE_CODE', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 15:46:38', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:27:22', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    10, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'LOC_ROUTES', 'N', 14, 'N', 
    'VARCHAR2', 500, 'Loc - Routes', 'N', 'LOC_ROUTES', 
    'LOC_ROUTES', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 15:47:46', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:28:52', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    20, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'LOC_BEGIN_MILEPOINT', 'N', 15, 'N', 
    'NUMBER', 38, 'Loc - Begin Milepoint', 'N', 'LOC_BEGIN_MILEPOINT', 
    'LOC_BEGIN_MILEPOINT', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 15:49:07', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:28:57', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    8, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'LOC_END_MILEPOINT', 'N', 16, 'N', 
    'NUMBER', 38, 'Loc - End Milepoint', 'N', 'LOC_END_MILEPOINT', 
    'LOC_END_MILEPOINT', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 15:49:51', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:29:00', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    8, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'ASSETS_PAVEMENT_TREAT', 'N', 17, 'N', 
    'VARCHAR2', 75, 'Assets - Pavement Treatment', 'N', 'ASS_PAVE_TREATMENT', 
    'ASS_PAVE_TREATMENT', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 15:50:58', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:29:09', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    20, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'ASSETS_BRIDGE_NOS_IN', 'N', 18, 'N', 
    'VARCHAR2', 500, 'Assets - Bridge Numbers', 'N', 'ASS_BRIDGE_NOS', 
    'ASS_BRIDGE_NOS', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 15:52:16', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:29:18', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    30, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'ASSETS_SIGN_STRUCTURE', 'N', 19, 'N', 
    'VARCHAR2', 500, 'Assets - Sign Structures', 'N', 'ASS_SIGN_STRUCTURES', 
    'ASS_SIGN_STRUCTURES', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 15:53:13', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:29:26', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    30, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'ASSETS_SIGNAL_SYSTEM', 'N', 20, 'N', 
    'VARCHAR2', 500, 'Assets - Traffic Signal System', 'N', 'ASS_TRAF_SIG_SYS', 
    'ASS_TRAF_SIG_SYS', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 15:54:21', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:29:33', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    30, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'ASSETS_RETAINING_WALL', 'N', 21, 'N', 
    'VARCHAR2', 500, 'Assets - Retaining Walls', 'N', 'ASS_RET_WALLS', 
    'ASS_RET_WALLS', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 15:57:11', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:29:36', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    20, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'SCHED_RPM_DATE', 'N', 22, 'N', 
    'DATE', 7, 'Sched - RPM Date', 'N', 'RPM_DATE', 
    'RPM_DATE', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:02:43', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:34:23', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    8, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'SCHED_INIT', 'N', 23, 'N', 
    'DATE', 7, 'Sched - Project Initiation', 'N', 'PROJ_INIT', 
    'PROJ_INIT', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:03:40', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:34:26', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    8, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'SCHED_DATE_OF_DES_APPR', 'N', 24, 'N', 
    'DATE', 7, 'Sched - Design Approval', 'N', 'DES_APPROVAL', 
    'DES_APPROVAL', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:04:40', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:34:29', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    8, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'SCHED_FDP_RPM', 'N', 26, 'N', 
    'DATE', 7, 'Sched - FDP at RPM', 'N', 'FDP_AT_RPM', 
    'FDP_AT_RPM', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:05:56', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:34:37', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    8, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'SCHED_FDP_DES', 'N', 27, 'N', 
    'DATE', 7, 'Sched - FDP at Design Approval', 'N', 'FDP_AT_DES', 
    'FDP_AT_DES', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:08:03', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:34:47', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    8, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'SCHED_CURRENT_FDP', 'N', 28, 'N', 
    'DATE', 7, 'Sched - FDP Current', 'N', 'FDP_CURRENT', 
    'FDP_CURRENT', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:08:55', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:34:51', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    8, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'SCHED_CURRENT_DCD', 'N', 29, 'N', 
    'DATE', 7, 'Sched - DCD Current', 'N', 'DCD_CURRENT', 
    'DCD_CURRENT', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:09:50', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:34:58', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    8, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'SCHED_ADV_CURRENT', 'N', 30, 'N', 
    'DATE', 7, 'Sched - ADV Current', 'N', 'ADV_CURRENT', 
    'ADV_CURRENT', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:10:57', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:35:03', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    8, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'SCHED_AWARD', 'N', 32, 'N', 
    'DATE', 7, 'Sched - Contract Award', 'N', 'CONTRACT_AWARD', 
    'CONTRACT_AWARD', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:11:46', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:35:37', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    8, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'SCHED_NOTICE_TO_PR', 'N', 33, 'N', 
    'DATE', 7, 'Sched - Notice to Proceed', 'N', 'NOTICE_TO_PROCEED', 
    'NOTICE_TO_PROCEED', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:12:53', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:35:48', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    8, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'SCHED_EST_CCD_AT_AWARD', 'N', 34, 'N', 
    'DATE', 7, 'Sched - Est CCD at Award', 'N', 'EST_CCD_AT_AWARD', 
    'EST_CCD_AT_AWARD', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:13:53', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:36:04', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    8, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'SCHED_CURRENT_EST_CCD', 'N', 35, 'N', 
    'DATE', 7, 'Sched - Current Estimated CCD', 'N', 'EST_CCD_CURRENT', 
    'EST_CCD_CURRENT', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:14:57', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 18:30:08', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    8, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'SCHED_CONS_COMPLETION', 'N', 36, 'N', 
    'DATE', 7, 'Sched - Constr Completion', 'N', 'CONST_COMPLETION', 
    'CONST_COMPLETIONN', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:15:53', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:36:53', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    8, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'COST_PE_EST_AT_DES_APPR', 'N', 37, 'N', 
    'NUMBER', 38, 'Cost - PE Est at Des Approval', 'N', 'PE_EST_AT_DES_APPROVAL', 
    'PE_EST_AT_DES_APPROVAL', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:17:01', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:37:19', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    10, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'COST_PE_EXPENDITURES', 'N', 38, 'N', 
    'NUMBER', 38, 'Cost - PE Expenditures', 'N', 'PE_EXPENDITURES', 
    'PE_EXPENDITURES', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:17:50', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:37:35', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    10, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'COST_ROW_ESTBUDGET', 'N', 39, 'N', 
    'NUMBER', 38, 'Cost - ROW Est Budget', 'N', 'ROW_EST_BUDGET', 
    'ROW_EST_BUDGET', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:31:54', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:38:02', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    8, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'COST_CONS_TOT_EST_AT_RPM', 'N', 41, 'N', 
    'NUMBER', 38, 'Cost - Const Tot Est at RPM', 'N', 'CONS_TOT_EST_AT_RPM', 
    'CONS_TOT_EST_AT_RPM', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:38:44', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 17:53:10', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    10, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'COST_CONS_TOT_EST_AT_DES_APPR', 'N', 42, 'N', 
    'NUMBER', 38, 'Cost - Cons Tot Est at Des App', 'N', 'TOT_EST_AT_DES_APPROV', 
    'TOT_EST_AT_DES_APPROV', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:43:34', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 17:53:48', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    10, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'COST_CONS_TOT_EST_AT_DCD', 'N', 43, 'N', 
    'NUMBER', 38, 'Cost - Const Total Est at DCD', 'N', 'CONS_TOT_EST_AT_DCD', 
    'CONS_TOT_EST_AT_DCD', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:44:54', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 17:53:51', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    10, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'COST_CONS_ORIG_CONTRACT_VAL', 'N', 44, 'N', 
    'NUMBER', 38, 'Cost - Const Orig Contract Val', 'N', 'CONS_ORIG_CONT_VAL', 
    'CONS_ORIG_CONT_VAL', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:48:01', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 17:53:54', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    10, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'COST_REVISED_ORIG_CONTRACT_VAL', 'N', 45, 'N', 
    'NUMBER', 38, 'Cost - Const Rev Contact Val', 'N', 'CONS_REV_ORIG_CONT_VAL', 
    'CONS_REV_ORIG_CONT_VAL', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:49:35', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 17:54:56', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    10, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'COST_CURRENT_CONS_TOT_EST', 'N', 46, 'N', 
    'NUMBER', 38, 'Cost - Current Const Total Est', 'N', 'CURRENT_CONS_TOTAL_EST', 
    'CURRENT_CONS_TOTAL_EST', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:50:53', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 17:55:31', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    10, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'COST_TOT_PROJ_EST', 'N', 47, 'N', 
    'NUMBER', 38, 'Cost - Total Project Cost Est', 'N', 'TOTAL_PROJ_COST_EST', 
    'TOTAL_PROJ_COST_EST', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:52:02', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 17:56:38', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    10, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'DES_PERCENT_COMPLETE', 'N', 49, 'N', 
    'NUMBER', 10, 'Design - Percent Complete', 'N', 'DESIGN_PERCENT_COMPLETE', 
    'DESIGN_PERCENT_COMPLETE', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:53:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 18:09:49', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    4, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'DES_PROJ_MAN', 'N', 51, 'N', 
    'VARCHAR2', 50, 'Design - Project Manager', 'N', 'DES_PROJ_MAN', 
    'DES_PROJ_MAN', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:54:59', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 18:23:04', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    20, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'DES_CONSULTANT_ENG', 'N', 52, 'N', 
    'VARCHAR2', 200, 'Design - Consultant Engineer', 'N', 'DES_CONS_ENG', 
    'DES_CONS_ENG', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:57:56', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 18:23:33', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    20, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'DES_PROJECT_ENGINEER', 'N', 53, 'N', 
    'VARCHAR2', 50, 'Design - Project Engineer', 'N', 'DES_PROJ_ENG', 
    'DES_PROJ_ENG', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 16:58:51', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 18:23:46', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    20, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'CONS_PERCENT_COMPLETE', 'N', 54, 'N', 
    'NUMBER', 10, 'Constr - Percent Complete', 'N', 'CONST_PERCENT_COMPLETE', 
    'CONST_PERCENT_COMPLETE', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('03/13/2014 17:00:56', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 18:43:26', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    4, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'GEN_PROJ_INHERITED', 'N', 3, 'N', 
    'VARCHAR2', 40, 'Gen - Project Inherited', 'N', 'GEN_PROJ_INHERITED', 
    'GEN_PROJ_INHERITED', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('05/22/2014 16:20:28', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:20:28', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    4, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'GEN_PHASE_TYPES_INCL', 'N', 9, 'N', 
    'VARCHAR2', 20, 'Gen - Phase Types Included', 'N', 'GEN_PHASE_TYPES_INCL', 
    'GEN_PHASE_TYPES_INCL', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('05/22/2014 16:26:40', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:26:40', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    10, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'GEN_STIP_STATUS', 'N', 12, 'N', 
    'VARCHAR2', 20, 'Gen - STIP Status', 'N', 'GEN_STIP_STATUS', 
    'GEN_STIP_STATUS', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('05/22/2014 16:28:31', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:28:31', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    4, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'SCHED_ROW_INIT', 'N', 25, 'N', 
    'VARCHAR2', 200, 'Sched - ROW Initiation', 'N', 'SCHED_ROW_INIT', 
    'SCHED_ROW_INIT', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('05/22/2014 16:31:37', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:34:32', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    9, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'SCHED_CONST_INIT', 'N', 31, 'N', 
    'DATE', 7, 'Sched - Constr Initiation', 'N', 'SCHED_CONSTR_INIT', 
    'SCHED_CONSTR_INIT', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('05/22/2014 16:34:10', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:35:15', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    9, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'COST_ROW_EXPENDITURES', 'N', 40, 'N', 
    'NUMBER', 38, 'Cost - ROW Expenditures', 'N', 'COST_ROW_EXPEND', 
    'COST_ROW_EXPEND', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('05/22/2014 16:39:50', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 16:39:50', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    12, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'COST_CONST_EXP', 'N', 48, 'N', 
    'NUMBER', 38, 'Cost - Constr Expenditures', 'N', 'COST_CONSTR_EXPEND', 
    'COST_CONSTR_EXPEND', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('05/22/2014 18:08:02', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 18:08:02', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    12, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'CONS_PRIMARY_INSPECTOR', 'N', 55, 'N', 
    'VARCHAR2', 75, 'Constr - Primary Inspector', 'N', 'CONSTR_PRIMARY_INSPECTOR', 
    'CONSTR_PRIMARY_INSPECTOR', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('05/22/2014 18:37:27', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 18:43:21', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    20, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'CONS_MANAGER', 'N', 56, 'N', 
    'VARCHAR2', 200, 'Constr - Project Manager', 'N', 'CONSTR_PROJ_MANAGER', 
    'CONSTR_PROJ_MANAGER', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('05/22/2014 18:43:13', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 18:43:29', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    30, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'CONS_SUPERVISING_ENGINEER', 'N', 57, 'N', 
    'VARCHAR2', 75, 'Constr - Supervising Engineer', 'N', 'CONSTR_SUPERVISING_ENG', 
    'CONSTR_SUPERVISING_ENG', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('05/22/2014 18:46:53', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 18:46:53', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    20, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'CONS_SUPERVISING_ENG_EMAIL', 'N', 58, 'N', 
    'VARCHAR2', 500, 'Constr - Supervising Eng Email', 'N', 'CONSTR_SUPER_ENG_EMAIL', 
    'CONSTR_SUPER_ENG_EMAIL', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('05/22/2014 18:48:01', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 18:49:35', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'N', 
    'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'CONS_INSPECTOR', 'N', 59, 'N', 
    'VARCHAR2', 500, 'Constr - Project Inspector', 'N', 'CONSTR_PROJ_INSPECTOR', 
    'CONSTR_PROJ_INSPECTOR', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('05/22/2014 18:49:14', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 18:49:14', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    20, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'PROJECT_DISTRICT', 'N', 60, 'N', 
    'VARCHAR2', 200, 'Constr - District', 'N', 'CONSTR_DISTRICT', 
    'CONSTR_DISTRICT', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('05/22/2014 18:50:52', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 18:50:52', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    3, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'CONTRACTOR', 'N', 61, 'N', 
    'VARCHAR2', 200, 'Constr - Contractor', 'N', 'CONSTR_CONTRACTOR', 
    'CONSTR_CONTRACTOR', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('05/22/2014 18:51:52', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 18:51:52', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    20, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'CONS_AS_BUILT', 'N', 62, 'N', 
    'VARCHAR2', 200, 'Constr - As Built Record', 'N', 'CONSTR_AS_BUILT', 
    'CONSTR_AS_BUILT', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('05/22/2014 18:52:45', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 18:52:45', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    10, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'CONS_CONSULTANT_INSPECT_FIRM', 'N', 63, 'N', 
    'VARCHAR2', 75, 'Constr - Consultant Insp Firm', 'N', 'CONSTR_INSP_FIRM', 
    'CONSTR_INSP_FIRM', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('05/22/2014 18:53:56', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 18:53:56', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'N', 
    'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'PROJ_END_DATE', 'N', 65, 'N', 
    'NUMBER', 38, 'Project End Date', 'N', 'PROJ_END_DATE', 
    'PROJ_END_DATE', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('05/22/2014 18:55:46', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 18:58:02', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    5, 'N', 'UPPER');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'PROJ_END_DATE_REASON', 'N', 66, 'N', 
    'VARCHAR2', 25, 'Project End Date Reason', 'N', 'PROJ_END_DATE_REASON', 
    'PROJ_END_DATE_REASON', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('05/22/2014 18:57:45', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 18:57:45', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    5, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'PROJ_DESCRIPTION', 'N', 71, 'N', 
    'VARCHAR2', 127, 'Project Description', 'N', 'O_PROJ_DESC', 
    'O_PROJ_DESC', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'N', 'N', 'N', 
    TO_DATE('04/03/2014 16:17:28', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 18:26:47', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'N', 
    'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'PROJ_TYPE', 'N', 6, 'N', 
    'VARCHAR2', 25, 'Gen - CTDOT Improvement Type', 'N', 'CTDOT_IMPR_TYPE', 
    'CTDOT_IMPR_TYPE', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('04/03/2014 16:29:59', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 18:27:59', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    20, 'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'CONS_DES_PRIMARY', 'N', 50, 'N', 
    'VARCHAR2', 200, 'Design - Primary Designer', 'N', 'CONS_DES_PRIM', 
    'CONS_DES_PRIM', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'N', 'N', 'N', 
    TO_DATE('04/03/2014 17:00:36', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 18:22:29', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'N', 
    'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'DES_PROJ_MAN_EMAIL', 'N', 51, 'N', 
    'VARCHAR2', 50, 'Design - Project Manager Email', 'N', 'DES_PROJ_MAN_EMAIL', 
    'DES_PROJ_MAN_EMAIL', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'N', 'N', 'N', 
    TO_DATE('04/03/2014 17:10:13', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 18:23:22', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'N', 
    'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'PROJ_REMARKS', 'N', 64, 'N', 
    'VARCHAR2', 200, 'Remarks', 'N', 'PROJ_REMARKS', 
    'PROJ_REMARKS', TO_DATE('01/01/1901 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'N', 'N', 'N', 
    TO_DATE('04/03/2014 17:12:04', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 18:54:20', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'N', 
    'N', 'MIXED');
Insert into ATLAS.NM_INV_TYPE_ATTRIBS
   (ITA_INV_TYPE, ITA_ATTRIB_NAME, ITA_DYNAMIC_ATTRIB, ITA_DISP_SEQ_NO, ITA_MANDATORY_YN, 
    ITA_FORMAT, ITA_FLD_LENGTH, ITA_SCRN_TEXT, ITA_VALIDATE_YN, ITA_VIEW_ATTRI, 
    ITA_VIEW_COL_NAME, ITA_START_DATE, ITA_QUERYABLE, ITA_EXCLUSIVE, ITA_KEEP_HISTORY_YN, 
    ITA_DATE_CREATED, ITA_DATE_MODIFIED, ITA_MODIFIED_BY, ITA_CREATED_BY, ITA_DISPLAYED, 
    ITA_DISP_WIDTH, ITA_INSPECTABLE, ITA_CASE)
 Values
   ('PRFT', 'PROJ_DESC_TITLE', 'N', 5, 'N', 
    'VARCHAR2', 200, 'Gen - Project Title', 'N', 'PROJ_DESC_TITLE', 
    'PROJ_DESC_TITLE', TO_DATE('01/01/2014 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'Y', 'N', 'N', 
    TO_DATE('04/03/2014 21:06:38', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('05/22/2014 18:27:43', 'MM/DD/YYYY HH24:MI:SS'), 'ATLAS', 'ATLAS', 'Y', 
    20, 'N', 'MIXED');
COMMIT;
