SET DEFINE OFF;
Insert into HIG_MODULES
   (HMO_MODULE, HMO_TITLE, HMO_FILENAME, HMO_MODULE_TYPE, HMO_FASTPATH_OPTS, 
    HMO_FASTPATH_INVALID, HMO_USE_GRI, HMO_APPLICATION, HMO_MENU)
 Values
   ('WAG9998', 'WAG fix single budget', 'wag9998', 'SQL', NULL, 
    'N', 'Y', 'MAI', 'FORM');
COMMIT;
SET DEFINE OFF;
Insert into HIG_MODULE_ROLES
   (HMR_MODULE, HMR_ROLE, HMR_MODE)
 Values
   ('WAG9998', 'MAI_ADMIN', 'NORMAL');
COMMIT;
SET DEFINE OFF;
Insert into GRI_MODULES
   (GRM_MODULE, GRM_MODULE_TYPE, GRM_MODULE_PATH, GRM_FILE_TYPE, GRM_TAG_FLAG, 
    GRM_TAG_TABLE, GRM_TAG_COLUMN, GRM_TAG_WHERE, GRM_LINESIZE, GRM_PAGESIZE, 
    GRM_PRE_PROCESS)
 Values
   ('WAG9998', 'SQL', '$PROD_HOME/bin', 'lis', 'N', 
    NULL, NULL, NULL, 132, 66, 
    NULL);
COMMIT;
SET DEFINE OFF;
Insert into GRI_MODULE_PARAMS
   (GMP_MODULE, GMP_PARAM, GMP_SEQ, GMP_PARAM_DESCR, GMP_MANDATORY, 
    GMP_NO_ALLOWED, GMP_WHERE, GMP_TAG_RESTRICTION, GMP_TAG_WHERE, GMP_DEFAULT_TABLE, 
    GMP_DEFAULT_COLUMN, GMP_DEFAULT_WHERE, GMP_VISIBLE, GMP_GAZETTEER, GMP_LOV, 
    GMP_VAL_GLOBAL, GMP_WILDCARD, GMP_HINT_TEXT, GMP_ALLOW_PARTIAL, GMP_BASE_TABLE, 
    GMP_BASE_TABLE_COLUMN, GMP_OPERATOR)
 Values
   ('WAG9998', 'FINANCIAL_YEAR', 4, 'Financial Year', 'Y', 
    1, NULL, 'N', NULL, NULL, 
    NULL, NULL, 'Y', 'N', 'Y', 
    NULL, 'N', 'Enter financial year of budget', 'N', NULL, 
    NULL, NULL);
Insert into GRI_MODULE_PARAMS
   (GMP_MODULE, GMP_PARAM, GMP_SEQ, GMP_PARAM_DESCR, GMP_MANDATORY, 
    GMP_NO_ALLOWED, GMP_WHERE, GMP_TAG_RESTRICTION, GMP_TAG_WHERE, GMP_DEFAULT_TABLE, 
    GMP_DEFAULT_COLUMN, GMP_DEFAULT_WHERE, GMP_VISIBLE, GMP_GAZETTEER, GMP_LOV, 
    GMP_VAL_GLOBAL, GMP_WILDCARD, GMP_HINT_TEXT, GMP_ALLOW_PARTIAL, GMP_BASE_TABLE, 
    GMP_BASE_TABLE_COLUMN, GMP_OPERATOR)
 Values
   ('WAG9998', 'ROAD_ID', 3, 'Group name', 'Y', 
    1, NULL, 'N', NULL, NULL, 
    NULL, NULL, 'Y', 'Y', 'Y', 
    'ROAD_ID', 'N', 'Budget Road Group', 'N', NULL, 
    NULL, NULL);
Insert into GRI_MODULE_PARAMS
   (GMP_MODULE, GMP_PARAM, GMP_SEQ, GMP_PARAM_DESCR, GMP_MANDATORY, 
    GMP_NO_ALLOWED, GMP_WHERE, GMP_TAG_RESTRICTION, GMP_TAG_WHERE, GMP_DEFAULT_TABLE, 
    GMP_DEFAULT_COLUMN, GMP_DEFAULT_WHERE, GMP_VISIBLE, GMP_GAZETTEER, GMP_LOV, 
    GMP_VAL_GLOBAL, GMP_WILDCARD, GMP_HINT_TEXT, GMP_ALLOW_PARTIAL, GMP_BASE_TABLE, 
    GMP_BASE_TABLE_COLUMN, GMP_OPERATOR)
 Values
   ('WAG9998', 'WORK_CATEGORY', 1, 'Budget Code', 'Y', 
    1, 'ICB_WORK_CODE IN (SELECT BUD_ICB_ITEM_CODE||BUD_ICB_SUB_ITEM_CODE||BUD_ICB_SUB_SUB_ITEM_CODE FROM BUDGETS)', 'N', NULL, NULL, 
    NULL, NULL, 'Y', 'N', 'Y', 
    NULL, 'N', 'Enter budget code of budget to be adjusted', 'N', NULL, 
    NULL, NULL);
COMMIT;


